### ISSUE TITLE
go: Additional curve25519 routines

### ISSUE THREAD

**Issue by Yawning** [mit-plv/fiat-crypto#1004]
The Go compiler's inliner refuses to inline functions over a certain size, and the maintainers have steadfastly refused to give developers control over the inliner behavior[0].

While I understand the appeal of having `Add`/`Sub`/`Opp` decoupled from `Carry`, it would be nice to additionally have `CarryAdd`, `CarrySub`, and `CarryOpp` that reduce the results.

Concretely this improves EdDSA operation performance by between 4 to 7% on amd64.  I suspect intuitively that the gains on 32-bit targets are likely less significant, but I don't have a target to easily be able to test this on.

[0]: Manually splitting functions up to tiny routines under the inliner budget and/or rebuilding the toolchain to increase the inliner budget are both terrible workarounds.

**Comment by JasonGross** [comment]
Should be relatively easy, just need to find the time to do this.  If someone else wants to give it a go, I can explain what needs to be done.
