### ISSUE TITLE
Bitwidth differences in fiat-json output

### ISSUE THREAD

**Issue by mmcloughlin** [mit-plv/fiat-crypto#1058]
I have been experimenting with code-generation based on the fiat-json output format. As an aside, I'd be interested to know if you consider that a good or bad idea. For now I'm trying to generate output that's mostly equivalent to fiat-go but from the fiat-json files.

One issue is the datatypes reported in the fiat-json output. For example, in the `to_bytes` function for 64-bit curve25519:

https://github.com/mit-plv/fiat-crypto/blob/edba07de3c424cb4d584044d3231afcaca67edd5/fiat-json/src/curve25519_64.json#L3891-L3903

https://github.com/mit-plv/fiat-crypto/blob/edba07de3c424cb4d584044d3231afcaca67edd5/fiat-go/64/curve25519/curve25519.go#L596-L598

A few other languages I looked at (C, Rust, Zig) all generate similar code.

So `u32` in the JSON seems like obviously the wrong type. Presumably `u64` or `u51` would be the most helpful here. The consumer of the fiat-json output somehow needs to know this is a 51-bit subtraction.

**Comment by JasonGross** [comment]
> As an aside, I'd be interested to know if you consider that a good or bad idea. For now I'm trying to generate output that's mostly equivalent to fiat-go but from the fiat-json files.

I would advise against this.  The JSON output is aimed at a joint project we're working on to synthesize assembly, and we make no guarantees about stability of the JSON format we're using, nor the particular meaning of the output.  Can you say a bit more about what the overall goal is?

> So `u32` in the JSON seems like obviously the wrong type.

Presumably bounds analysis guarantees that the outputs will fit in 32 bits.  The other languages are all passing outputs by pointer, and the function declaration forces inputs and outputs to be the same width.  The JSON is not constrained by this rule, and we found it convenient to annotate with tighter bounds specifications.

> The consumer of the fiat-json output somehow needs to know this is a 51-bit subtraction.

Yeah, it's weird that we say "subborrowx" instead of "subborrowxu51".  @dderjoel do you recall why we do it this way? How do you fetch the information about the carry location?

**Comment by mmcloughlin** [comment]
Thanks for getting back to me :)

> I would advise against this. The JSON output is aimed at a joint project we're working on to synthesize assembly, and we make no guarantees about stability of the JSON format we're using, nor the particular meaning of the output. Furthermore, different languages have different requirements for cast insertion and bounds relaxation. Can you say a bit more about what the overall goal is?

My ultimate goal was to generate Go assembly, perhaps with my [`avo`](https://github.com/mmcloughlin/avo) project or a specialized generator. But I thought I'd start by generating generic Go, based on a naive assumption that this wouldn't be that difficult and I'd learn more about the project along the way. The JSON output seemed like the easiest to consume, and the fact that you documented it so clearly in the README did suggest more stability than you indicate here. I'm not particularly concerned about API instability, since I can pin versions and/or make changes to keep up. But it is a problem if the JSON format throws away relevant information from the IR, though I guess if it's enough for your project it could be enough for mine.

> > So `u32` in the JSON seems like obviously the wrong type.
> 
> Presumably bounds analysis guarantees that the outputs will fit in 32 bits. The other languages are all passing outputs by pointer, and the function declaration forces inputs and outputs to be the same width. The JSON is not constrained by this rule, and we found it convenient to annotate with tighter bounds specifications.

Unless there are some other constraints in this problem I'm unaware of, I don't think the outputs are guaranteed to be 32 bits.

The JSON declares the output of the referenced function to be `u64`:

https://github.com/mit-plv/fiat-crypto/blob/edba07de3c424cb4d584044d3231afcaca67edd5/fiat-json/src/curve25519_64.json#L138-L151

What is a consumer supposed to do here? Is the idea to deduce that `subborrowx` actually refers to `subborrowx_u51` by looking at the bounds on the inputs? And then once that's established to prefer the declared return type of `subborrowx_u51` to the datatype on the JSON expression?

> > The consumer of the fiat-json output somehow needs to know this is a 51-bit subtraction.
> 
> Yeah, it's weird that we say "subborrowx" instead of "subborrowxu51". @dderjoel do you recall why we do it this way? How do you fetch the information about the carry location?

Yeah I'm not sure how to do this, other than perhaps guessing it from the declared bounds of the inputs. But as a consumer, I'd prefer to avoid as much logic like this as possible since `fiat-crypto` is verified and my generator would not be. Ideally, the generator is as "dumb" as possible.

I looked at the code a bit, but it wasn't immediately obvious to me what the problem was. On the Go side:

https://github.com/mit-plv/fiat-crypto/blob/edba07de3c424cb4d584044d3231afcaca67edd5/src/Stringification/Go.v#L277-L281

on the JSON side:

https://github.com/mit-plv/fiat-crypto/blob/edba07de3c424cb4d584044d3231afcaca67edd5/src/Stringification/JSON.v#L136-L138

So it would seem that `lg2s` is 51 in the Go generator? Not clear to me from this why it ends up being 32 on the JSON side. At this point I figured someone deeper into the project might know the answer faster than I could figure it out by digging around.

Anyway, thanks again.

**Comment by JasonGross** [comment]
> So it would seem that lg2s is 51 in the Go generator?

Yes

> Not clear to me from this why it ends up being 32 on the JSON side. 

It looks like a bug in our generator.  (This apparently doesn't matter for generation of assembly from the JSON, and we validate the generated assembly, so there's no correctness issue there.). The cast handling is the weakest part of our correctness story, because while the bounds we generate are verified, the way we turn them into casts is not.

The technical issue here is that `int.of_bitwidth false lg2s` rounds down. I guess I forgot that there could be non-power-of-2 numbers here.  The solution is to fix `handle_op` to take the bitwidth and sign separately, and pass `lg2s` directly.  I'll plan to make a PR to do this next week (but feel free to do it yourself if you're so motivated).

**Comment by JasonGross** [comment]
> My ultimate goal was to generate Go assembly, perhaps with my [`avo`](https://github.com/mmcloughlin/avo) project or a specialized generator. But I thought I'd start by generating generic Go, based on a naive assumption that this wouldn't be that difficult and I'd learn more about the project along the way.

Assuming avo does spill allocation for you (does it?), do you want to just clone the Coq code that generates Go and make it generate Go asm or whatever instead?  I'm happy to merge new backends (as long as you're willing to maintain it for as long as you want to keep it in the project), and I'm happy to help explain what's going on in the backend code generation.

**Comment by JasonGross** [comment]
> But it is a problem if the JSON format throws away relevant information from the IR, though I guess if it's enough for your project it could be enough for mine.

All of the codegen throws away some information.  Internally we annotate each expression with the bitwidth it's known to fit inside. During codegen we have to turn this into casts, which is a subtly different thing, given that the inputs might be larger than the outputs and there's no consistent way to specify versions of arithmetic operations with heterogeneous type signatures.

**Comment by dderjoel** [comment]
Hi guys,

> Yeah, it's weird that we say "subborrowx" instead of "subborrowxu51". @dderjoel do you recall why we do it this way? 

I do not recall why we did that. 
I am using the `--no-wide-int` and `--no-primitives` switches, which cause `addcarryx`/`subborrowx` to be used correctly in the mul/sq methods. The problem only seems to occurr in the `to_bytes` method, which I am currently not targetting to generate assembly for, so I did not notice.

> How do you fetch the information about the carry location?

I don't fetch the information from the `datatype` in the body. I 'assume' that the first identifier is a u64, the second identifier is a u1 for `subborrowx`; the same for `addcarryx`. I then generate instructions for that, instead of jumping into any primitive function.

I don't really know if that helps, but long story short, I think it would not break my API, if the datatype would change to `u51` or `u64`, because I dont read the type from there at the moment
However, it would also be confusing in the sense that when `subborrowx` (implicitly) declares `x1` and `x2` as `u51` or `u64`, it would only apply one of the identifiers, not both, because one must be `u1`. 
So I would see two solutions to this
  - the documentation would need to say the datatypes for the operation `subborrowx` is 'whatever `datatype` specifies' for x1 and always `u1` for `x2`
  - the `datatype` property would need to be an array of the same length as the `names`-property, specifying the type of each identifier.

**Comment by mmcloughlin** [comment]
> I am using the `--no-wide-int` and `--no-primitives` switches, which cause `addcarryx`/`subborrowx` to be used correctly in the mul/sq methods. The problem only seems to occurr in the `to_bytes` method, which I am currently not targetting to generate assembly for, so I did not notice.

Yes I'm also using `--no-wide-int`, in the 64-bit case but not the 32-bit case.

> I don't fetch the information from the `datatype` in the body. I 'assume' that the first identifier is a u64, the second identifier is a u1 for `subborrowx`; the same for `addcarryx`. I then generate instructions for that, instead of jumping into any primitive function.
> 
> I don't really know if that helps, but long story short, I think it would not break my API, if the datatype would change to `u51` or `u64`, because I dont read the type from there at the moment However, it would also be confusing in the sense that when `subborrowx` (implicitly) declares `x1` and `x2` as `u51` or `u64`, it would only apply one of the identifiers, not both, because one must be `u1`. So I would see two solutions to this
> 
> * the documentation would need to say the datatypes for the operation `subborrowx` is 'whatever `datatype` specifies' for x1 and always `u1` for `x2`
> * the `datatype` property would need to be an array of the same length as the `names`-property, specifying the type of each identifier.

I think this only addresses one of the two questions here. As I see it there are two issues:

* _What computation does `subborrowx` actually specify?_ Specifically, where is the borrow location that's being extracted? My default assumption is that a `subborrowx` operation with 64-bit inputs would be a 64-bit subtraction not a 51-bit one. As currently written there is no way for the consumer to know it should be a 51-bit subtraction.
* _What type are the return values from the `subborrowx` expression?_ As you say, there are various arguments for this being `u51`, `u64`, `[u64,u1]` or `[u51,u1]`.

It seems to me there are a few solutions:

* Use the `datatype` field to communicate what computation is required. That is, the data type changes to `u51` and that implies a 51-bit subtraction. This is workable but doesn't feel like the right solution to me.
* Set the datatype to `u64` and introduce some other way to specify the required computation. That could be renaming it `subborrowx_u51` or you could perhaps add another parameter like `"operation_size": 51`.

Thoughts?

**Comment by mmcloughlin** [comment]
> It looks like this is indeed a bug in our generator. (This apparently doesn't matter for generation of assembly from the JSON, and we validate the generated assembly, so there's no correctness issue there.). The cast handling is the weakest part of our correctness story, because while the bounds we generate are verified, the way we turn them into casts is not.
> 
> The technical issue here is that `int.of_bitwidth false lg2s` rounds down. I guess I forgot that there could be non-power-of-2 numbers here. The solution is to fix `handle_op` to take the bitwidth and sign separately, and pass `lg2s` directly. I'll plan to make a PR to do this next week (but feel free to do it yourself if you're so motivated).

Thanks! If you can put together a PR that would be much appreciated. I might have time to take a look, but I suspect you'd be able to do it much faster than me anyway. That said, it's not yet clear to me that just changing `u32` to `u51` is the right fix here, see my above comment.

> Assuming avo does spill allocation for you (does it?), do you want to just clone the Coq code that generates Go and make it generate Go asm or whatever instead? I'm happy to merge new backends (as long as you're willing to maintain it for as long as you want to keep it in the project), and I'm happy to help explain what's going on in the backend code generation.

`avo` does not do spill allocation. I decided early on that the core of `avo` should not make too many "magic" decisions for the user. The user should still be in full control of the performance-critical aspects of assembly output, but it just makes the process of reading and writing it easier. Still, it's perfectly possible to implement spilling on top of `avo`, and indeed the `blake3` implementation does this.

Honestly, if I do continue with this project I'm not sure I will use `avo`. Spilling was one concern in the back of my mind already. The other is carry bits, which are variables in `fiat-crypto` output but need to be stored in flags in raw assembly. I hadn't yet checked whether fiat output arranges for at most one or two (with ADX) carry bits to be live at one time. Anyway, `avo` does not have handling for "flag register allocation" so I'd need to implement that myself anyway. Finally, `avo` is amd64 only and I'd like to think about arm64 and other architectures as well. Since the subset of the instruction sets required is small, it seems potentially manageable. I'm assuming that since you're generating assembly already you've dealt with all the issues I've mentioned here, and probably others?

> All of the codegen throws away some information. Internally we annotate each expression with the bitwidth it's known to fit inside. During codegen we have to turn this into casts, which is a subtly different thing, given that the inputs might be larger than the outputs and there's no consistent way to specify versions of arithmetic operations with heterogeneous type signatures.

Yes of course, I wasn't saying codegen shouldn't throw away information, that's inevitable. But it does need to preserve enough to specify what computation must be performed. So in particular, it seems a reasonable requirement that it should be possible to implement an interpreter for the JSON format. In its current form, there are ambiguities that prevent you from doing it.

Would you consider providing a `--lang IR` format that's as much as possible just a raw dump of the internal representation?

**Comment by JasonGross** [comment]
> I'm assuming that since you're generating assembly already you've dealt with all the issues I've mentioned here, and probably others?

I think you won't have too much trouble with carries; IIRC they almost all come from ripple-carry-add chains and we don't parallelize them.  Regarding spill allocation, as I understand it (I haven't actually looked at the code here), there's just an empirical search through the space of possible spill allocations, so I don't think our work will help you here.  As far as I'm aware, spill allocation is essentially the only thing standing in the way of generating assembly directly (though of course we'd be missing out on all the instruction scheduling optimizations if we did nothing but spill allocation).

> Would you consider providing a --lang IR format that's as much as possible just a raw dump of the internal representation?

Yeah, I'm happy to add a flag that just prints out the format of the IR we use in error messages.  If that's missing any information, then I'm happy to just add the relevant information to that representation.
