### ISSUE TITLE
rust: consider labeling library as `no_std`

### ISSUE THREAD

**Issue by vlmutolo** [mit-plv/fiat-crypto#1067]
As far as I can tell, there shouldn't be any issue with adding Rust's `#![no_std]` declaration to the generated library code. This would enable fiat-crypto to be used in embedded environments without an allocator or the full Rust standard library.

This change also wouldn't affect any existing code.

If you don't want to commit the library to never adding allocating code, there's also the option to feature-gate the allocating code behind a default feature (usually named `std`) with something like:

```rust
#![cfg_attr(not(std), no_std)]
```

The above only labels the library as `no_std` when the `std` feature is not turned on (and it would be turned on by default).

**Comment by brycx** [comment]
This is required for Orion to switch to the crate provided on crates.io, as discussed in https://github.com/orion-rs/orion/issues/201

**Comment by JasonGross** [comment]
Should the `#![no_std]` come before (after?)
https://github.com/mit-plv/fiat-crypto/blob/f08e5c5a1ceda7aea538820821714fb0df7d59c4/fiat-rust/src/p224_32.rs#L20-L21

If we do eventually want to add some function that allocates, can you give an example of how to use `#![cfg_attr(not(std), no_std)]`?  (And whether or not adding this means removing `#![no_std]`?)

Feel free also to submit a PR updating the code generator at
https://github.com/mit-plv/fiat-crypto/blob/f08e5c5a1ceda7aea538820821714fb0df7d59c4/src/Stringification/Rust.v#L72-L75
and/or
https://github.com/mit-plv/fiat-crypto/blob/f08e5c5a1ceda7aea538820821714fb0df7d59c4/src/Stringification/Rust.v#L377-L379

**Comment by brycx** [comment]
> Should the #![no_std] come before (after?)

Since `#![no_std]` is a crate-level attribute it actually goes into the crate root, i.e `lib.rs`.

> If we do eventually want to add some function that allocates, can you give an example of how to use #![cfg_attr(not(std), no_std)]? (And whether or not adding this means removing #![no_std]?)

What @vlmutolo is suggesting is that (correct me if I'm wrong Vincent), we could add `#![cfg_attr(not(feature = "std"), no_std)]` to `lib.rs`, instead of `#![no_std]`. Say we'd want to add a function later that uses something like `Vec<u8>`, then we'd do:

```rust
#[cfg(feature = "std")]
pub fn foo() -> Vec<u8> {}
```

We'd also need to add the following to `Cargo.toml`:

```toml
[features]
default = [ "std" ]
std = []
```

This approach is similar to how Orion handles it.

**Comment by vlmutolo** [comment]
Yes, this is exactly what I meant. 

>  (And whether or not adding this means removing #![no_std]?)

Using the way that @brycx described above, you could add functions that require std that would be "feature-gated" on an "std" feature. You'd probably also make that the default feature, so users of the library generally don't have to think about whether or not to enable "std". 

Then, if a user needs "no std", they can disable the default features, which will also disable compilation of the function(s) added that do need std, ie `foo` in @brycx 's example.

**Comment by brycx** [comment]
Actually `Vec<u8>` may be a bad example, since this can be used in `no_std` through `alloc`, but the approach is still applicable for other things not in `alloc` nonetheless.
