### ISSUE TITLE
reducing CI latency

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#1076]
#1072 took ~24h to run. That's quite a friction for cleanup changes.

Do we really need the full array of CI jobs that we have right now? What about using a shortlist of representative use cases instead, like the following

- coq master as a coq developer would use it
- OS X and Coq as a decent setup on a corporate laptop would have
- Ubuntu coq
- Debian coq
- latest coq

that'd be 5 coq runs, down from the 10 we have right now. @JasonGross wdyt?

**Comment by JasonGross** [comment]
I think this would be a good set to run on PRs, and maybe keep the full suite for the tip of master?

**Comment by JasonGross** [comment]
Closed (hopefully) by #1077
