### ISSUE TITLE
Rust: Exposing the Poly1305 modules

### ISSUE THREAD

**Issue by brycx** [mit-plv/fiat-crypto#1089]
Is there a reason that the current `poly1305_32` and `poly1305_64` modules are not exposed publicly, such that they are available from the crate?

If not, I can create a quick PR to add this (or any other missing modules, if existent, for that matter).

**Comment by JasonGross** [comment]
My guess is that we just didn't realize we had to update the crate to expose them.  I'd be happy to merge a PR that exposes them.  Even better would be a PR that updates the Makefile to automatically regenerate the relevant file anytime the Makefile changes.

**Comment by brycx** [comment]
> Even better would be a PR that updates the Makefile to automatically regenerate the relevant file anytime the Makefile changes.

Not sure I understand. Could you point me in the right direction? I haven't worked with a lot of Makefiles and couldn't at a glance tell from the current where points of interest would be.

**Comment by JasonGross** [comment]
@brycx I've created #1091

**Comment by brycx** [comment]
Much obliged.
