### ISSUE TITLE
u128 in json, where in c its implicitly u64

### ISSUE THREAD

**Issue by dderjoel** [mit-plv/fiat-crypto#1099]
Hi,
I noticed, that in the JSON-version a `u128` type is used where the C-version implicitly has a `u64` type for a sub expression calculating `u128 x6`.
Looking at the carry-sq method in poly1305-64 [in JSON](https://github.com/mit-plv/fiat-crypto/blob/079363c3d37bf075ecdf920d7a28f5ee55b52dea/fiat-json/src/poly1305_64.json#L1396-L1428), specifically Line 1416

Whereas in the [C-Version ](https://github.com/mit-plv/fiat-crypto/blob/079363c3d37bf075ecdf920d7a28f5ee55b52dea/fiat-c/src/poly1305_64.c#L289) we have the parenthesis , like so
`x6 = ((fiat_poly1305_uint128)(arg1[1]) * (x2 * 0x2));` with `x2` being a `uint64_t`, making the sub expression `x2 * 0x2` a uint64, which according to bounds also fits.

My question is, if the JSON could also emit `u64` instead of `u128` for sub expressions, known to fit in u64. Otherwise I'd need to parse that out myself (would be rather much work on my end, tracking the bit widths of the intermediate results in between)

**Comment by JasonGross** [comment]
I'm working on a PR that adds `--emit-all-casts` which will drop the fancy cast adjustment logic and just insert casts as they're inferred (i.e., casts to describe the types of expressions rather than to constrain them).  However, this is so verbose that it makes p384 x32 take over 45 minutes.  What are your thoughts on adding this and dropping the autogeneration of secp256k1_32.json and p384_32.json?

**Comment by JasonGross** [comment]
Ah, maybe I can just optimize the synthesis pipeline a bit.  It seems that (at least one of) the bottleneck(s) is that `List.rev` is quadratic in the length of the list, and we invoke `List.rev` a couple times on the list of lines we're printing to the file.

**Comment by dderjoel** [comment]
I don't need the auto generated files anyway. I always generate them on the fly, let alone 32-bit versions. IIRC p434_32 is also not automatically generated. So yes, I'm fine with that!
