### ISSUE TITLE
Anomaly in our nsatz tactic

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#11]
[Our `nsatz` variant raises an anomaly in some cases](https://coq.inria.fr/bugs/show_bug.cgi?id=4858); the standard library one does not.  It's not terribly hard to work around (just clear hypotheses of the form `x = x`), but I figured I'd record it here.

**Comment by andres-erbsen** [comment]
If I understand correctly, there is not much that we can do about this right now. Maybe we should make a milestone called `non-actionable` or something like that.

**Comment by JasonGross** [comment]
I'd be curious to know where the anomaly comes from, and what we're doing differently from the stdlib.  Maybe `non-blocking` or `far-future` or `curiosity` would be a better tag?

**Comment by andres-erbsen** [comment]
fixed upstream: https://github.com/coq/coq/pull/243
