### ISSUE TITLE
Have 6_4op like 9_4op

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#110]
We should revert https://github.com/mit-plv/fiat-crypto/commit/4d3d21d604243bc63774f4931f2313e20cdaf515 but use `6` rather than `10`, to remove the dummies from https://github.com/mit-plv/fiat-crypto/blob/master/src/Specific/GF25519Reflective/Reified/LadderStep.v#L32

**Comment by andres-erbsen** [comment]
Please no.
