### ISSUE TITLE
fsatz _nonzero_tac does not work on fractions

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#114]
x, y, sqrt_a : F
        H : sqrt_a^2 = a
        H0 : (sqrt_a / y)^2 <> d
        ============================
        d * y^2 - a <> 0

We probably want to call `fsatz` recursively or something, but obviously we don't want to loop...

**Comment by andres-erbsen** [comment]
I think there is more going on here than just avoiding silly loops. I found a case where the only way to prove one denominator nonzero is to

1. introduce the contradictory hypothesis that the denominator is zero
2. prove *another* denominator nonzero using the new hypothesis
3. derive a contradiction; conclude that the original denominator is nonzero

https://github.com/mit-plv/fiat-crypto/blob/fsatz-nonzero-weirdness/src/Algebra/Field.v#L311

I don't know how this issue generalizes, or what we want to do about this. I think I would be perfectly fine if this case wasn't solved, except that this breaks the invariant that if `assert (_); fsatz` succeeds then `fsatz` should succeed (for example in https://github.com/mit-plv/fiat-crypto/blob/0ab98d3380033b58162015656f435ae90b936856/src/CompleteEdwardsCurve/CompleteEdwardsCurveTheorems.v#L98). Any insight on this would be appreciated.

**Comment by JasonGross** [comment]
Ew, really?  Okay, here's an alternate loop-avoider:

```coq
Ltac clear_nonzero_assum :=
      repeat match goal with
             | [ H : ?x <> 0 -> _ |- _ ] => clear H
      end.

Ltac _nonzero_tac fsatz_tac :=
      repeat match goal with
             | [ H : ?x <> 0 -> _ |- _ ]
               => let H' := fresh in
                  assert (H' : x <> 0) by (clear_nonzero_assum; fsatz_tac); specialize (H H')
             | [ H : ?x <> 0 -> _ |- _ ]
               => let H' := fresh in
                  assert (H' : x <> 0) by (clear H; fsatz_tac); specialize (H H')
             end.
```

I have the `clear_nonzero_assum` case first as a performance optimization, because we want to discharge as many of the nonzero assumptions as possible before we try to discharge them recursively.
