### ISSUE TITLE
Unused functions in fiat-c trip -Wunused-function

### ISSUE THREAD

**Issue by davidben** [mit-plv/fiat-crypto#1164]
GCC and Clang's -Wunused-function seem to trip unused functions if the consumer doesn't use every one of them. I'm currently looking at wrapping the include in pragmas, but this is kind of annoying. Some ideas...

1. Tag all the generated functions with `__attribute__((unused))`, or...
2. Mark every function `static inline`, which reliably silences the warning in GCC and Clang. One detail to keep in mind, since fiat's currently' doing `__inline__` with a `__GNUC__` check: while Clang usually defines `__GNUC__`, it doesn't when building as `clang-cl` (MSVC-like Clang). I usually write `defined(__GNUC__) || defined(__clang__)` to check for GCC extension support. Or you could just use plain `static inline` which should work on remotely recent compilers, or...
3. Stick some macro in front of every function, so the consumer can customize it.

**Comment by JasonGross** [comment]
Probably the easiest thing is to change
https://github.com/mit-plv/fiat-crypto/blob/f1ccc4bd4f2b42ceab152780a70256371045f086/src/Stringification/C.v#L140
to 
```coq
 ["#if defined(__GNUC__) || defined(__clang__)"] 
```
?  Does this sound good, or do you want me to implement (1)?  (And do you want to make this change, or should I?)

**Comment by JasonGross** [comment]
See also #820

**Comment by JasonGross** [comment]
(If you have a solid preference of any of the options, I'm happy to implement that one.)

**Comment by davidben** [comment]
`__GNUC__ || __clang__` isn't _quite_ sufficient. There also seem to be some functions that aren't marked inline.

Although, I'm also not sure if worrying about ancient versions of compilers makes much sense. Personally I'd just use plain `static inline`, on the assumption that everyone either implements C99 or is MSVC. But if you all really want to support those compilers, that works too I suppose. :-)

**Comment by JasonGross** [comment]
> There also seem to be some functions that aren't marked inline.

This can be fixed by changing https://github.com/mit-plv/fiat-crypto/blob/f1ccc4bd4f2b42ceab152780a70256371045f086/Makefile#L275 to 
```makefile
C_EXTRA_ARGS := --inline --static --use-value-barrier
```
