### ISSUE TITLE
Coq 8.5 timeouts on travis

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#122]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/207100793/log.txt
"The job exceeded the maximum time limit for jobs, and has been terminated."

`src/WeierstrassCurve/WeierstrassCurveTheorems (real: 2073.61, user: 2070.73, sys: 1.44, mem: 2009060 ko)` is new, of course other stuff is slow as well.

**Comment by JasonGross** [comment]
Yeah, I was noticing that WeierstrassCurveTheorems was really slow.  Can we do something about that?

**Comment by andres-erbsen** [comment]
I don't have easy solutions.

https://github.com/mit-plv/fiat-crypto/pull/111/commits/9745f92ffeee07fed5f0dc7d9f2351affd5c2c83#diff-ac5f33d32601c240bed22e951c18f7d1R147 has the last fine-grained timings. 

The "hard" cases are a couple of seconds each, and there is maybe a hundred non-trivial cases. We could probably reduce the number of cases by half by proving commutativity first, and then deduplicating the associativity goals using that.

The log also shows that one of the cases takes most of the time, which is I would guess is the same case which fails with characteristic at least 3, even though it should succeed. I don't know what's wrong with that, could be another nsatz bug.

**Comment by JasonGross** [comment]
There's now a `lite` target (see #129); should we have travis build this target instead?

**Comment by andres-erbsen** [comment]
how about 8,5 builds lite and 8.6 still builds everything that it can?

On March 15, 2017 10:40:54 AM PDT, Jason Gross <notifications@github.com> wrote:
>There's now a `lite` target (see #129); should we have travis build
>this target instead?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mit-plv/fiat-crypto/issues/122#issuecomment-286822036

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
