### ISSUE TITLE
Request for a "Lite" version.

### ISSUE THREAD

**Issue by ejgallego** [mit-plv/fiat-crypto#129]
Hi folks,

it is great to be able to test fiat-crypto in Coq's travis, however right now we are just at the limit of what the build time allows, which makes the builds fail often by overtime.

How could we proceed to modify the makefile such that we cut around 5 minutes of build time, without being too fragile?

Thanks

**Comment by andres-erbsen** [comment]
I propose we disable WeierstrassCurveTheorems if running on travis CI.

**Comment by ejgallego** [comment]
Cool, thanks @andres-erbsen , how can I do that in a reliable way?

My fear is that if I add to our travis script the logic to remove that files, when some other new files that depend on Weierstrass are added our script will break.

**Comment by JasonGross** [comment]
I've pushed a commit that enables you to `make lite` (others should feel free to change the name of the target to something else, if there's a more standard name).  There's currently nothing that depends on `WeierstrassCurveTheorems`, and if we add something and forget to exclude it from the `lite` target, that'll be our bug to fix.

**Comment by ejgallego** [comment]
Thanks a lot Jason!

**Comment by ejgallego** [comment]
Hopefully we manage to get more time from Travis in the future.

**Comment by maximedenes** [comment]
It seems the `lite` target still times out for Coq 8.6, so I have two questions
1. Could some dependencies be removed from that target?
2. Could you have your own Travis test 8.6 with that `lite` target?

**Comment by JasonGross** [comment]
1. What are the last few files in the log where it times out?  (Or just point me at the log.) I'll remove some.
2. That's tricker; we actually build more than what's in the lite target, and we don't time out, because we're not also building Coq.  If you have a way that we can continue not building Coq in some configurations, but build it in others, I can update our Travis config to do that.

**Comment by andres-erbsen** [comment]
It is also the case that the "non-lite" files are perhaps the most interesting to test Coq on -- the currently excluded `Curves/Weierstrass/AffineProofs` has been the subject of a couple of Coq issues. We could make the build a bunch faster if we excluded all proofs in the curves directory, but I think that would defeat the point. The same applies to the fiat-crypto synthesis and integration tests. OTOH `src/Spec/Test` uses Coq in very simple ways, and still takes a minute and some, so it can probably be excluded?

**Comment by JasonGross** [comment]
Note that Travis has a hard limit of one hour, and that while the `lite` target is tested on Travis, I believe the default target is tested in benchmarking.  As long as the bench keeps testing the full package, I think it's fine to restrict Travis more.

You can adjust the lite target by adding things to `HEAVY_VO_FILES`

**Comment by JasonGross** [comment]
@maximedenes Does this still happen?

**Comment by JasonGross** [comment]
Closing this for lack of information; I can reopen if there's still an issue.
