### ISSUE TITLE
Asymmetry between field_simplify_eq and field_simplify_eq in

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#13]
It seems that `field_simplify_eq` puts the original goal *first*, while `field_simplify_eq in H` puts it last.  This makes it a pain to write automation that calls both of them.  I'm going to try to work around this in `common_denominator_in`, so that tactics above that don't see this issue (I'm going to arbitrarily pick that the original goal should come first, but feel free to suggest otherwise).  We could also see if we could do anything about `field_simplify_eq in` itself.

**Comment by andres-erbsen** [comment]
Could we choose to always call `field_simplify_eq` and never `field_simplify`? I don't recall any good reason to use the latter.

**Comment by JasonGross** [comment]
Sorry, I had a typo.  I'm actually comparing `field_simplify_eq` against `field_simplify_eq in H`

**Comment by JasonGross** [comment]
I've worked around this to the best of my ability without modifying Coq, so I'm going to close this.  Reported as [bug #4888](https://coq.inria.fr/bugs/show_bug.cgi?id=4888).
