### ISSUE TITLE
Cannot install `coq-fiat-crypto.0.0.13` package

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [mit-plv/fiat-crypto#1367]
Trying to run `opam install coq-fiat-crypto.0.0.13` results in the error:

```
File "./src/Bedrock/End2End/X25519/MontgomeryLadder.v", line 7, characters 0-33:
Error: Cannot find a physical path bound to logical path compiler.Pipeline.
```

(I can also not get the `coq-fiat-crypto.dev` package to build, but I guess the package in `coq-released` should be a bit more stable...)

**Comment by JasonGross** [comment]
Try 0.0.15; does it all work now?  (Both 0.0.15 and dev should work)

**Comment by JasonGross** [comment]
Please re-open if 0.0.15 / 0.0.16 / coq-fiat-crypto.dev still don't work
