### ISSUE TITLE
Duplication between Tuple.fieldwise and Tuple.pointwise2

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#137]
We have two definitions that are almost the same; the difference between `Tuple.fieldwise` and `Tuple.pointwise2` is that `Tuple.fieldwise` conjoins the relatedness in the opposite order from `Tuple.pointwise2`.  The order of `Tuple.pointwise2` is what needs to stay the same for lining up with the reflective pipeline; do we care about the ordering of `Tuple.fieldwise`?

**Comment by andres-erbsen** [comment]
All uses of `Tuple.fieldwise` that I can think of don't care about it's definitional structure on opaque tuple sizes.
