### ISSUE TITLE
Unintentional axiom dependence

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#143]
Did you know that `Require Nsatz` causes `tauto` to use classical axioms when it needs them?  [Well, it does.](https://coq.inria.fr/bugs/show_bug.cgi?id=5444)

```coq
Print Assumptions Crypto.Algebra.Ring.nonzero_hypothesis_to_goal.
```
gives
```coq
Axioms:
Classical_Prop.classic : forall P : Prop, P \/ ~ P
```

Interestingly, we never use this lemma anywhere.  Should we remove it?

**Comment by andres-erbsen** [comment]
Yes.
