### ISSUE TITLE
Split MontgomeryX into two files

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#144]
It's annoying when I have to wait 15 minutes for WeierstrassCurveTheorems to build just to use the definition of `xzladderstep`, which (I think) doesn't depend on the theorems.

**Comment by JasonGross** [comment]
(I guess to do this, you'll also need to move `MontgomeryCurveTheorems.M.opp` somewhere else, to make it not depend on the theorems.)

**Comment by andres-erbsen** [comment]
Meh. This is a pure build-time hack.

I do think it is justified in this case, but splitting conceptually related code into different files causes significant overhead for my workflow.

**Comment by JasonGross** [comment]
Oh, man, I totally forgot that I could `make quick` and bypass all the proofs.  It's plausible that there's no good reason to do this if it messes with your pipeline.

**Comment by andres-erbsen** [comment]
Split files and a faster weierstrass proof are coming

**Comment by JasonGross** [comment]
Thanks!

**Comment by andres-erbsen** [comment]
This happened in #145
