### ISSUE TITLE
We should add [Proof using] statements to our theorems

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#146]
It will make `make quick` faster.  I wrote a [script here](https://github.com/JasonGross/coq-tools#proof-using-helper) that we can use.

**Comment by andres-erbsen** [comment]
What is the meaning of `Proof using`, what does it do? I remember trying to read the docs once, and not iunderstanding it.

**Comment by JasonGross** [comment]
`Proof using` describes which section variables get used in a proof.  The primary purpose is so that `make quick` or `coqc -quick` doesn't have to run the entire proof script when all it really needs to know is which section variables to quantify over when you end the section.

**Comment by JasonGross** [comment]
It does a few other things as well, such as making `Qed` error if you use a section variable not described in the `Proof using` statement, and it might or might not clear variables not so mentioned; I don't recall.

**Comment by andres-erbsen** [comment]
So `Proof using Type` is code for none?

**Comment by JasonGross** [comment]
`Proof using Type.` and `Proof using .` mean the same thing: use only section variables occurring in the type of the theorem statement.

**Comment by andres-erbsen** [comment]
Nevermind, https://coq.inria.fr/refman/Reference-Manual009.html does actually explain it. I just couldn't figure out what it is good for until now.
