### ISSUE TITLE
`super_nsatz` clears `H: 1 + 1 <> 0`

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#15]
In response to #10, I was trying to port `CompleteEdwardsCurve` proofs from `field_algebra` to `super_nsatz`. However, it seems that `super_nsatz` clears `H: 1 + 1 <> 0`, making a provable goal unprovable.

https://github.com/mit-plv/fiat-crypto/commit/5f522eedfece8db63ddd95360b58e14fefcdad9a

**Comment by JasonGross** [comment]
Do you get it back if you run `split_field_inequalities`?

**Comment by JasonGross** [comment]
> I should probably add that to the end of

On the other hand, I'm not sure it's a good idea to put much work into the kind of goals that `super_nsatz` leaves over; the intended use is "pose all the facts you need, then finish with `super_nsatz`".  If this is the spec, and left-over goals are just meant for debugging purposes, then I'm not sure whether or not it makes sense to clean up.  What do you think?

**Comment by andres-erbsen** [comment]
I would definitely appreciate if `super_nsatz` won that goal right away -- I posed all facts that are necessary before calling `super_nsatz`. In particular, asserting the goal that `super_nsatz` leaves over under the original hypotheses, `assumptions` solves the goal.

**Comment by andres-erbsen** [comment]
Yes, `split_field_inequalities` gives the missing assumption back.

**Comment by JasonGross** [comment]
Try `repeat super_nsatz` ;)

I wrote the tactic under the assumption that `nsatz` would not leave over side-conditions.  I'll go fix this now.

**Comment by JasonGross** [comment]
Try it now with 91a712295078756f162113d30412c666679c90ac ?

**Comment by JasonGross** [comment]
Er, I mean the one after that commit; that one doesn't actually compile.

**Comment by andres-erbsen** [comment]
Now I get the following subgoal left over:

    F : Type
    eq : F -> F -> Prop
    zero : F
    one : F
    opp : F -> F
    add : F -> F -> F
    sub : F -> F -> F
    mul : F -> F -> F
    inv : F -> F
    div : F -> F -> F
    H : field
    a : F
    sqrt_a : F
    a_nonzero : sqrt_a <> 0 /\ sqrt_a <> 0
    a_square : exists sqrt_a0 : F, sqrt_a0^2 = a
    d : F
    d_nonsquare : forall sqrt_d : F, sqrt_d^2 <> d
    x1 : F
    y1 : F
    x2 : F
    y2 : F
    a_square' : sqrt_a^2 - a = 0
    H0 : sqrt_a^2 * x1^2 + y1^2 - (1 + d * x1^2 * y1^2) = 0
    H1 : sqrt_a^2 * x2^2 + y2^2 - (1 + d * x2^2 * y2^2) = 0
    H2 : (d * x1 * x2 * y1 * y2)^2 - 1 = 0
    e : sqrt_a * x2 + y2 = 0
    H5 : (1 + 1) * ((sqrt_a * x2 - y2) * (sqrt_a * (x1 * y1))) <> 0
    H3 : Algebra_syntax.equality (opp (1 + 1)) Algebra_syntax.zero
    ============================
     (1 + 1) * ((sqrt_a * x2 - y2) * (sqrt_a * (x1 * y1))) = 0  

Notice the `Algebra_syntax.equality` -- `nsatz` reification works in terms of standard library wrapper definitions, and the extra goal is generated after reification and reflection by a applying a lemma of the form `c*x^p = 0 -> c <> 0 -> x = 0`.

**Comment by andres-erbsen** [comment]
Ugh, I didn't mean t close this.

**Comment by andres-erbsen** [comment]
https://github.com/mit-plv/fiat-crypto/commit/fa9f999603fa45eb490b52439b7108c09eadac21

**Comment by JasonGross** [comment]
Huh.  So you're saying we should include a call to `dropRingSyntax` after every call to `nsatz`?  Why not just fold `dropRingSyntax` into the leavings of `nsatz`?

**Comment by JasonGross** [comment]
(Note that `dropRingSyntax; nsatz` solves this goal you have.)

**Comment by andres-erbsen** [comment]
I think changing our `nsatz` to include `dropRingSyntax` makes sense in our use cases. The reason why I didn't do this is that proofs that do use `Algebra_syntax` wrappers would probably be sad if a tactic unfolded them. Maybe we just shouldn't support that.

**Comment by JasonGross** [comment]
Maybe make a `raw_nsatz` or do something like
```coq
Module Algebra_syntax.
  Ltac nsatz := ...
End Algebra_syntax.
Ltac nsatz := Algebra_syntax.nsatz; dropRingSyntax.
```
or something, so we can have a decent story for `nsatz` with `Algebra_syntax` (and if we want to submit a PR to the standard library, there's a clean story about what to submit).

I think we should either build everything around using `Algebra_syntax`, or build everything around not using it (and the things that put compatibility wrappers for (un)folding at the earliest possible points); using it in some places and not others is a recipe for headaches.

**Comment by andres-erbsen** [comment]
I went with the code snippet you suggested in https://github.com/mit-plv/fiat-crypto/pull/16 and it seems to be working out.
