### ISSUE TITLE
Installation problems on macOS: Package `coq-core.plugins.ltac' not found

### ISSUE THREAD

**Issue by tarcieri** [mit-plv/fiat-crypto#1558]
I've encountered the following attempting to install on macOS (Ventura 13.2, both ARM and Intel):

```
CAMLC -c src/Rewriter/Util/plugins/ltac2_extra.mli
ocamlfind: Package `coq-core.plugins.ltac' not found
```

`coq` and `ocaml-findlib` were installed via Homebrew.

It seems similar to this?

https://github.com/coq/coq/issues/15635

(Also separately, have you considered having a `Dockerfile` that provides a reproducible build on e.g. Ubuntu?)

**Comment by andres-erbsen** [comment]
The Coq issue you linked seems indeed related -- perhaps the Homebrew package for Coq does not have the `META` file in the right location. If you're willing to use OPAM, we have CI-tested installation steps [here](https://github.com/mit-plv/fiat-crypto/blob/master/.github/workflows/coq-macos.yml#L43-L61). Alternatively, the [Coq Platform](https://github.com/coq/platform/blob/main/doc/README_macOS.md) also includes Fiat Cryptography.

**Comment by tarcieri** [comment]
I resolved the issue by installing with `opam`, which worked great
