### ISSUE TITLE
CSE/AC the squaring function used in `xzladderstep`

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#158]
We want to eliminate common subexpressions when doing field element multiplications `x*x`. These common subexpressions need to be recognized modulo associativity and commutativity. The carrying code would expand in size exponentially if `let`-binders were inlined, so that shouldn't happen during CSE (as a workaround, we could CSE a non-carrying squaring function and then plug it in, but meh).

**Comment by JasonGross** [comment]
Basically implemented (without proofs) at https://github.com/JasonGross/fiat-crypto/tree/zzz-cse-square

But didn't we find that this made things slower?

**Comment by andres-erbsen** [comment]
It did make the first benchmark I ran marginally slower, but I would suspect it was compiler noise, not a real effect. The effectiveness of CSE depends a lot on what the input code looks like, I would not be surprised if it did end up being useful. So let's say it is not a priority to prove it for now, but we should include a version that uses it in any benchmarks we run and prove it if we deem the performance to be worth the work. So if there is anything that could be merged with an admit for correctness, perhaps we should do so.

**Comment by JasonGross** [comment]
@andres-erbsen Do you want to have CSE'd versions built by default, alongside the non-CSE'd versions?  The simplest way to do this will make both versions' correctness proofs depend on the CSE admits; is that acceptable?

**Comment by briansmith** [comment]
If the CSE version isn't 20% faster then doesn't that mean it isn't working the way it is expected to work? When we replaced the non-CSE code with hand-written CSE'd code, it was 20% faster.

**Comment by andres-erbsen** [comment]
The CSE experiments we did at HACS were on curve25519-donna, not fiat-crypto output. This was because curve25519 donna does the inlining in the C compiler but fiat-crypto produces already inlined C source, making later experimentation inconvenient. The relevant timings are as follows:

    curve25519-donna with fsquare=fmul (approximating no source-level CSE): 70us
    curve25519-donna: 61us
    curve25519-fiat51: 75us
    curve25519-fiat51+CSE: 75us

The CSE seems to be doing something: it gets `fsquare` down to 70 operations from 90. However, there is an even bigger difference between between our output and curve25519-donna: fiat-crypto currently scales the outputs products, whereas curve25519-donna scales one of the [inputs to each partial product](https://github.com/agl/curve25519-donna/blob/master/curve25519-donna-c64.c#L159): `19*(a*b)` vs `(19*a)*b`. The former does two 64-bit multiplications, the latter does a 32-bit multiplication and a 64-bit multiplication. Changing just that part in donna results in a slowdown that again counts for approximately half of the difference between fiat-crypto and donna. I am guessing that once we improve our code in this respect, specializing the squaring operation at the C source level will become as effective as in donna. I have no real explanation why CSE improves donna and not our code, though. Or perhaps we were wrong to attribute the differences between curve25519-donna `fmul` and `fsquare` to CSE (but I still don't know what else it could be).

**Comment by andres-erbsen** [comment]
Since we added a bit of manual (verified) optimization to our curve25519 code, CSE does not do anything anymore.
