### ISSUE TITLE
Make a definition for base conversion

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#160]
For now, let's implement it by chaining `to_associational` and `from_associational`. The definition obtained in this manner is suboptimal (it needlessly uses double-width words), but I think it will do. The same interface can later be implemented using a select-and-assemble algorithm.

**Comment by JasonGross** [comment]
Is this https://github.com/mit-plv/fiat-crypto/blob/b591ae00c3f6512c6be1469c865d4113ad33b04e/src/Experiments/SimplyTypedArithmetic.v#L543-L545 ?

**Comment by jadephilipoom** [comment]
Yes, that should be it.
