### ISSUE TITLE
inversion / divstep code broken?

### ISSUE THREAD

**Issue by hannesm** [mit-plv/fiat-crypto#1605]
Dear all,

I've been using the C code generated by fiat-crypto 2a07751f37af74edeac47b19bd51810bc99b91a1 (May 29th 2022) for a crypto library in OCaml. Now, due to some issue on a macOS machine, I wanted to update that code to a recent fiat-crypto commit (namely 1dc6b3a05dcfcb1e94b2a26c3fd6af0bd6788837).

I noticed in my test suite that the inversion code (relying on divstep) changed in commit 822615fca330cb87d16789d29fb77dd8bd4df87c, and a commit from before that works fine, and after does not anymore.

So, I struggle: did the semantics of `divstep` change? Is the inversion_template being tested in CI?

If you like to take a look: this commit https://github.com/mirage/mirage-crypto/commit/38adeb669f5da31b0ab26642a822e4e018a1e063 works fine (`dune build tests/test_ec.exe && _build/default/tests/test_ec.exe`); while this commit does not https://github.com/hannesm/mirage-crypto/commit/cb578f12aa3728b1a1fd41d104a465534eabddbb

Any help / clarification is highly appreciated... it may as well be that the issue is in my interfacing of the fiat-code.

**Comment by andres-erbsen** [comment]
I have just briefly looked into this, but I think you found a bug. Specifically removing the cast from
[`x74 = (fiat_p256_uint1)(x22 & 0x1);`](https://github.com/mit-plv/fiat-crypto/commit/1dc6b3a05dcfcb1e94b2a26c3fd6af0bd6788837#diff-660c1986828a90bf989b69dd15b1dcac887274ac8c8ddbf56d75b33c1ed06371L1937) looks bad given [`fiat_p256_cmovznz_u64(&x22, x3, (arg3[0]), x12);`](https://github.com/mit-plv/fiat-crypto/commit/1dc6b3a05dcfcb1e94b2a26c3fd6af0bd6788837#diff-660c1986828a90bf989b69dd15b1dcac887274ac8c8ddbf56d75b33c1ed06371L1902) and [`typedef unsigned char fiat_p256_uint1;`](https://github.com/mit-plv/fiat-crypto/commit/1dc6b3a05dcfcb1e94b2a26c3fd6af0bd6788837#diff-660c1986828a90bf989b69dd15b1dcac887274ac8c8ddbf56d75b33c1ed06371L21). Overall (assuming I'm eyeing the right thing) the `uint1`-means-`uint8` typedef is the part that is just wrong (casting to a "real" uint1 should truncate!); the redundant-and-removal optimization just unearthed the issue. There are no proofs about the (Coq->C/Rust/etc) pretty-printers, and I can't find any tests for divstep, so this would be exactly the kind of issue that we are not prepared against. My hunch is it's probably the right one.

I'll see how granular of a revert I can get in.

Given that you have tests for divstep, you could try out the C code printed using the more rigorous Bedrock2-based backend of fiat-crypto... https://github.com/mit-plv/fiat-crypto/blob/master/fiat-bedrock2/src/p256_64.c#L1669 would be the file for p256. But there's a number of reasons this backend wouldn't be a drop-in replacement, Bedrock2 being untyped and not having intrinsics are perhaps the most blatant examples. [It does keep the required truncation, though](https://github.com/mit-plv/fiat-crypto/blob/1dc6b3a05dcfcb1e94b2a26c3fd6af0bd6788837/fiat-bedrock2/src/p256_64.c#L1826), as proven.

**Comment by andres-erbsen** [comment]
I reverted the redundant-& optimization as a hotfix (ab4d8ac2ed2473b591753d86f19d7f1915797ddf and c79cf6061a60ead08730658fa6f38a5f260ad7d3); I hope this gets you unstuck. Continued unsoundness of the IR-to-C printer will be tracked at https://github.com/mit-plv/fiat-crypto/issues/1606.

Thank you for the report! Please let us know if there's anything else we can help you with here.

**Comment by hannesm** [comment]
Thanks for your fix, this indeed works fine for me.

**Comment by JasonGross** [comment]
> I reverted the redundant-& optimization as a hotfix ([ab4d8ac](https://github.com/mit-plv/fiat-crypto/commit/ab4d8ac2ed2473b591753d86f19d7f1915797ddf) and [c79cf60](https://github.com/mit-plv/fiat-crypto/commit/c79cf6061a60ead08730658fa6f38a5f260ad7d3));

We should probably parametrize the pass on a list of acceptable bitwidths to remove, then pass in [8; 16; 32; 64; 128] or something in BoundsPipeline
