### ISSUE TITLE
Make for-loops more transparent

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#164]
The current for-loop framework (`src/Util/ForLoop.v`) probably works, but is highly non-obvious.  Building on #163 and [some comments there](https://github.com/mit-plv/fiat-crypto/pull/163#issuecomment-296883467), we should figure out a way to make it better.

One proposal that I can think of, modified from https://github.com/mit-plv/fiat-crypto/pull/163#issuecomment-296883467, is to base for-loops on while-loops, and have the following interface and equations:
```coq
Definition while {T} (max_iter : ℕ) (initial : T) (test : T → bool) (body : T → T) : T.
Theorem while_def {T} n (v : T) test body
 : while (n.+1) v test body =
    if test v
    then while n (body v) test body
    else v.
Theorem while_monotone
 : ∀ T (v₀ : T) test body n m,
    let v₁ := while n v₀ test body in
    let v₂ := while m v₀ test body in
    n ≤ m
    → test v₁ = false
    → v₁ = v₂.
Theorem while_ind
 : ∀ T (P : T → Prop) n v₀ test body,
    P v₀
    → (∀ v, test v = true → P v → P (body v))
    → P (while n v₀ test body).
```
Then we can prove some theorems when we have a measure on the body:
```coq
Lemma measured_while_completes {T} (measure : T → nat) v₀ test body
 : (∀ v, test v = true → measure (body v) < measure v)
   → test (while (measure v₀) v₀ test body) = false.
Corollary measured_while_def {T} (measure : T → nat) v test body
 : (∀ v, test v = true → measure (body v) < measure v)
   → while (measure v) v test body =
         if test v
         then let v' := body v in
              while (measure v') v' test body
         else v.
Theorem measured_while_measure_independent {T} (measure₁ measure₂ : T → nat) v₀ test body
 : (∀ v, test v = true → measure₁ (body v) < measure₁ v)
   → (∀ v, test v = true → measure₂ (body v) < measure₂ v)
   → while (measure₁ v₀) v₀ test body = while (measure₂ v₀) v₀ test body.
Theorem measured_while_ind
 : ∀ {T} (P : T → Prop) (measure : T → nat) v₀ test body,
    (∀ v, test v = true → measure (body v) < measure v)
    → P v₀
    → (∀ v, test v = true → P v → P (body v))
    → let retv := while (measure v₀) v₀ test body in
      test retv = true ∧ P retv.
```
Then we can define `for`-loops in terms of `while` loops:
```coq
Local Coercion Z.to_nat : ℤ ↣ ℕ.
for (int i = i₀; i < max; i += Δi) updating (v := v₀) {{ body }}
  := while (λ '(i, v).  max - i    ) (i₀, v₀) (λ '(i, v). i <? max) (λ '(i, v). (i + Δi, body))
for (int i = i₀; i ≤ max; i += Δi) updating (v := v₀) {{ body }}
  := while (λ '(i, v). (max - i).+1) (i₀, v₀) (λ '(i, v). i ≤? max) (λ '(i, v). (i + Δi, body))
for (int i = i₀; i > min; i -= Δi) updating (v := v₀) {{ body }}
  := while (λ '(i, v).  i - min    ) (i₀, v₀) (λ '(i, v). i >? min) (λ '(i, v). (i - Δi, body))
for (int i = i₀; i ≥ min; i -= Δi) updating (v := v₀) {{ body }}
  := while (λ '(i, v). (i - min).+1) (i₀, v₀) (λ '(i, v). i ≥? min) (λ '(i, v). (i - Δi, body))
```
As long as `Δi` is a `positive`, I think we can prove `(∀ v, test v = true → measure (body v) < measure v)` for all of these.

Thoughts on this proposal @andres-erbsen ?

**Comment by andres-erbsen** [comment]
I like where this is going. I am still thinking that it might make sense to make the `(∀ v, test v = true → measure (body v) < measure v)` proof an argument to while itself -- it seems that we never want one without the other.

**Comment by JasonGross** [comment]
I think that's a bad idea; then we will likely need to prove that the value is independent of the proof, and it will be impossible to use `setoid_rewrite` with the body of the while-loop, and we will likely have trouble denoting the reified loop (because we'll need to manifest a proof from nothing).

**Comment by andres-erbsen** [comment]
Okay, I'm convinced.

**Comment by andres-erbsen** [comment]
What if we wrote all loop definitions in continuation-passing style? I am not sure what we could make the syntax look like, but I think it would enable unrolling by partial evaluation, so it might make working with the invariants easier as well.

**Comment by andres-erbsen** [comment]
`Definition loop {T} (max_iter : ℕ) (initial : T) (body : T → forall R (continue:T->R) (break:T->R), R) : forall U (after : T -> U), U`?

**Comment by JasonGross** [comment]
I don't think unrolling via partial evaluation is particularly helpful.  Do you have a particular use-case where you think it would be helpful?

In any case, I think with the interface I proposed, you could get unrolling by partial evaluation (unless you mean getting rid of top-level `let`s?).

**Comment by andres-erbsen** [comment]
I played around with this and encountered an issue: `(max_iter : ℕ)` is often larger than 5000, which according `large-nat,numbers` tends to be the largest fully supported `nat` in Coq...

**Comment by JasonGross** [comment]
Possible solutions:
1. use a function `N -> nat` or `Z -> nat` (fine as long as we don't unroll the loop)
2. Hope that https://github.com/coq/coq/pull/496 gets merged into 8.7, and make use of its support for gigantic nats
3. Switch to `N`-based recursion

**Comment by andres-erbsen** [comment]
Almost done in 9b6d577171419a8478f6cb1649020e7237a962f7, just that the `()%for_test` notations now show up in places where they shouldn't.

**Comment by JasonGross** [comment]
You can fix that by defining things like
```
Definition for_test_lt := Z.ltb.
```
and making the notation be for that

**Comment by andres-erbsen** [comment]
Is there a way to have a notation scope that is bound to the particular location in the for loop, not printed elsewhere?

**Comment by JasonGross** [comment]
None that I know of.
