### ISSUE TITLE
Consider to replace Stdlib by Prevasives

### ISSUE THREAD

**Issue by armfazh** [mit-plv/fiat-crypto#1674]
When compiling using Ocaml v5.0.0, it does not recognize `Pervasives` library.

Workaround: Replace `Pervasives` by `Stdlib`.
See: https://stackoverflow.com/questions/64742628/unbound-module-stdlib

```sh
$ sed -i 's/Pervasives/Stdlib/g' src/ExtractionOCaml/*.ml
```

**Comment by JasonGross** [comment]
> `$ sed -i 's/Pervasives/Stdlib/g' src/ExtractionOCaml/*.ml`

This is not a great workaround, since all files are generated.
We should instead fix the issue at
https://github.com/mit-plv/fiat-crypto/blob/37dd5afc21a11fd476ba0822169c4892c00e408b/src/StandaloneOCamlMain.v#L80
