### ISSUE TITLE
Our [nsatz] is weaker than the standard library's [nsatz]

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#17]
Here is code that works:
```coq
Require Import Coq.Reals.Reals Coq.nsatz.Nsatz.

Local Open Scope R.

Goal forall a b yx xz : R,
  yx^2 = xz^3 + a * xz + b ->
  (- yx)^2 = xz^3 + a * xz + b ->
  xz * (2 * yx)^2 - ((3 * xz^2 + a)^2 - xz * (2 * yx)^2 - xz * (2 * yx)^2) = 0 ->
  (3 * xz^2 + a)^2 - 2 * (2 * yx)^2 * xz = (2 * yx)^2 * xz.
Proof.
  intros ???? H0 H1 H2.
  nsatz.
Qed.
```
And here is code that doesn't:
```coq
Require Import Crypto.Tactics.Nsatz Crypto.Algebra Crypto.Util.Notations.

Section F.
  Context {F Feq Fzero Fone Fopp Fadd Fsub Fmul Finv Fdiv}
          {field:@field F Feq Fzero Fone Fopp Fadd Fsub Fmul Finv Fdiv}.
  Local Infix "=" := Feq : type_scope. Local Notation "a <> b" := (not (a = b)) : type_scope.
  Local Infix "+" := Fadd. Local Infix "*" := Fmul.
  Local Infix "-" := Fsub. Local Infix "/" := Fdiv.
  Local Notation "- x" := (Fopp x).
  Local Notation "x ^ 2" := (x*x). Local Notation "x ^ 3" := (x*x^2).
  Local Notation "0" := Fzero.  Local Notation "1" := Fone.
  Notation "2" := (1+1). Notation "3" := (1+2).
  Local Open Scope core_scope.

  Goal forall a b yx xz : F,
    yx^2 = xz^3 + a * xz + b ->
    (- yx)^2 = xz^3 + a * xz + b ->
    xz * (2 * yx)^2 - ((3 * xz^2 + a)^2 - xz * (2 * yx)^2 - xz * (2 * yx)^2) = 0 ->
    (3 * xz^2 + a)^2 - 2 * (2 * yx)^2 * xz = (2 * yx)^2 * xz.
  Proof.
    intros ???? H0 H1 H2.
    nsatz. (* In nested Ltac calls to "nsatz", "nsatz", "nsatz_sugar_power" and "nsatz_domain_sugar_power", last
call failed.
Error: No applicable tactic.
computation without sugar
p: [9]*b^4 + [(-12)]*a^2*b + [6]*b^2*c + [1]*c^2 
lp:
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-9)]*b^4 + [12]*a^2*b + [(-6)]*b^2*c + [(-1)]*c^2 
remainder: [3]*a^2*b + [3]*b^2*c + [(-1)]*c^2 + [9]*b*d 
computation of the Groebner basis
[3,3]0[3,2]
new polynomial: [3]*a^2*b + [3]*b^2*c + [(-1)]*c^2 + [9]*b*d 
remainder: 0
polynomial reduced to 0
r ok
r: 0
verif sum: [9]*b^4 + [(-9)]*a^2*b + [9]*b^2*c + [9]*b*d 
coefficient: [(-1)] 
computed
time:      0.000s
cert ok
useless spolynomials: 0
useful spolynomials: 2
number of parametres: -1
term computed
term computed
computation without sugar
p: [81]*b^8 + [(-216)]*a^2*b^5 + [108]*b^6*c + [144]*a^4*b^2 + [(-144)]*a^2*b^3*c + [54]*b^4*c^2 + [(-24)]*a^2*b*c^2 + [12]*b^2*c^3 + [1]*c^4 
lp:
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-9)]*b^4 + [12]*a^2*b + [(-6)]*b^2*c + [(-1)]*c^2 
remainder: [(-9)]*a^4*b^2 + [(-18)]*a^2*b^3*c + [(-27)]*b^4*c^2 + [81]*b^5*d + [24]*a^2*b*c^2 + [(-12)]*b^2*c^3 + [(-135)]*a^2*b^2*d + [27]*b^3*c*d + [(-1)]*c^4 
computation of the Groebner basis
[3,3]0[3,2]
new polynomial: [3]*a^2*b + [3]*b^2*c + [(-1)]*c^2 + [9]*b*d 
remainder: [9]*a^4*c + [(-3)]*a^2*b*c^2 + [(-15)]*b^2*c^3 + [27]*a^2*b^2*d + [54]*b^3*c*d + [1]*c^4 + [(-9)]*a^2*c*d + [(-27)]*b*c^2*d + [81]*b^2*d^2 
[4,4]c[4,3]
new polynomial: [(-3)]*a^4 + [4]*b^2*c^2 + [(-9)]*b^3*d + [3]*a^2*d + [3]*b*c*d 
remainder: 0
polynomial reduced to 0
r ok
r: 0
verif sum: [81]*b^8 + [(-216)]*a^2*b^5 + [108]*b^6*c + [135]*a^4*b^2 + [(-153)]*a^2*b^3*c + [54]*b^4*c^2 + [(-9)]*a^4*c + [(-18)]*a^2*b*c^2 + [27]*b^2*c^3 + [(-54)]*a^2*b^2*d + [(-54)]*b^3*c*d + [9]*a^2*c*d + [27]*b*c^2*d + [(-81)]*b^2*d^2 
coefficient: [(-1)] 
computed
time:      0.000s
cert ok
useless spolynomials: 0
useful spolynomials: 3
number of parametres: -1
term computed
term computed
computation without sugar
p: [729]*b^12  + 16 terms
lp:
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-9)]*b^4 + [12]*a^2*b + [(-6)]*b^2*c + [(-1)]*c^2 
remainder: [(-27)]*a^8  + 17 terms
computation of the Groebner basis
[3,3]0[3,2]
new polynomial: [3]*a^2*b + [3]*b^2*c + [(-1)]*c^2 + [9]*b*d 
remainder: [(-27)]*a^8  + 17 terms
[4,4]c[4,3]
new polynomial: [(-3)]*a^4 + [4]*b^2*c^2 + [(-9)]*b^3*d + [3]*a^2*d + [3]*b*c*d 
remainder: 0
polynomial reduced to 0
r ok
r: 0
verif sum: [729]*b^12 + [(-2916)]*a^2*b^9 + [1458]*b^10*c + [3888]*a^4*b^6 + [(-3888)]*a^2*b^7*c + [1215]*b^8*c^2 + [(-1728)]*a^6*b^3 + [2592]*a^4*b^4*c + [(-1944)]*a^2*b^5*c^2 + [540]*b^6*c^3 + [27]*a^8 + [54]*a^6*b*c + [405]*a^4*b^2*c^2 + [(-477)]*a^2*b^3*c^3 + [135]*b^4*c^4 + [81]*a^4*b^3*d + [(-63)]*a^4*c^3 + [(-18)]*a^2*b*c^4 + [81]*b^2*c^5 + [135]*a^6*d + [243]*a^4*b*c*d + [(-486)]*a^2*b^2*c^2*d + [(-378)]*b^3*c^3*d + [486]*a^2*b^3*d^2 + [9]*a^2*c^3*d + [135]*b*c^4*d + [81]*a^4*d^2 + [(-1215)]*b^2*c^2*d^2 + [729]*b^3*d^3 + [54]*c^3*d^2 + [(-243)]*a^2*d^3 + [(-729)]*b*c*d^3 
coefficient: [(-1)] 
computed
time:      0.000s
cert ok
useless spolynomials: 0
useful spolynomials: 3
number of parametres: -1
term computed
term computed
computation without sugar
p: [6561]*b^16  + 25 terms
lp:
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-9)]*b^4 + [12]*a^2*b + [(-6)]*b^2*c + [(-1)]*c^2 
remainder: [81]*a^10*b  + 27 terms
computation of the Groebner basis
[3,3]0[3,2]
new polynomial: [3]*a^2*b + [3]*b^2*c + [(-1)]*c^2 + [9]*b*d 
remainder: [(-81)]*a^8*c^2  + 27 terms
[4,4]c[4,3]
new polynomial: [(-3)]*a^4 + [4]*b^2*c^2 + [(-9)]*b^3*d + [3]*a^2*d + [3]*b*c*d 
remainder: 0
polynomial reduced to 0
r ok
r: 0
verif sum: [(-6561)]*b^16 + [34992]*a^2*b^13 + [(-17496)]*b^14*c + [(-69984)]*a^4*b^10 + [69984]*a^2*b^11*c + [(-20412)]*b^12*c^2 + [62208]*a^6*b^7 + [(-93312)]*a^4*b^8*c + [58320]*a^2*b^9*c^2 + [(-13608)]*b^10*c^3 + [(-20736)]*a^8*b^4 + [41472]*a^6*b^5*c + [(-46656)]*a^4*b^6*c^2 + [25920]*a^2*b^7*c^3 + [(-5670)]*b^8*c^4 + [81]*a^10*b + [243]*a^8*b^2*c + [7074]*a^6*b^3*c^2 + [(-10368)]*a^4*b^4*c^3 + [6480]*a^2*b^5*c^4 + [(-1512)]*b^6*c^5 + [(-108)]*a^8*c^2 + [(-378)]*a^6*b*c^3 + [(-891)]*a^4*b^2*c^4 + [1053]*a^2*b^3*c^5 + [(-252)]*b^4*c^6 + [891]*a^8*b*d + [1620]*a^6*b^2*c*d + [243]*a^4*b^3*c^2*d + [297]*a^4*c^5 + [(-18)]*a^2*b*c^6 + [(-279)]*b^2*c^7 + [(-1593)]*a^6*c^2*d + [(-2025)]*a^4*b*c^3*d + [3078]*a^2*b^2*c^4*d + [2106]*b^3*c^5*d + [3402]*a^6*b*d^2 + [1458]*a^4*b^2*c*d^2 + [(-5832)]*a^2*b^3*c^2*d^2 + [135]*a^2*c^5*d + [(-711)]*b*c^6*d + [(-2673)]*a^4*c^2*d^2 + [324]*a^2*b*c^3*d^2 + [10773]*b^2*c^4*d^2 + [4374]*a^4*b*d^3 + [(-8748)]*a^2*b^2*c*d^3 + [(-15309)]*b^3*c^2*d^3 + [(-432)]*c^5*d^2 + [3645]*a^2*c^2*d^3 + [8991]*b*c^3*d^3 + [(-2187)]*a^2*b*d^4 + [(-15309)]*b^2*c*d^4 + [729]*c^2*d^4 + [(-6561)]*b*d^5 
coefficient: [1] 
computed
time:      0.001s
cert ok
useless spolynomials: 0
useful spolynomials: 3
number of parametres: -1
term computed
term computed
computation without sugar
p: [59049]*b^20  + 36 terms
lp:
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-1)]*b^3 + [1]*a^2 + [(-1)]*b*c + [(-1)]*d 
[(-9)]*b^4 + [12]*a^2*b + [(-6)]*b^2*c + [(-1)]*c^2 
remainder: [(-243)]*a^12*b^2  + 38 terms
computation of the Groebner basis
[3,3]0[3,2]
new polynomial: [3]*a^2*b + [3]*b^2*c + [(-1)]*c^2 + [9]*b*d 
remainder: [729]*a^12*c  + 39 terms
[4,4]c[4,3]
new polynomial: [(-3)]*a^4 + [4]*b^2*c^2 + [(-9)]*b^3*d + [3]*a^2*d + [3]*b*c*d 
remainder: 0
polynomial reduced to 0
r ok
r: 0
verif sum: [59049]*b^20 + [(-393660)]*a^2*b^17 + [196830]*b^18*c + [1049760]*a^4*b^14 + [(-1049760)]*a^2*b^15*c + [295245]*b^16*c^2 + [(-1399680)]*a^6*b^11 + [2099520]*a^4*b^12*c + [(-1224720)]*a^2*b^13*c^2 + [262440]*b^14*c^3 + [933120]*a^8*b^8 + [(-1866240)]*a^6*b^9*c + [1749600]*a^4*b^10*c^2 + [(-816480)]*a^2*b^11*c^3 + [153090]*b^12*c^4 + [(-248832)]*a^10*b^5 + [622080]*a^8*b^6*c + [(-933120)]*a^6*b^7*c^2 + [777600]*a^4*b^8*c^3 + [(-340200)]*a^2*b^9*c^4 + [61236]*b^10*c^5 + [243]*a^12*b^2 + [243]*a^10*b^3*c + [103680]*a^8*b^4*c^2 + [(-207360)]*a^6*b^5*c^3 + [194400]*a^4*b^6*c^4 + [(-90720)]*a^2*b^7*c^5 + [17010]*b^8*c^6 + [729]*a^12*c + [81]*a^10*b*c^2 + [(-2430)]*a^8*b^2*c^3 + [(-18900)]*a^6*b^3*c^4 + [25920]*a^4*b^4*c^5 + [(-15120)]*a^2*b^5*c^6 + [3240]*b^6*c^7 + [3402]*a^10*b^2*d + [4860]*a^8*b^3*c*d + [(-135)]*a^8*c^4 + [1998]*a^6*b*c^5 + [2241]*a^4*b^2*c^6 + [(-2205)]*a^2*b^3*c^7 + [405]*b^4*c^8 + [4131]*a^10*c*d + [(-5670)]*a^8*b*c^2*d + [(-22680)]*a^6*b^2*c^3*d + [(-7047)]*a^4*b^3*c^4*d + [18225]*a^8*b^2*d^2 + [24786]*a^6*b^3*c*d^2 + [(-1251)]*a^4*c^7 + [198]*a^2*b*c^8 + [1053]*b^2*c^9 + [10827]*a^6*c^4*d + [12879]*a^4*b*c^5*d + [(-16902)]*a^2*b^2*c^6*d + [(-10746)]*b^3*c^7*d + [(-486)]*a^8*c*d^2 + [(-48114)]*a^6*b*c^2*d^2 + [(-34020)]*a^4*b^2*c^3*d^2 + [46170]*a^2*b^3*c^4*d^2 + [43740]*a^6*b^2*d^3 + [26244]*a^4*b^3*c*d^3 + [(-1287)]*a^2*c^7*d + [3591]*b*c^8*d + [31833]*a^4*c^4*d^2 + [(-4536)]*a^2*b*c^5*d^2 + [(-76059)]*b^2*c^6*d^2 + [(-30618)]*a^6*c*d^3 + [(-104976)]*a^4*b*c^2*d^3 + [145800]*a^2*b^2*c^3*d^3 + [169857]*b^3*c^4*d^3 + [32805]*a^4*b^2*d^4 + [(-85293)]*a^2*b^3*c*d^4 + [2538]*c^7*d^2 + [(-26487)]*a^2*c^4*d^3 + [(-79461)]*b*c^5*d^3 + [(-19683)]*a^4*c*d^4 + [24057]*a^2*b*c^2*d^4 + [328050]*b^2*c^3*d^4 + [(-39366)]*a^2*b^2*d^5 + [(-157464)]*b^3*c*d^5 + [(-16038)]*c^4*d^4 + [45927]*a^2*c*d^5 + [196830]*b*c^2*d^5 + [(-59049)]*b^2*d^6 
coefficient: [(-1)] 
computed
time:      0.001s
cert ok
useless spolynomials: 0
useful spolynomials: 3
number of parametres: -1
term computed
term computed
 *)
  Qed.
End F.
```

This seems somehow related to the fact that we have duplicate information in the hypotheses.

**Comment by andres-erbsen** [comment]
The standard library nsatz gives special treatment to `Coq.Reals.Reals`. Here is a file that does NOT solve the goal:

	Require Import Coq.QArith.Qfield Coq.nsatz.Nsatz Algebra_syntax.
	
	Local Notation "2" := (2#1).
	Local Notation "3" := (3#1).
	Local Notation "x ^ 2" := (x*x) (at level 30).
	Local Notation "x ^ 3" := (x*x*x) (at level 30).
	
	Goal forall a b yx xz : Q,
	  yx^2 == xz^3 + a * xz + b ->
	  (- yx)^2 == xz^3 + a * xz + b ->
	  xz * (2 * yx)^2 - ((3 * xz^2 + a)^2 - xz * (2 * yx)^2 - xz * (2 * yx)^2) == 0 ->
	  (3 * xz^2 + a)^2 - 2 * (2 * yx)^2 * xz == (2 * yx)^2 * xz.
	Proof.
	  intros ???? H0 H1 H2.
	  nsatz; cbv -[Qmult Qplus Qopp Qeq] in *.
	Qed.

The output is "polynomial not in ideal".

**Comment by andres-erbsen** [comment]
The failure of our nsatz is due to a disagreement between `nsatz_compute` and reflective `check`: https://gist.github.com/andres-erbsen/d1ac706ec4ef692e341517feb9d87fda

**Comment by andres-erbsen** [comment]
If I inlined tactics correctly, the failure of standard library nsatz is detected inside nsatz_compute: https://gist.github.com/andres-erbsen/432653913834aa559676a420243d6e29. This is hidden from the outside interface by `match` backtracking and nsatz's own retry mechanism.

**Comment by andres-erbsen** [comment]
In these examples, the standard library `nsatz` calls `nsatz_compute` with arguments that denote to

     0
       :: 0
          :: ((3 * (xz * xz) + a) * (3 * (xz * xz) + a) + - (2 * (2 * yx * (2 * yx)) * xz) +
              - (2 * yx * (2 * yx) * xz)) *
             (((3 * (xz * xz) + a) * (3 * (xz * xz) + a) + - (2 * (2 * yx * (2 * yx)) * xz) +
               - (2 * yx * (2 * yx) * xz)) *
              ((3 * (xz * xz) + a) * (3 * (xz * xz) + a) + - (2 * (2 * yx * (2 * yx)) * xz) +
               - (2 * yx * (2 * yx) * xz)) *
              (((3 * (xz * xz) + a) * (3 * (xz * xz) + a) + - (2 * (2 * yx * (2 * yx)) * xz) +
                - (2 * yx * (2 * yx) * xz)) *
               ((3 * (xz * xz) + a) * (3 * (xz * xz) + a) + - (2 * (2 * yx * (2 * yx)) * xz) +
                - (2 * yx * (2 * yx) * xz))))
             :: xz * (2 * yx * (2 * yx)) +
                -
                ((3 * (xz * xz) + a) * (3 * (xz * xz) + a) + - (xz * (2 * yx * (2 * yx))) +
                 - (xz * (2 * yx * (2 * yx)))) + - 0
                :: - yx * - yx + - (xz * xz * xz + a * xz + b)
                   :: yx * yx + - (xz * xz * xz + a * xz + b) :: nil
     : list Q

Our nsatz calls nsatz_compute with arguments that denote to

     (0
        :: - (1)
           :: ((3 * xz^2 + a)^2 - 2 * (2 * yx)^2 * xz - (2 * yx)^2 * xz) *
              (((3 * xz^2 + a)^2 - 2 * (2 * yx)^2 * xz - (2 * yx)^2 * xz)^2)^2
              :: xz * (2 * yx)^2 - ((3 * xz^2 + a)^2 - xz * (2 * yx)^2 - xz * (2 * yx)^2)
                 :: (- yx)^2 - (xz^3 + a * xz + b) :: yx^2 - (xz^3 + a * xz + b) :: nil)%list
     : list F

(and the `(-1)` replaced with `0` gives the same behavior).

**Comment by andres-erbsen** [comment]
Sage thinks these argument lists are equivalent.

**Comment by andres-erbsen** [comment]
If I take the input that our `nsatz` gives to `nsatz_compute` and give it to Sage, Sage thinks that 
    sage: R.<a,b,yx,xz> = PolynomialRing(QQ,4,order='invlex')
    sage: (((3 * xz^2 + a)^2 - 2 * (2 * yx)^2 * xz - (2 * yx)^2 * xz) * (((3 * xz^2 + a)^2 - 2 * (2 * yx)^2 * xz - (2 * yx)^2 * xz)^2)^2) in R.ideal([xz * (2 * yx)^2 - ((3 * xz^2 + a)^2 - xz * (2 * yx)^2 - xz * (2 * yx)^2), (- yx)^2 - (xz^3 + a * xz + b), yx^2 - (xz^3 + a * xz + b)])
    # True

**Comment by andres-erbsen** [comment]
Standard library `nsatz` on `Coq.Reals.Reals` does not recognize `^` as opaque and thus uses the following list of variables: `yx ^ 2 :: xz ^ 3  :: a :: xz :: b :: (- yx) ^ 2 :: (2 * yx) ^ 2 :: (3 * xz ^ 2 + a) ^ 2`, which enables it to succeed: https://gist.github.com/andres-erbsen/ba351881bb42d101b84b30cda06f56d6. When `^2` and `^3` defined as notations for simple multiplication, standard library nsatz fails the same way as our nsatz -- `nsatz_compute` generates an invalid certificate: https://gist.github.com/andres-erbsen/d25133e021ffb0b7b4b11134a6c5e278

**Comment by JasonGross** [comment]
Perhaps I should have mentioned that if you clear either of the first two hypotheses, `nsatz` works fine.

Can you tell what's invalid about the certificate?  And thanks for tracking this down!  (Once you reach a good stopping point, or a complete understanding, want to report a Coq bug?  (`nsatz` is supposed to be complete, and it's not, in a way that's hard to deal with ahead of time)

**Comment by andres-erbsen** [comment]
I am not familiar with the certificate format. I will file a Coq bug the next time I work on this.

**Comment by andres-erbsen** [comment]
Here is a smaller example that results in a bad certificate in 8.5pl1 and is non-trivial to work around:

    Require Import Coq.Reals.Reals Coq.nsatz.Nsatz.
    Local Open Scope R.
    
    Goal forall x y : R,
      x*x =  y *  y ->
      x*x = -y * -y ->
      x*(x*x) = 0 -> (* The associativity does not actually matter, *)
      (x*x)*x = 0.   (* just otherwise [assumption] would solve the goal. *)
    Proof.
      nsatz. (* "invalid nsatz certificate" *)
      cbv -[PolZeq ]. (* these polynomials indeed not equal *)
      cbv. (* [false = true] *)
      reflexivity. (* fails *)
    Qed.

I'm currently locked out of the coq bug tracker sign-up system because I made a typo, will try to register again in an hour.

**Comment by andres-erbsen** [comment]
For future reference:
Author of latest commit on nsatz's `ideal.ml`: https://www-sop.inria.fr/lemme/Loic.Pottier/
A link from his website even has user-level documentation!: https://docs.google.com/document/d/1qRcQ5-UK5OusDz97m9nHGGyV-KnQh_af6GwMBjQO0Mw/edit?hl=fr
A paper that covers `nsatz`: https://www-sop.inria.fr/marelle/personnel/Loic.Pottier/pottier.pdf

**Comment by andres-erbsen** [comment]
The [nsatz] bug is tracked at https://coq.inria.fr/bugs/show_bug.cgi?id=4880. I am closing this issue since its name is confusing; another issue may be warranted for figuring out how to work around the said bug.
