### ISSUE TITLE
Compiler optimization : add with carry

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#171]
@JasonGross Here's the longer-form example I promised you.

Suppose we are adding `[a0, a1, a2]` to `[b0, b1, b2]`. We have an operation `ADD` of
type `Z -> Z -> Z * Z` and an operation `ADC` of type `Z -> Z -> Z -> Z * Z`. The
code produced initially (by the basesystem side of things) will be equivalent to:

```
s0, c0 := ADD a0 b0
s1', c1' := ADD c0 a1
s1, c1'' := ADD s1' b1
c1 := c1' + c1''
s2', c2' := ADD c1 a2
s2, c2'' := ADD s2' b2
c2 := c2' + c2''
...
```

The compiler optimization should convert this to:

```
s0, c0 := ADD a0 b0
s1, c1 := ADC c0 a1 b1
s2, c2 := ADC c1 a1 b2
...
```

Referencing Jason's earlier objection in the meeting today--It's okay to use one carry instead of
two because the bounds work out. For example, in the first code snippet, it is
not possible that c1' and c1'' are both 1; since a1 and b1 are both < 2^n ,
their sum must be < 2^{n+1} - 1.  Therefore, even when c0 is added in, the sum
is < 2^{n+1} and the carry c1 must be 1 or 0.

For reference, the exact Gallina form of the initial code will be

```
let sum_carry0 := add_get_carry a0 b0 in
let carry0 := snd sum_carry0 in
let sum_carry1 := add_get_carry c0 a1 in
let carry1 := snd sum_carry1 in
let sum_carry2 := add_get_carry (fst sum_carry1) b1 in
let carry2 := carry1 + snd sum_carry2 in
let sum_carry3 := add_get_carry carry2 a2 in
let carry3 := snd sum_carry3 in
let sum_carry4 := add_get_carry carry3 b2 in
let carry4 := carry3 + snd sum_carry4 in
...
```

**Comment by JasonGross** [comment]
Ewww, this is horrendous.  I don't currently support rewriting let-expressions, so I'll need to make a dedicated pass for this particular optimization.  It'll be a pass that is hard-coded to exactly this pattern (up to syntactic equality; no inlining of lets or anything), or whatever pattern actually shows up in the reified form of freeze at the appropriate location.  This also needs to come after bounds analysis, right?

**Comment by JasonGross** [comment]
Turns out it doesn't need to come after bounds analysis.

**Comment by JasonGross** [comment]
Design question (for @jadephilipoom and/or @andres-erbsen ):  Do we
1. Transform from
```
s0, c0 := ADD a0 b0
s1', c1' := ADD c0 a1
s1, c1'' := ADD s1' b1
c1 := c1' + c1''
...
```
to
```
s0, c0 := ADD a0 b0
s1', c1' := ADD c0 a1
_, c1'' := ADD s1' b1
s1, c1 := ADC c0 a1 b1
...
```
and then do a dead-code-elimination pass after that (DCE is already mostly written, it just needs a bit of cleanup, and some helper lemmas to tie it to PHOAS, because it works with the named representation); or
2. Pass to the named representation, transform from
```
s0, c0 := ADD a0 b0
s1', c1' := ADD c0 a1
s1, c1'' := ADD s1' b1
c1 := c1' + c1''
...
```
to
```
s0, c0 := ADD a0 b0
s1', c1' := ADD c0 a1
_, c1'' := ADD s1' b1
s1, c1 := ADC c0 a1 b1
...
```
, do dead code elimination, then transform back to PHOAS?

I'm leaning towards the first one...

**Comment by JasonGross** [comment]
Oh, nevermind, the first one is impossible; this isn't a valid PHOAS transformation because it contains nonlinear occurrences. >.<

**Comment by JasonGross** [comment]
I have the transformation [here](https://github.com/JasonGross/fiat-crypto/blob/wip-add-cary-optimization/src/Compilers/Z/Named/RewriteAddToAdc.v#L41-L54):
```coq
  Definition do_rewrite
             (rewrite_exprf : forall t (e : exprf t), exprf t)
             {t} (e : exprf t)
    : exprf t
    := match e in Named.exprf _ _ _ t return exprf t with
       | (nlet (a2, c1)       : tZ * tZ := (ADD bw1 c0 a as ex0) in P0)
         => (nlet (a2, c1)    : tZ * tZ := rewrite_exprf _ ex0 in
             match P0 in Named.exprf _ _ _ t return exprf t -> exprf t with
             | (nlet (s , c2) : tZ * tZ := (ADD bw2 a2' b as ex1) in P1)
               => match P1 in Named.exprf _ _ _ t return exprf t -> exprf t with
                  | (nlet c   : tZ      := (ADX c1' c2' as ex2) in P)
                    => fun e
                       => if (((bw1 =Z? bw2) && (a2 =n? a2') && (c1 =n? c1') && (c2 =n? c2'))
                                && negb (name_list_has_duplicate (a2::c1::c0::a::s::c2::b::c::nil)%list))
                          then (nlet (s , c2) : tZ * tZ := ex1 in
                                nlet c        : tZ      := ex2 in
                                nlet (s, c)   : tZ * tZ := ADC bw1 (Var c0) a b in
                                rewrite_exprf _ P)
                          else e
                  | P1' => fun e => e
                  end
             | P0' => fun e => e
             end (rewrite_exprf _ P0))
       | TT => TT
       | Var _ n => Var n
       | Op _ _ opc args
         => Op opc (rewrite_exprf _ args)
       | (nlet nx := ex in eC)
         => (nlet nx := rewrite_exprf _ ex in rewrite_exprf _ eC)
       | Pair tx ex ty ey
         => Pair (rewrite_exprf tx ex) (rewrite_exprf ty ey)
       end%core%nexpr%bool.
```
It's currently unproven, untested, and I haven't yet added the boilerplate to get it to work with PHOAS.

**Comment by jadephilipoom** [comment]
Looks good from a preliminary scan. If you can get it to a stage where I can test it, that'd be great. (If you prefer, I could make you the test case.)

**Comment by JasonGross** [comment]
I'll try to have such a version that you can test by Thursday (hopefully sooner, but not sure how much time I also plan to spend some time on fiat-parsers).

**Comment by JasonGross** [comment]
@jadephilipoom I think you lied to me :-P  The code
```coq
let sum_carry3 := add_get_carry carry2 a2 in
let carry3 := snd sum_carry3 in
let sum_carry4 := add_get_carry carry3 b2 in
```
is not the same as
```
s2', c2' := ADD c1 a2
s2, c2'' := ADD s2' b2
```

Also, the code in freeze is neither, and instead seems to be closer to
```
s2', c2' := ADD c1 a2
s2, c2'' := ADD b2 s2'
```

**Comment by JasonGross** [comment]
Actually, the code in freeze seems to be
```
s2', c2' := ADD a2 b2
s2, c2'' := ADD c1 s2'
```
Can I rely on it always being like this?

**Comment by JasonGross** [comment]
@jadephilipoom It's in a state where you can probably start playing around with it: https://github.com/JasonGross/fiat-crypto/blob/wip-add-cary-optimization/src/Specific/IntegrationTestFreezeDisplay.log

If you have something better than `freeze` for me to work on, can you create an example file that's like `IntegrationTestFreeze.v`?

**Comment by JasonGross** [comment]
The currently generated code is:
```
λ x : word64 * word64 * word64 * word64 * word64,
Interp-η
(λ var : Syntax.base_type → Type,
 λ '(x7, x8, x6, x4, x2)%core,
 uint64_t x10, ℤ x11 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (0x0, Return x2, Const (-2251799813685229));
 uint64_t x13, ℤ x14 = Op (Syntax.AddWithGetCarry 51 Syntax.TZ (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (Return x11, Return x4, Const (-2251799813685247));
 uint64_t x16, ℤ x17 = Op (Syntax.AddWithGetCarry 51 Syntax.TZ (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (Return x14, Return x6, Const (-2251799813685247));
 uint64_t x19, ℤ x20 = Op (Syntax.AddWithGetCarry 51 Syntax.TZ (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (Return x17, Return x8, Const (-2251799813685247));
 uint64_t x22, ℤ x23 = Op (Syntax.AddWithGetCarry 51 Syntax.TZ (Syntax.TWord 6) Syntax.TZ (Syntax.TWord 6) Syntax.TZ) (Return x20, Return x7, Const (-2251799813685247));
 uint64_t x24 = x23 == 0 ? 0x0 : 0xffffffffffffffffL;
 uint64_t x25 = x24 & 0x7ffffffffffed;
 uint64_t x27, uint64_t x28 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, Return x10, Return x25);
 uint64_t x29 = x24 & 0x7ffffffffffff;
 uint64_t x31, uint64_t x32 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (Return x28, Return x13, Return x29);
 uint64_t x33 = x24 & 0x7ffffffffffff;
 uint64_t x35, uint64_t x36 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (Return x32, Return x16, Return x33);
 uint64_t x37 = x24 & 0x7ffffffffffff;
 uint64_t x39, uint64_t x40 = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (Return x36, Return x19, Return x37);
 uint64_t x41 = x24 & 0x7ffffffffffff;
 uint64_t x43, uint64_t _ = Op (Syntax.AddWithGetCarry 51 (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (Return x40, Return x22, Return x41);
 (Return x43, Return x39, Return x35, Return x31, Return x27))
x
     : word64 * word64 * word64 * word64 * word64 → ReturnType (uint64_t * uint64_t * uint64_t * uint64_t * uint64_t)
```

**Comment by jadephilipoom** [comment]
You can rely on the argument order being the same. Sorry I switched it around; if you care it's pretty trivial to change. But it looks like you did fine anyway.

Regarding the question of how to deal with the 51-bit version of add with carry--since the 51-bit version does not correspond to any real-world instruction, this particular piece of code would be represented with ands and bitshifts. However, we do want to have the capability to use add with carry when we're using a 64- or 32- bit system, and the principle is the same. I didn't have a handy example with 64- or 32- bits, but word by word Montgomery will use it.

**Comment by JasonGross** [comment]
I'm having a great deal of trouble proving this transformation correct... most of my trouble comes from the lack of a good pattern language to write the transformation in.  Trying to recreate the particular set of dependent pattern matches via ad-hoc tactics is quite daunting, and trying to prove the goal by manually following the structure of the definition (with an explicit `refine`) is ... incredibly frustrating (the first of the three `match` statements leaves me with 71(!) subgoals, approximately 66 of which are ill-typed(!)).  Not sure where to go from here...
