### ISSUE TITLE
Add reflective notations for add-get-carry

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#173]
This is mostly a note to myself and a convenient place to store a picture of what the notations should be.

![2017-05-12 11 19 37](https://cloud.githubusercontent.com/assets/396076/26027373/f7fb2aa0-37da-11e7-8886-d0a605706584.jpg)

**Comment by andres-erbsen** [comment]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=adcx&expand=140,139 : `_addcarryx_u32`, `_addcarryx_u64` for add-with-get-carry and hope that the compiler notices how we use these.

**Comment by JasonGross** [comment]
Do you mean `_addcarry_u32` and `_addcarry_u64`?  (The `x` versions are for add-with-carry, not add-with-get-carry, right?)

**Comment by JasonGross** [comment]
Oh, hrm, maybe not.  I guess the difference is "carry or overflow flag" vs "carry flag", so we want the `x` versions?  Even though `_addcarryx` is not the same as `adcx`...
