### ISSUE TITLE
Optimize scaling of partial products in field mul

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#176]
As said in https://github.com/mit-plv/fiat-crypto/issues/158#issuecomment-301316153.

It is faster to do `(19*a)*b` than `19*(a*b)` because `a*b` is double-width. In the case of 2^255-19, we essentially want the inverse of the first diff in https://gist.github.com/andres-erbsen/6ccc7261d97e2e95281384c7610eb675. For every concrete implementation of multiplication, the equivalence is true by `ring` (https://gist.github.com/andres-erbsen/23befc52a1f5cc7ae355d5d875cdff6e). Unfortunately, I haven't yet figured out how to get our templates or compiler optimizations to produce the more desirable version. Perhaps we should do this step manually for each field?

**Comment by JasonGross** [comment]
We can over-approximate this by saying that for constants `c` smaller than some cutoff (64?), we should replace `c * (a * b)` with `(c * a) * b`, and replace `c * (a + b)` with `(c * a + c * b)`?  We may have to iterate the simplifier to get the second rule to be applied enough times for the first rule to be applied in most cases.  Is this sufficient?  Is this too much?

**Comment by andres-erbsen** [comment]
Uh, this is also done to pull out two different factors... https://github.com/floodyberry/supercop/blob/master/crypto_scalarmult/curve25519/ref10/fe_mul.c#L58
 I don't think the over-approximation you proposed would work there (our code has `38*`).

If we wanted to integrate a manual prime-specific optimization as the one I show above, how would we do it? How hard would it be? I can think of either changing the last step of the derivation of `fmul` before reification or adding a compiler optimization that substitutes the faster version for the slower version a la icc matrix multiplication.

**Comment by jadephilipoom** [comment]
Before arithmetic simplification, our code actually has `19 * 2 *`, if that makes things any easier.

**Comment by andres-erbsen** [comment]
@jadephilipoom , is there a place in field arithmetic synthesis where we could do `transitivity (...); try ring; []` with handwritten code for multiplication?

**Comment by jadephilipoom** [comment]
Yes, but there would be let binders in there.

**Comment by JasonGross** [comment]
> How hard would it be? ... adding a compiler optimization

See https://github.com/mit-plv/fiat-crypto/issues/171#issuecomment-301325910 for how hard it is to add a 3-line -> 4-line optimization.  Note that you have to leave all of the old binders in place, just in case they're (re)used, and perform dead-code-elimination as a separate step.

**Comment by andres-erbsen** [comment]
Until a proposal for how to do this systematically comes up, we will be doing it manually for every field.
