### ISSUE TITLE
Chasing curve25519-donna performance

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#180]
With evaluation order of `fmul` and `fsquare` mimicking `curve25519-donna`, the code printed from fiat-crypto is still 10% slower. I disassembled the inner loops (donna: https://gist.github.com/andres-erbsen/fbdc25abd4a9a78d3c5954384740ebab, fiat: https://gist.github.com/andres-erbsen/6d659e58f0daf41c5ae4894cde545a2c) and counted instructions in them:

            donna   fiat  hand-drawn comparison
    mov*      672    849  ++++++++++++
    add       228    234  ++
    mul*      190    198  ++
    adc       180    180 
    lea       107    105  -
    and        89     91  +
    xor        60     60 
    shrd       59     50  --
    shr        50     49  -
    movabs     24     27  +
    sub        20     20 
    movzbl      3      3 
    jne         2      2 
    subq        1      1 
    subl        1      1 
    shlb        1      1 
    nopl        1      1 
    neg         1      1 
    movl        1      1 
    jmp         1      1 
    cmp         1      1 

I `mul` counts differ some because gcc chooses to multiply by 19 using a low-hamming-weight `lea` technique in donna but not in fiat, and possibly for some other reason as well. The rest of the difference is just moving data around, no useful computation. We may or may not choose to do anything about this.

**Comment by andres-erbsen** [comment]
Ordering the ladderstep field operations as in donna gives

            donna   fiat   hand-drawn comparison
    mov*      672    789   ++++++++++
    add       228    231   ++
    mul*      190    198   ++
    adc       180    180 
    lea       107    112   ++
    and        89     91   +
    xor        60     60 
    shrd       59     50   --
    shr        50     49   -
    movabs     24     28   +
    sub        20     20 
    movzbl      3      3 
    jne         2      2 
    subq        1      1 
    subl        1      1 
    shlb        1      1 
    nopl        1      1 
    neg         1      1 
    movl        1      1 
    jmp         1      1 
    cmp         1      1

**Comment by andres-erbsen** [comment]
Using current master and s/bool/uint64_t/, we get the following cycle counts:

    fiat51.c:    177224
    donna_c64.c: 164696 (-7%)

Breakdown, using a slightly tighter definition of the inner loop than before:

    instr   donna    fiat
              135     199
    mov       635     709
    add       229     231
    mulx      190     190
    adc       180     180
    lea       105     113
    and        89      91
    xor        60      60
    shr        59      50
    shrd       50      49
    movabs     24      29
    sub        20      20
    movq        0      12
    movzbl      2       2
    subl        1       1
    shlb        1       1
    neg         1       1
    jne         1       1

**Comment by andres-erbsen** [comment]
Maybe we should try printing `let x := y` as `int x[1] = {y}` and `Var x` as `x[0]` in hope that it persuades the compiler towards better register allocation. I normally would say this cannot matter, but eh, we are down to silly things here and donna has arrays in places where we use variables.

**Comment by JasonGross** [comment]
Do you want me to make a branch that does this?  (Time Estimate: 15-45 minutes.)

**Comment by andres-erbsen** [comment]
Sure, but I see no reason to hurry with it.

**Comment by JasonGross** [comment]
Oof, I tried to do this and got the fun
```coq
Anomaly:
No printing rule found for _ _ [1] = { _ } ; return ( _ , _ , .. , _ ).
Please report at http://coq.inria.fr/bugs/.
```

**Comment by andres-erbsen** [comment]
I don't feel like doing this anymore... if somebody else does, new issue
