### ISSUE TITLE
Karatsuba test case for bounds analysis

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#182]
To work on the bounds analysis procedure we discussed, I'd like the following:
- A file, say, `src/Specific/IntegrationTestKaratsuba.v`, like `src/Specific/IntegrationTestMul.v`, which uses the karatsuba algorithm in something-or-other, and compiles up to the `(* jgross start here *)` comment
- The code that shows up at `(* jgross start here *)` should use an identifier like `id_with_alt_bounds_and_proof` defined as
```coq
Definition id_with_alt_bounds {A} (value : A) (value_for_alt_bounds : A) : A
  := value.
Definition id_with_alt_bounds_and_proof {A} (value : A) (value_for_alt_bounds : A)
       {pf : value = value_for_alt_bounds}
:= id_with_alt_bounds value value_for_alt_bounds.
```
- If you `unfold id_with_alt_bounds_and_proof, id_with_alt_bounds`, then the rest of the file should go through, and should produce reified code that uses `Z` or `TWord 256` or whatever.

I'll then work on making bounds analysis handle either `id_with_alt_bounds` or `id_with_alt_bounds_and_proof` (not sure which, yet, so I figured I'd stick on the safe side and ask for the one with the proof), using `value_for_alt_bounds` rather than `value` for computing bounds.  Does this sound good to you @jadephilipoom?

**Comment by jadephilipoom** [comment]
Okay, I did some exploration on this and came to the following conclusions:

1. It's definitely doable. I reduced it to a list of admits in `src/Arithmetic/Karatsuba.v` that I'm fairly confident in.
2. It's going to take work. Because this hack means we have to prove *literal* equality of basesystem numbers, not equality of their eventual values, it breaks abstraction barriers, and we have to prove a bunch of stuff to push it through. The list of admits is quite long.

Based on this, I think we should table Karatsuba and focus on Montgomery. I am optimistic about this strategy working out, but not quickly or easily.

**Comment by JasonGross** [comment]
How much work will it take to get an example with a bunch of admits?  The reflective machinery could be done independently of proving the admits.  (Though it may make sense to hold off until after the POPL deadline or whatever we're targeting.)

**Comment by jadephilipoom** [comment]
I could spend another couple of hours getting it to the example stage--I did manage to get up to the first stage of synthesis (e.g. ArithmeticSynthesisTest level), but haven't made the IntegrationTest-style step. However, I think we've spent well over enough time on this for now, and without proving those admits it's not much of an accomplishment to chase.

**Comment by JasonGross** [comment]
@jadephilipoom I've mostly finished the reflective automation for this (I'll be pushing momentarily).  There's an issue: the bounds are not tight enough; I'm left with this impossible goal:
```coq
  ((r[0 ~> 72057594037927935] <=? r[0 ~> 81064793292668928])%zrange &&
   (r[0 ~> 72057594037927935] <=? r[0 ~> 81064793292668928])%zrange &&
   (r[0 ~> 72057594037927935] <=? r[0 ~> 81064793292668928])%zrange &&
   (r[0 ~> 102363547501837588311535505879802992345435751778060049012811372691468] <=? r[0 ~> 81064793292668928])%zrange &&
   (r[0 ~> 72057594037927935] <=? r[0 ~> 81064793292668928])%zrange &&
   (r[0 ~> 19714502134749424271321677013450763] <=? r[0 ~> 81064793292668928])%zrange &&
   (r[0 ~> 72057594037927935] <=? r[0 ~> 81064793292668928])%zrange &&
   (r[0 ~> 72057594037927935] <=? r[0 ~> 81064793292668928])%zrange)%bool = true
```
In fact, none of the id-with-alt bounds land in anything other than `Z`.  For example, here is the first failure of tightness:
```coq
   λ '(H6, x9, x8, x7, x6, x5, x4, x3, (H13, x16, x15, x14, x13, x12, x11, x10))%core,
   uint64_t x17 = Op (Syntax.IdWithAlt (Syntax.TWord 6) (Syntax.TWord 6) (Syntax.TWord 6)) (0x0, 0x0);
   ℤ x18 = Op (Syntax.IdWithAlt Syntax.TZ Syntax.TZ Syntax.TZ)
             ((uint128_t) x6 * x13 + (uint128_t) H6 * H13 +
              ((uint128_t) x6 + H6 * (x13 + H13) - (uint128_t) x6 * x13) *
              Const 26959946667150639794667015087019630673637144422540572481103610249216,
             (uint128_t) x6 * x13 + (uint128_t) H6 * H13 +
             ((uint128_t) x6 * H13 + (uint128_t) H6 * x13 + (uint128_t) H6 * H13) *
             Const 26959946667150639794667015087019630673637144422540572481103610249216);
```

**Comment by JasonGross** [comment]
@jadephilipoom Why are you multiplying by 2^225?

**Comment by jadephilipoom** [comment]
Figured out what I did wrong. It's correct to multiply by `2^224`, but I implemented it as a scalar multiplication rather than a basesystem multiplication.

More detail --the general formula for goldilocks multiplication is this:

Given:
       `s^2 mod p = (s + 1) mod p`
        `x = x0 + s * x1`
        `y = y0 + s * y1`

We can compute `(x  * y) mod p` by doing:

```
z0 = x0 * y0
z2 = x2 * y2
sum_z = z0 + z2
sum_x = x0 + x1
sum_y = y0 + y1
mul_sumxy = sum_x * sum_y
z1 = mul_sumxy - z0
sz1 = s * z1
xy = sum_z - sz1
```

In this formulation, `s=2^224`. The multiplication `s * z1` is currently using `scmul` when it should be using `mul`.

**Comment by JasonGross** [comment]
Great!  If you can fix this, I bet Karatsuba mul will almost just go through, and the only thing I'll have to do is fix up the display a bit.  (Okay, actually, I'll need to do a bit more than that, and figure out the right way to strip out `IdWithAlt` at the end, whether it's by notation, or by matching on the outermost operation and changing its return type.  I also worry a bit that the IdWithAlt location is not precise enough, at least if we ever want A-normal form; you need to catch it at the first place that it overflows or underflows, i.e., without the extra constant multiplication.)

**Comment by jadephilipoom** [comment]
Figuring out the numbers of limbs everything needs to have now is being a pain with this new multiplication. So far I've got the following limb sizes (where `n2 = 2 * n`):

```
    x y : n2
    x0 x1 y0 y1 : n
    s : S n
    z0 z1 : pred n2
    sum_z : n2
    sum_x sum_y : S n
    mul_sumxy : S n2
    z1 : S n2
    sz1 : S n + S n2 - 1 = S (n + n2)
    xy : S (n + n2) (??? - should be n2)
```

Basically, not sure what exactly we do with the huge size of `sz1`; presumably we wrap the last `n` terms around to the beginning. I'm having trouble deciphering where that happens from the p448 code, though. @andres-erbsen, if you have free time and want to take a look at it and point me to where this happens, that'd be cool. Otherwise I'll just allocate some time to sit down with a pen and paper myself.

**Comment by andres-erbsen** [comment]
I fixed both the mul-by-`2^224` and `id_with_alt` placement issue on https://github.com/mit-plv/fiat-crypto/tree/karatsuba-fix . However, it seems that we are totally missing a `reduce` instantiation for 448, so the integration test no longer builds after those fixes (previously, `goldilocks_mul` had the wrong type).

**Comment by JasonGross** [comment]
I've fixed the anomaly with reification.  Now there is an issue with the bounds, still; two of the limbs have upper bounds of `2^60 + 2^53 + 2^52`, which is not within the input bounds of `2^56 + 2^53`.

**Comment by andres-erbsen** [comment]
Jason Gross <notifications@github.com> writes:

> I've fixed the anomaly with reification.  Now there is an issue with the bounds, still; two of the limbs have upper bounds of `2^60 + 2^53 + 2^52`, which is not within the input bounds of `2^56 + 2^53`.

I am guessing the (1+1/8) rule just does not apply to the karatsuba
case. 2^61 sounds like a reasonable next try.

**Comment by jadephilipoom** [comment]
In which position are the limbs that overflow?

My guess is we need to do two modular reduction steps, carrying in between--my back-of-the-napkin calculation says the result of the multiplication is 13 limbs, then we do reduce, meaning we cut off the last 5 and add them back at positions 0 and 4. That gives us a 9-limb result, which we would then need to carry. This guess would predict one limb overflowing, though, not two.

**Comment by JasonGross** [comment]
Yeah, it's only one limb that overflows, not two; it's the fourth limb.  Let me paste the code

**Comment by JasonGross** [comment]
Code is:
```coq
  (fun var : Syntax.base_type -> Type =>
   λ '(H6, x9, x8, x7, x6, x5, x4, x3, (H13, x16, x15, x14, x13, x12, x11, x10))%core,
   uint128_t x17 = (uint128_t) (x6 + H6) * (x13 + H13) - (uint128_t) x6 * x13;
   uint128_t x18 = (uint128_t) (x5 + x9) * (x13 + H13) + (uint128_t) (x6 + H6) * (x12 + x16) -
                   ((uint128_t) x5 * x13 + (uint128_t) x6 * x12);
   uint128_t x19 = (uint128_t) (x4 + x8) * (x13 + H13) + ((uint128_t) (x5 + x9) * (x12 + x16) + (uint128_t) (x6 + H6) * (x11 + x15)) -
                   ((uint128_t) x4 * x13 + ((uint128_t) x5 * x12 + (uint128_t) x6 * x11));
   uint128_t x20 = (uint128_t) (x3 + x7) * (x13 + H13) +
                   ((uint128_t) (x4 + x8) * (x12 + x16) +
                    ((uint128_t) (x5 + x9) * (x11 + x15) + (uint128_t) (x6 + H6) * (x10 + x14))) -
                   ((uint128_t) x3 * x13 + ((uint128_t) x4 * x12 + ((uint128_t) x5 * x11 + (uint128_t) x6 * x10)));
   uint128_t x21 = (uint128_t) (x3 + x7) * (x12 + x16) + ((uint128_t) (x4 + x8) * (x11 + x15) + (uint128_t) (x5 + x9) * (x10 + x14)) -
                   ((uint128_t) x3 * x12 + ((uint128_t) x4 * x11 + (uint128_t) x5 * x10));
   uint128_t x22 = (uint128_t) (x3 + x7) * (x11 + x15) + (uint128_t) (x4 + x8) * (x10 + x14) -
                   ((uint128_t) x3 * x11 + (uint128_t) x4 * x10);
   uint128_t x23 = (uint128_t) (x3 + x7) * (x10 + x14) - (uint128_t) x3 * x10;
   uint128_t x24 = (uint128_t) x6 * x13 + (uint128_t) H6 * H13 + x21 + x17;
   uint128_t x25 = (uint128_t) x5 * x13 + (uint128_t) x6 * x12 + ((uint128_t) x9 * H13 + (uint128_t) H6 * x16) + x22 + x18;
   uint128_t x26 = (uint128_t) x4 * x13 + ((uint128_t) x5 * x12 + (uint128_t) x6 * x11) +
                   ((uint128_t) x8 * H13 + ((uint128_t) x9 * x16 + (uint128_t) H6 * x15)) + x23 + x19;
   uint128_t x27 = (uint128_t) x3 * x13 + ((uint128_t) x4 * x12 + ((uint128_t) x5 * x11 + (uint128_t) x6 * x10)) +
                   ((uint128_t) x7 * H13 + ((uint128_t) x8 * x16 + ((uint128_t) x9 * x15 + (uint128_t) H6 * x14)));
   uint128_t x28 = (uint128_t) x3 * x12 + ((uint128_t) x4 * x11 + (uint128_t) x5 * x10) +
                   ((uint128_t) x7 * x16 + ((uint128_t) x8 * x15 + (uint128_t) x9 * x14)) + x17;
   uint128_t x29 = (uint128_t) x3 * x11 + (uint128_t) x4 * x10 + ((uint128_t) x7 * x15 + (uint128_t) x8 * x14) + x18;
   uint128_t x30 = (uint128_t) x3 * x10 + (uint128_t) x7 * x14 + x19;
   uint64_t x31 = (uint64_t) (x30 >> 0x38);
   uint64_t x32 = (uint64_t) x30 & 0xffffffffffffff;
   uint128_t x33 = x31 + x29;
   uint64_t x34 = (uint64_t) (x33 >> 0x38);
   uint64_t x35 = (uint64_t) x33 & 0xffffffffffffff;
   uint128_t x36 = x34 + x28;
   uint64_t x37 = (uint64_t) (x36 >> 0x38);
   uint64_t x38 = (uint64_t) x36 & 0xffffffffffffff;
   uint128_t x39 = x37 + x27;
   uint64_t x40 = (uint64_t) (x39 >> 0x38);
   uint64_t x41 = (uint64_t) x39 & 0xffffffffffffff;
   uint128_t x42 = x40 + x26;
   uint64_t x43 = (uint64_t) (x42 >> 0x38);
   uint64_t x44 = (uint64_t) x42 & 0xffffffffffffff;
   uint128_t x45 = x43 + x25;
   uint64_t x46 = (uint64_t) (x45 >> 0x38);
   uint64_t x47 = (uint64_t) x45 & 0xffffffffffffff;
   uint128_t x48 = x46 + x24;
   uint64_t x49 = (uint64_t) (x48 >> 0x38);
   uint64_t x50 = (uint64_t) x48 & 0xffffffffffffff;
   uint128_t x51 = x49 + x20;
   uint64_t x52 = (uint64_t) (x51 >> 0x38);
   uint64_t x53 = (uint64_t) x51 & 0xffffffffffffff;
   uint64_t x54 = x32 + x52;
   uint64_t x55 = x54 >> 0x38;
   uint64_t x56 = x54 & 0xffffffffffffff;
   uint64_t x57 = x55 + x35;
   uint64_t x58 = x57 >> 0x38;
   uint64_t x59 = x57 & 0xffffffffffffff;
   return (Return x53, Return x50, Return x47, x44 + x52, Return x41, x58 + x38, Return x59, Return x56))
```
and the one that overflows is `x44 + x52`.

**Comment by andres-erbsen** [comment]
Reference: https://github.com/floodyberry/supercop/blob/a351f2c29235512a042d4b6989d241a67e86ad23/crypto_dh/ed448goldilocks/64/p448.c#L20 or https://github.com/floodyberry/supercop/blob/a351f2c29235512a042d4b6989d241a67e86ad23/crypto_sign/ed448goldilocks/amd64/p448.c#L9

**Comment by andres-erbsen** [comment]
That code seems to to two interleaved carry chains starting at 0 and 4. We should mimic.

**Comment by jadephilipoom** [comment]
Hmm, interleaving them might be tricky. I'm not sure how we would do that without making special basesystem code for the operation (currently, karatsuba only uses the basesystem API, and doesn't edit limbs directly).

**Comment by andres-erbsen** [comment]
?? can't we just specifu a carry chain that is 0 4 1 5 ...?

**Comment by andres-erbsen** [comment]
Also, I currently count 50 multiplications in our gcc output but only 45 in donna source...

**Comment by jadephilipoom** [comment]
We can specify the carry chain, but isn't the code you referenced doing it during the multiplication loop?

**Comment by andres-erbsen** [comment]
i don't know. it might just have commuted independent instructions compared to ours.

On June 15, 2017 8:04:06 PM EDT, jadephilipoom <notifications@github.com> wrote:
>We can specify the carry chain, but isn't the code you referenced doing
>it during the multiplication loop?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mit-plv/fiat-crypto/issues/182#issuecomment-308897303

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
