### ISSUE TITLE
Please create a tag for Coq 8.19 in Coq Platform 2024.01

### ISSUE THREAD

**Issue by rtetley** [mit-plv/fiat-crypto#1831]
The Coq team released Coq `8.19.0` on January 24th, 2024.
The corresponding Coq Platform release `2024.01` should be released before **April 30th, 2024**.
It can be delayed in case of difficulties until May 15th, 2024, but this should be an exception.

This issue is to inform you that to our (possibly a few days old) best knowledge the latest released version of your project (0.0.24) **does not work** with Coq `8.19.0`.
We tried to remove version restrictions in opam files and possibly make or configure files, but this did not suffice.

Please note that in Coq Platform CI (unlike Coq CI) we test only released / tagged versions. Coq CI is currently testing commit 4d9fadc163b8a09d75a6836e08f52f051fa489d4
47058dc312a5cad924972056cdfc4de06c432a82 on repository https://github.com/mit-plv/fiat-crypto
https://github.com/mit-plv/fiat-crypto - which likely means that this commit does work in Coq CI.

Could you please create a tag and opam package, or communicate us any existing tag that works with Coq branch v8.19, **preferably before March 31st, 2024**?
In case we might have to delay the Coq Platform release cause of issues with your project, we would prefer to be informed about the situation as early as possible.

In case the tag and opam package are available before March 31st, 2024, it will be included in an early Coq Platform beta release of the for Coq 8.19.0.

The working branch of Coq Platform, can be found here [main](https://github.com/coq/platform/tree/main).
It contains package pick [`~8.19~2024.01+beta1`](https://github.com/coq/platform/tree/main/package_picks/package-pick-8.19~2024.01+beta1.sh) which already supports Coq version `8.19.0` and contains already working (possibly patched / commit pinned) Coq Platform packages.

Please **don't** close this issue, even after creating the new tag and/or opam package.
We will close the issue after updating Coq Platform.
This is a measure of 'double book keeping' in order to avoid that we ship the wrong version.

In any case, Coq Platform won't be released before this issue is closed!

Thanks!

P.S.: this issue has been created automatically based on CI status.

CC: https://github.com/coq/platform/issues/405

**Comment by JasonGross** [comment]
I can tag a release and update opam once we get tags for
- https://github.com/mit-plv/coqutil/issues/112
- https://github.com/mit-plv/riscv-coq/issues/36
- https://github.com/mit-plv/bedrock2/issues/406
- https://github.com/mit-plv/rupicola/issues/102

**Comment by samuelgruetter** [comment]
I could create tags for these dependencies. I don't really care which versions end up in the platform. @JasonGross should I just pick whatever commit the fiat-crypto submodules point to?

**Comment by JasonGross** [comment]
Plausibly it makes sense to merge https://github.com/mit-plv/rupicola/pull/100 (and https://github.com/mit-plv/rupicola/pull/89?) first, but otherwise, yes @samuelgruetter , please tag whatever the master branch of rupicola points to (which should be the same as the fiat-crypto submodules)

**Comment by JasonGross** [comment]
I've released
- https://github.com/mit-plv/fiat-crypto/releases/tag/v0.1.2
- https://github.com/mit-plv/rewriter/releases/tag/v0.0.11 (up to you whether or not you update, both 0.0.10 and 0.0.11 should work)

and made https://github.com/coq/opam/pull/2992 to put all these packages on opam

**Comment by rtetley** [comment]
Perfect ! I'll wait for merge in opam and update the pick !

**Comment by JasonGross** [comment]
I've merged the opam PR

**Comment by rtetley** [comment]
Merged https://github.com/coq/platform/pull/407

**Comment by andres-erbsen** [comment]
So I've tied up a number of loose ends in fiat-crypto over the last week. Would it be possible to bump the fiat-crypto version that goes into the upcoming coq platform? 🙏

**Comment by rtetley** [comment]
No worries ! I don't see any new release though ?

**Comment by JasonGross** [comment]
@andres-erbsen should I tag a new release of Fiat Crypto on current master and update opam packages?  (And if current master is what you want used, could you or @samuelgruetter tag corresponding releases of the submodules?)

**Comment by rtetley** [comment]
@andres-erbsen , @JasonGross, @samuelgruetter, quick ping ! What is the status here ? Cheers !

**Comment by JasonGross** [comment]
I've tagged [Fiat Cryptography v0.1.3](https://github.com/mit-plv/fiat-crypto/releases/tag/v0.1.3).  Please keep using rewriter 0.1.11.  @andres-erbsen or @samuelgruetter could you tag releases for the other submodules again?  Then I (or someone else) can update opam.  Thank you!

**Comment by andres-erbsen** [comment]
I have tagged the dependencies at respective heads (which I checked to be in sync modulo CI changes):

- https://github.com/mit-plv/rupicola/releases/tag/v0.0.10
- https://github.com/mit-plv/bedrock2/releases/tag/v0.0.8
- https://github.com/mit-plv/coqutil/releases/tag/v0.0.6
- https://github.com/coq/opam/pull/3022

Thank you for accommodating us!

**Comment by rtetley** [comment]
No worries at all. Should go through with https://github.com/coq/platform/pull/411
