### ISSUE TITLE
Have a more coherent and saner pipeline definition

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#184]
The current definition is
```coq
       (let e := InlineConst e in
        let e := InlineConst (SimplifyArith false e) in
        let e := InlineConst (SimplifyArith false e) in
        let e := InlineConst (SimplifyArith false e) in
        let e := if opts.(anf) then InlineConst (ANormal e) else e in
        let e := RewriteAdc e in
        let e := InlineConstAndOpp (Linearize (SimplifyArith true e)) in
        let e := if opts.(anf) then InlineConstAndOpp (ANormal e) else e in
        let e := InlineConstAndOpp (Linearize (SimplifyArith true e)) in
        (*let e := CSE false e in*)
        let e := MapCast _ e input_bounds in
        option_map
          (projT2_map
             (fun b e'
              => let e' := InlineConst e' in
                 let e' := ExprEta e' in
                 e'))
          e).
```
We need, e.g., three `SimplifyArith` to propagate all of the `* 0` and `* 1` and `+ 0`, because arithmetic simplification isn't fused with constant-inlining.  We need them to *not* convert `adc` to `sbb`, because the adc-rewriter only knows the `adc` pattern (and for technical reasons involving DeBruijn indices it can only operate when the pattern it's rewriting is locally in a-normal form).  Then we need two passes of adc-to-sbb translation (done by `SimplifyArith true`) with an intermediate call to put things back in a-normal form because the first call to adc-to-sbb leaves a bunch of let-bound pairs of the form `let (v, c) := (let (v, c) := sbb ... in (v, -c)) in ...`, and we need to inline the negation into the subsequent call to adc/sbb so that arithmetic simplification can eliminate it (N.B. it's possible that we only need one call to `SimplifyArith true`, and the second call can be to `SimplifyArith false`).

This is pretty fragile, and was discovered by debugging and making educated guesses about what transformations I needed to insert where.  I don't think this is sustainable as we add more transformations.  At the same time, I'm not sure how to fix it.  I'm therefore recording it here.

**Comment by andres-erbsen** [comment]
Maybe we want to have different pipeline definitions for different targets? Saturated and unsaturated compilation are fairly different in my head...

**Comment by JasonGross** [comment]
What's different about them?

**Comment by JasonGross** [comment]
Significant progress is made in #373; this will be closed when we fully switch to the new pipeline.
