### ISSUE TITLE
X25519 performance regression due to bool

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#186]
before: 706752 crypto_scalarmult/curve25519/fiat51du gcc_-march=native_-mtune=native_-O3_-fomit-frame-pointer_-fwrapv
after: 713964 crypto_scalarmult/curve25519/fiat51d gcc_-m64_-march=native_-mtune=native_-O3_-fomit-frame-pointer

**Comment by JasonGross** [comment]
Shall I update the sed script to replace bool with uint64_t?

**Comment by andres-erbsen** [comment]
I would prefer if we only used the sed script for modifications that are sound on all programs.
