### ISSUE TITLE
Licensing of Amazon employees' contributions

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#192]
@jadephilipoom 

I see two ways this could go.
1. We get somebody appropriate from Amazon to say that working fiat-crypto is not a part of the job and the person who wrote the code holds the copyright, not Amazon.
2. If working on fiat-crypto ends up being a part of the job, or Amazon just insists on holding the copyright for the contributions anyway, we should get somebody appropriate from Amazon to confirm that the contributions are released under the MIT license. In this case, we should add Amazon to `AUTHORS`.

IIRC JasonGross did option 2 at Google, and I don't think we had any issues. The corporate form might be called something like "patches to existing open source project".

**Comment by JasonGross** [comment]
Yes, I did option 2, and had no issues.  The process was entirely automated (I submitted a form for the first three commits, it got automatic approval, and then I didn't have to submit the form anymore).

**Comment by jadephilipoom** [comment]
Indeed, good thing to bring up. I'll talk about it tomorrow and see what the process is at Amazon.

**Comment by jadephilipoom** [comment]
Talked to some people who are going to talk to some other people (probably lawyers). I'll get back once I know something. No one seemed to think it'd be an issue, though.

**Comment by jadephilipoom** [comment]
I have gotten (verbal) confirmation that it's fine and Amazon will consider it my personal hobby, as long as I don't work on this from any of their computers, which of course I won't.
