### ISSUE TITLE
ScalarMult scalar type

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#193]
Currently, `ScalarMult` uses `nat` as the scalar type. The fact that `nat` only encodes non-negative numbers seems to be causing inconvenience across the codebase. I can now think of some optimizations that I don't even know how I would verify with nat-based scalarmult.

OTOH, coding scalarmult with Z might make the proofs of basic properties awkward. The most natural way for me to think of scalarmult is on `Inductive pos := pos_one | pos_succ (_:pos)` and `Inductive int := int_pos (_:pos) | int_zero | int_neg (_:pos)`, but I guess we don't want to introduce even more numeral types...

**Comment by JasonGross** [comment]
> might make the proofs of basic properties awkward

In what way?  You can `destruct` a `Z` to get the pos, zero, and neg cases, and in the pos and neg case, you can do `induction p using Pos.peano_ind` to get `nat`-like induction cases.  There's also `induction z with Z.peano_ind`, which gives cases for `0`, for `Z.succ`, and for `Z.pred`.  Alternatively, there's `Z.replace_all_neg_with_pos` in `Crypto.Util.ZUtil.Tactics.ReplaceNegWithPos`, which works well with destructing `Z_dec : forall n m : Z, {n < m} + {n > m} + {n = m}`.
