### ISSUE TITLE
ArithmeticSynthesisTest for Montgomery multiplication

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#194]
How far away are we from having something like `ArithmeticSynthesisTest` that uses montgomery multiplication (leaving in admits)?  If we can get that, then I can start looking into adding loops to the reflective machinery.

**Comment by jadephilipoom** [comment]
The things on my radar are 1) stronger `small`, which we will presumably need somewhere (kind of holding off on this until I figure out exactly where) , 2) actually defining a `Z` version of two-output mul (this should be easy and doesn't have to be done by me), and 3) the admits left in the API section of `Arithmetic/Saturated.v`. Loops are also a todo, although I'm mostly considering that not-my-problem. Beyond that, I can't think of anything else we need, but maybe Andres has more.

**Comment by JasonGross** [comment]
I did 2 (https://github.com/mit-plv/fiat-crypto/commit/80687ca21d9f46fd4dd98bda163f096a43dd76b7).  If you want me to take care of the numlimbs admits, I can do that.  But I think we should hold off on the admits for now; I'd like to get all of the computational parts working, and then come back and fill in the admits after.

Does this mean that you could basically write an ArithmeticSynthesisTest-like file using wbw-montgomery now?

**Comment by andres-erbsen** [comment]
We need to rewrite WW_MM in CPS.

**Comment by jadephilipoom** [comment]
I propose eliminating the context variables and directly depending on the operations in `Arithmetic/Saturated`.

**Comment by JasonGross** [comment]
@andres-erbsen Like this? https://github.com/mit-plv/fiat-crypto/pull/200

**Comment by jadephilipoom** [comment]
Unfortunately, it's not that simple. You have to CPSify *every* operation inside `redc` that isn't getting compiled away--that means, if you leave in the context variables, you have to take in not just e.g. `divmod`, but `divmod_cps` and `divmod_id` and `divmod`, and then use `divmod_cps` in the code and `divmod` in the proofs. This explodes when you are using context variables (I went through this with Karatsuba once already) and that's why I'm saying we should get rid of them. 

Giving you a CPS version of the `Saturated` API will not be hard, since the current version is just wrapping things that are already in CPS. I should have that soon.

**Comment by JasonGross** [comment]
*nods*  What's the thing that we can't do with non-cps'd versions that we can do with cps versions?  (I'm asking in part because the reification machinery doesn't care; can cps things for us.)

**Comment by jadephilipoom** [comment]
At the partial evaluation stage (in the `ArithmeticSynthesis` files for those following along by files), we can't partially evaluate all the way because there are `dlet`s stuck in inner terms. I have a more detailed writeup in a comment here : https://github.com/mit-plv/fiat-crypto/blob/master/src/Arithmetic/Core.v#L8

**Comment by jadephilipoom** [comment]
On my end, this looks like "partial evaluation has been going for like 10 minutes". I'm not 100% sure lack of CPS is the entire problem, but I do know we have `dlet`s in inner terms and that just has never worked without it.

**Comment by JasonGross** [comment]
Ah.  So we are planning to fully unroll the montgomery loop, then?

**Comment by jadephilipoom** [comment]
I'm not sure why that would follow...

**Comment by jadephilipoom** [comment]
API now has CPS terms and proofs.

**Comment by andres-erbsen** [comment]
yes, we are planning to unroll the loop inside one Montgomery multiplication

**Comment by JasonGross** [comment]
CPS version using the CPS API done in 8079cc4

**Comment by andres-erbsen** [comment]
Turns out CPS partial evaluation does not work if our functions return `list`. We should do tuples like before. @JasonGross , you probably have the best handle on the WWMM code -- could you change it to use the tuple functions that are wrapped into list form in https://github.com/mit-plv/fiat-crypto/blob/06d3a5f4cffdf615f209677f6ffccd3e8b23a03b/src/Arithmetic/Saturated.v#L734, axiomating new ones for whatever is missing.

**Comment by JasonGross** [comment]
@andres-erbsen Can you point me at the place where you're trying to do partial evaluation, and it's failing?  I think I can do the modifications better if I also have a handle on what's going wrong.

**Comment by andres-erbsen** [comment]
my latest commit on master
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by JasonGross** [comment]
https://github.com/mit-plv/fiat-crypto/pull/204

Reduction is now blocked on the axiom of doing things like joining 0, doing divmod, and drop_high, suggestively named `JADE_HOW_DO_I_IMPLEMENT_THIS`.

**Comment by andres-erbsen** [comment]
I think 2a9bbdcb404875d4ae8d6542d846e53d619046c9 has got it.

**Comment by JasonGross** [comment]
Eh, not quite.  Still missing the following things:
- a definition of `m` (for `F m`)
- the conditional subtract at the end (I think reification can't yet handle `Z^4 -> Z^5`, because it won't be able to figure out how to transform the bounds on `Z^4` into bounds on `Z^5`)
- missing a `sig` whose correctness property is phrased in terms of `F m`

**Comment by andres-erbsen** [comment]
are all of these really necessary to proceed with compilation? m := p256, the conditional subtraction can be stubbed out by just dropping the highest limb, and the decoding function tuple-to-Z is redc with one input fixed to 1. I'll work on real versions of these tomorrow...

**Comment by JasonGross** [comment]
I now have
```coq
Definition mulmod_256 : { f:Tuple.tuple Z sz -> Tuple.tuple Z sz -> Tuple.tuple Z sz
                        | forall (A B : Tuple.tuple Z sz),
                            Saturated.small (Z.pos r) A -> Saturated.small (Z.pos r) B ->
                            let eval := Saturated.eval (Z.pos r) in
                            (0 <= eval (f A B) < Z.pos r^Z.of_nat sz
                             /\ (eval (f A B) mod Z.pos m
                                 = (eval A * eval B * r'^(Z.of_nat sz)) mod Z.pos m))%Z
                            }.
```
I'm not entirely sure how to get this to be in terms of `F`...

**Comment by andres-erbsen** [comment]
a tuple representation is valid if it is `small`.  
a montgomery-form number is valid if its `eval` is `< R`.  
Inputs being both tuple-valid and montgomery-valid gives output that is tuple-valid and montgomery-valid.
If inputs eval to `x` and `y`, the output should eval to `x*y * R' mod N`.

montgomery-form tuple `A` represents `a` if `eval A mod N = R*a mod N`.
If the inputs represent `a` and `b`, the output represents `a*b mod N`.

**Comment by JasonGross** [comment]
Updated in ff4b0ac to have a `small` postcondition

> If inputs eval to `x` and `y`, the output should eval to `x*y * R' mod N`.

Not so; we are just guaranteed that that it is equivalent to `x*y * R'` modulo `N`, and that it is `< R`.

In any case, the issue is not "how does the math connect" but "what form, precisely, do we want the specification in.  e.g., do we want to talk about F -> Z -> tuple and compare in tuple, or do we want to go tuple -> Z -> F and compare in F?  (I presume the later.)  Do we want to insert the final multiplication by `R'` at the tuple-level, or the `Z` level?  Would we want to synthesize a separate "convert-out" function in tuple-land and use it for the spec of mulmod, or do we use a not-partially-reduced version?  It's not the math I'm stumbling over, but the "how do we design this to fit with the rest of the framework?".

**Comment by andres-erbsen** [comment]
compare in F. multiply in Z level in the specs (essentially a composition of a Z-level spec and tuple-level spec about Z-s). Synthesize convert-out, but separately from specs.

So maybe the first step is to make a spec that doesn't have tuples in it, just Z-s, and show that the tuple spec represents those Z-s?

**Comment by JasonGross** [comment]
I expect the spec will look something like `forall A B, small A -> small B -> F.of_Z (???convert_from_montgomery??? (mulmod A B)) = F.mul (???convert_from_montgomery??? A) (???convert_from_montgomery??? B)`

**Comment by andres-erbsen** [comment]
Eventually there will be refactors, but for now, we have something.
