### ISSUE TITLE
Karatsuba code is silly

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#201]
We currently generate https://gist.github.com/andres-erbsen/4ab2c626247ff0f466faaed1ee7180cc (with assembly: https://gist.github.com/andres-erbsen/5b5664be1e7a084d75aecbc40e8761eb) which uses several multiplications more than https://github.com/floodyberry/supercop/blob/a351f2c29235512a042d4b6989d241a67e86ad23/crypto_sign/ed448goldilocks/amd64/p448.c#L9 Some of this is due to common subexpressions, but maybe not all.

**Comment by andres-erbsen** [comment]
@jadephilipoom have you looked into this? Does it still need to be done?

**Comment by jadephilipoom** [comment]
Still needs to be done; we decided a while ago that it wasn't urgent, so I've been thinking I'll look at it once I get to the chapter in my thesis that mentions Karatsuba. Should I prioritize it more?

**Comment by jadephilipoom** [comment]
On a close inspection, it doesn't look like we actually have more multiplications. Our assembly code has 47 `mulx`s and one `mulq`; the C code has 6 `widemul`s, 39 `mac`s, and 3 `msb`s (each of those operations involves one `mulx` or `mulq`; see https://github.com/floodyberry/supercop/blob/a351f2c29235512a042d4b6989d241a67e86ad23/crypto_sign/ed448goldilocks/amd64/x86-64-arith.h).

@andres-erbsen, what count did you take to determine that we had more multiplications? Perhaps only `widemul`?

I assume this leaves us with an unexplained performance issue.
