### ISSUE TITLE
intel MULX intrinsics

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#205]
https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=_mulx_u64&expand=3755

We probably want to output these instead -- while compilers do recognize our shifts as MUL, they output MUL, not MULX, which significantly increases register pressure.

**Comment by andres-erbsen** [comment]
https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAKxAEZSBnVAV2OUxAHIBSAJgGY8AO2QAbZlgDU3fgGEGBfEIIA6BDOzcADAEE%2BgkeKkzZADwAcANmEFiwtRu16BwsRMzS5C9ACNUqUQd%2BTV0CAE8AB0wsADNJZiEGPGAhaMkbeJtaXnMAfQJJXNyAQwJbPB9mAkwiqABbDEwIABUASQBKTpkAIScnADdUPHRJYAhmG0sAFnyAKkkWAlJM5Wn8yQtlidWZgtMATi3J3Y2AdiOd9dMAVguCNb3aKbuHjdpblfuT01p%2BF%2B/aLR2n1Tt1JJ9snlHpZPAARSTjLI5fLtDbXSTzH60HogsGfV4/U5whHbL4ot4wvgwrSmGJ0%2BkMxkxAAyON03FB4NJBNo5mJiMuBFREB%2BlOCGkkNKmWmB/F67M5EORj32/NJkPJNwxb34bL0iu5314WjVx01tFVVMltKZtrprLluK5Zr2vFopsFwp%2BlvFwWt0tl8v1ePVyo2vF4HoIGqFaO1P2ueo5IZd4f4UYeqNMEekvGpNrtTIdQeTzsF4amGd2Xpzjj9UplSYNSKh4fRMnhAujyqz6MxTybKfL2bFncNmt47bz1sLtuLTvxRqJHZJLpr7d92H9jcdCqHZNd%2Bx6n1bpn4JpXJXQ6GQxWIxDCplyzGmEBpWmWP3Mn%2BNyyp2f2QMF3HPZ%2BF4Y9SVPfh00vYpr1ve9H2fV8zw/cN6DTP88zPXggL3MsDw2fhEzlE8rn4UdCjgm87wfJ8XymEVoJ/Z5w0sLDLDPa48ODAiCX4cwIJsVtcmJK8aMQ%2BjX3fT8KJ/c5c04gSeNLRcrmlYlCUUmdZ0Zed8KVU8pndFcuxjLMNPmGldL0wc%2BO%2BKZI1MkCLJM6drJs%2Bl9N4tS9imGD%2BDHNcEVMYzPE0etQp3Etm2UGMNimStnJbTVLJ0pk7N8hKNyCz0EqS9yC087zVJAhLKK7TMQsS8KJQbFTYu7Izl0C1c4p7BKTSsoqGS0Pr%2Bq0WgSsagkpj5ZK8tC5dCs8rzMrK0KfVyg8vSmFqIq3er5tTG5sVIyCrmuJzWvEhC6OQxiZISv5so43aGv3AlrimITlFPa4cqo%2BDaKQhiRSOz8pnY600P/Z6Hvsw7Tlegh3vGk7qLO36UI%2B5YrtC79FJuU4Iay0xLC0GGRLExGfqky7TDQm5McWu6CdxsrciJq5phJ77JIut9Kc/WgFNC3gONyBmdssSxmb2SwWvhU6yc5/HWIAz9rgw/9ReF4dLCPfbhKuU4LwR9nzr%2B/G%2BbApXWNVwDtuHU5wO1t7dYC6XSY5429dkj5sbu231cI0xThIsEDr2U5KJl12UNOG6zxpgnve462mt1qW2qT2N/fjQFE4JU54eWqr/em/NZvtbPvlOJbU6qkVTnWuqot9%2BKLH15bzLOTPdV3HyFvMEzWsq6sNnMC8ZpL4bHu%2BcxjvzweRWH2rIoDROm/MJ3U7bjP%2B0D4CdvMJL%2B5coeYNH2bx8hvZzE%2BgfyTngKNu3RuwwsCrQyhLMiX7F6u9K3eU%2Bv9OrDaQ8qfMuVxzB5yrrPZ%2BC9NoN1AXsfYhN7awyuPsPuztDbIwplTCun5e53UQb7Ak%2BxO5Bx1gg/eGCJJGxQmgvBAsh4W2wiQoh3x9hi2QaefYKdw40MYgcBWl88EKX/Ow1hqCtZkIdgUUSsFMHky5lTbheDMaiKtt/EaAItB2ykSgx4Wg168KwYoz8otPy5zurQbR4j9GBzIvosOLs%2BEiisdHTWn5EGWK0AnDRE8rhWMEpw/xWhK5GIUT8LQwN/YMIODdf8ASbFvCzkEx42Q2bUOMREw4ZxPbsMsYCRJWIv66NPICT6YS5aAhiaHDx2T4lPEKYCSiESnIn2KsvJ%2BgI/6v3NLQGE3US4sngUkiB/8sxdKAT1XSZ88aAkrmMkKEy6ywKXr4giTdsgt3Xh1LE/T0qMmGT8N0VZzTGkmYMmZC1sjT0gTfI5%2Bt75bTWYZfxAgowbyadqYBjIBr9SGoc7IlDbnp2yMfYuY8AWThObGFxbzlkP0hdDFJbwcjpKRgo9GcyeZuksbwHGALzzix1Ogr6GTwmQmxQwq68TzyNOgkSn4/AgUVONr8DCmLeBMM4r8fgdKOElPWLIg2ZLOaYqZdij4NLLCJKZsin4Gk5Eir%2Bpi7RPNeSC0aY5BlTxDFOMyU8KmVjPbZBEdhJ4uEAVTDscHN4QM0Wy1Zf5HmWgaa/FBmaq1mrAkCseFMUJeryVAzVRhRlcSPXmEacrbVR17UR34U8bJRSeZySxu8IEALrhrwWe%2BXMYIEytLzWUjppTnrvJ2aqfse0Yp%2BMeB9aF4zS1Wm%2BTZS5O13gv2Ci4xtm4EXPJ6bW7pKV04Vp1Bm0Zh8ExF32S2jN8zD5drrovaKO92qlIJmWt%2BGwR0JgBZYElCzRQj3BSAvtbbLA3IWS49d8KnnVvWZ0ywWb%2B1Zm3QOU9w4%2BlAoPX0sF07pm7qvvO0Ud966rLvbMyW2rLAQJZdJbmbxrhRPeKos1ktGl621acElsH43QZ5tcRNfSVZmr1uh0h9i3inGZQGypWGebnvo1ywkvKAWhyJUKqh6LRXwcJArPpkqSPStY5IijX4tk4ZMbamJ7wBPcoro0qe2rV6xucWJnmVr6Omu5VPBT1ryFvEAYqrjrLV7qdde7VNl8FPetE7yf18jKlWHwyG3mYbtMRoBWg7V%2BwbkSa/IRzNPMamprQY0khmleaWjaTO99ac3j7C/c%2B%2BL6YBkQtizyfYgHgregKse9p6WATsPrYshLMDe3gf7fFwdq7zThdSxlAr/j9jjuyxaKdzb/2NZVHOzt3pF0rOXQZSr2Y%2Bobtqylv9dJfl9X%2BV18Mg1isjaPZNwsrbhzGgvUB40DzQODe7jtY0xTRPGnKTR5VPGLRIea3dQ7hTjRIp9fNmDZ2UInZ5vsbJ1LsL3bu1YhlbpsMvf4caTG6NjTEc4m6PbP91u/HYyp4xYPAQ/lVVjN0LG5uyse9mXmCOMUXdwfF2TQtDluhEza7MZyjMOte7zHmU8UdMbJ3diM/24XCuM6938BnPb3ZuxGFnenpHhmnNTuNIoIzR15DTKH/OfEVYOzkNn9mlVc6uyG9H/OPNzezOeYrOa%2BB5ojFFwtPni1XAEPupLFhM5VpXX7AQm3suW/OWlhX63oLFYl/wPujy4GxabgIRLQ6sx8n7KQ%2B3BIBBZcmkH13J73cO4ol73X%2B8/dgft4H/g1W06h8ztvIbB2BKLYEO1qZs41tJ563lb3/XyuZ6fpyrZZkdlh9taTsKE0VoVmWx1ivHenc1%2BzAqntt7I9GkSv9q1ePuNUwENHaPN3Ep3bWlP57Dnjact5ym3XKHIdrTu9cJB2PJyA4369saP5%2BCJs5RD7MR/D/kZtRx0lnPsE/mVixBh/5JwY8T1HxDf7a4HhIHSTHHG/M2NHRDQ/cnfTEccTUA%2B/PmCMGJTlJnAjO7c9f7R9GfTfOOEXXnNaG7c9TAoXPRNiRxc/YHR9H8HID/d1SHSweXcfC3aDeHMXVTPMKJAQOfQLNHaDO7PWTSScSkaLTrRPQPLDMbdOPFLqFbO0SvKPW2EvKQptcvVbUnKOFPPFX3XbR%2BU8PFYPGrGQoQ%2BrA5HXPFGPbvbMKjePfLf/JcDtIfQwsrMfQvYw8MWuaQrMWQr5dQ6bQaRQpcFrWPLwtQi5TQ6vbvCXMI0ff3Bwi3Xuf7KeXAuDOfKOeSWTbMXuO7PeZI07KgiXBnTw4GL7SHPeXIh7Y7cBVI4HIREGeSPfbI/FCwxBdgjnGnd/cMcBeSOpb7QhYZLHY7UrDgxHHjEQ%2BSb/PMEnVo/lYYkAwogCBWScG/fBNHMRUnD7Blc8BAxY3gZRNiVAveG7D7Qpc8HRUTc8XVRYnYn8Jgn8cwLTVCC1HXc8Mg4mUY8JK4u4mXTxLGN4niRYbga4boQma4eEFcVCAvHQIEkE7EcEzSc4vUWE7ocCBEyE/YyRJwFE3UdE1qACflEEWEDkYk04Uk8kkkykskqkik6kuk2khkmkpk%2Bk5kxklk9ktkzk1k7kjknkrk3kgU/koUvkkUwU0U4UsUyUiU6U8U2UqUuUmU%2BUpUxUrk3QAAejVMkFvFEFEEwGIBACyhRJenBL1E4HaFIFEC4GuE4FICEC4C0BtNQC4FkEN0N0kCYFYHYFzB9xtIIHtLNPNIAGsQBoIVBoJwyIzIz2JLTOApgbS7TOAHTSAnTOAbSGAQAPw/TEyzTSA4BYAkA0A6gIg8BdSyAKAIBCzizSyQA8BkBkA6cYgSzqhiB0yIAfB/TSBCy6hMBlAAB5IQUQMIDs/AYgTAZAAgPAfoTAdM7M8gZQTAGMh0801ACICc1ARILgAAWl7PTE3LqFZk3JiFQDqEIEPOIGKG7M3IiCGHnOIEkEPIAHdzyIh%2Bh7yYgohiATyGAkgpz7y6g7xkB1BAoGBAywhRBihAyPA9yCAEhMAOwQKwKIKoL/z0BTA0yWA2AOAgQLSrT4yOyUzn5NzWZazkBJBccIBcBCASBvSMJZBjyqy9SaL2hfT/TOhSBgzQzIyuLwzoyuA4zbT8KuA0yMzSAsylzcyYBEAQBFgIgqhyBKBKySy9S6BSBogqL9TsKYzrSBLZyUz9B3QHzCAEAh5LAiLKwSKyLTgWLsy2KOL%2BAwzuKuKcLYy8LdKhLGARKxKAznLeBXKkyUzrKlzzSpyWy8B1yQApggA%3D%3D

**Comment by andres-erbsen** [comment]
@JasonGross did you ever test this? The intrinsic reference says the pointer-based output is for the high half, but `p256`  mul seems to be using it as if it was the low half... I am guessing our notation is just backwards.

gcc seems to match the intel reference this time


~~~~~~~~~~~~~~~
#include <stdint.h>
#include <stdio.h>
#include <x86intrin.h>

int main(int argc, char** argv) {
	if (argc != 3) {
		return 111;
	}
	uint64_t a = 0;
	uint64_t b = 0;
	sscanf(argv[1], "%llu", &a);
	sscanf(argv[2], "%llu", &b);
	unsigned long long hi = 0;
	unsigned long long lo = 0;
	lo = _mulx_u64(a, b, &hi);
	printf("_mulx_u64(%llu, %llu) = 0x%llx + (0x%llx<<64)\n", a, b, lo, hi);
}
~~~~~~~~~~~~~~~

~~~~~~~~~~~~~~~
browse@ashryn ~ % ./mulx $((256*256*256*256)) $((256*256*256*256+1))
_mulx_u64(4294967296, 4294967297) = 0x100000000 + (0x1<<64)
~~~~~~~~~~~~~~~

**Comment by JasonGross** [comment]
> did you ever test this?

No.  Can we add a makefile target that will fail if the code is obviously wrong like this?

>  I am guessing our notation is just backwards.

The easiest way to fix this is to update the `sed` script; otherwise we'd have to reverse the returned pair at all reflective levels.  (It's unfortunate that `mulx` is backwards from `addcarryx` and `subborrowx`.)  I believe (untested) that the new `sed` line should be:
`sed s':^\([^,]*\),\(\s*\)\([^ ]*\) \([^ ]*\)\(.*\)\(mulx.*\))\([; ]*\)$:\3 \4;\2\1\5_\6, \&\4)\7:' | \`

**Comment by andres-erbsen** [comment]
Yes, such a target already exists on my machine and I will commit when it passes.

How is it backwards? I think all of them return the least significant part and pointer-store the more significant part? Why sed instead of changing the coq notation?

**Comment by JasonGross** [comment]
No, `_addcarryx_u64` returns the carry (`ret / bound`) and pointer-stores the value (`ret mod bound`), while, apparently, `mulx` returns the low bits (`ret mod bound`) and pointer-stores the overflow (`ret / value`).

There is a single Coq notation responsible for `addcarryx`, `subborrowx`, and `mulx` (it's the notation for anything that returns a pair); we can't change one notation without changing the others.  So we have to change the actual interpretation of `mulx`.  I can do this (estimated: 20-60 minutes); shall I?

**Comment by andres-erbsen** [comment]
Okay, you are right. The "convention" they are following is "whatever x86 does", which never made sense anyway. Nah, the current way makes sense, and we are sed-ing mulx already anyway, so I will modify that instead. One day when we get rid of sed we probably want to make separate notations for these.

**Comment by JasonGross** [comment]
> One day when we get rid of sed we probably want to make separate notations for these.

Yes, when we move to Coq 8.7 / 8.6.1, we should be able to use notations for these (as per https://github.com/coq/coq/pull/634), and fix this issue at the notation-level.
