### ISSUE TITLE
Add csubtract to API, fix small_add

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#207]
Here's what remains in the context to be instantiated:
```coq
  Local Notation conditional_subtract_cps := (@drop_high_cps
R_numlimbs).
  (*Axiom conditional_subtract_cps : T (S R_numlimbs) -> forall {cpsT},
(T R_numlimbs -> cpsT) -> cpsT *)(* computes [arg - N] if [R <= arg],
and drops high bit *)
  Axiom conditional_subtract : T (S R_numlimbs) -> T R_numlimbs (*
computes [arg - N] if [R <= arg], and drops high bit *).
  Local Lemma small_add : forall n a b, small a -> small b -> small
(@add n a b).
  Proof.
    intros; apply Saturated.small_add; auto; try lia.
    cbv [uweight].
    rewrite ?Znat.Nat2Z.inj_succ, ?Z.pow_succ_r by lia.
    try nia.
  Admitted.
  Local Lemma small_add' : forall n a b, small a -> small b -> small
(@add' n a b).
  Proof.
    intros; apply Saturated.small_add; auto; try lia.
    cbv [uweight].
    rewrite !Znat.Nat2Z.inj_succ, !Z.pow_succ_r by lia.
    try nia.
  Admitted.
  Axiom conditional_subtract_cps_id : forall v cpsT f,
@conditional_subtract_cps v cpsT f = f (@conditional_subtract _ v).
  Axiom small_scmul : forall (n : nat) (a : Z) (v : T n),
      small v -> 0 <= a < Z.pos r -> 0 <= eval v < R -> small (scmul a
v).
  Axiom eval_conditional_subtract
    : forall v : T (S R_numlimbs),
      small v ->
      0 <= eval v < eval N + Z.pos R ->
      eval (conditional_subtract v) = eval v + (if Z.pos R <=? eval v
then - eval N else 0).
  Axiom small_conditional_subtract
    : forall v : T (S R_numlimbs),
      small v ->
      0 <= eval v < eval N + Z.pos R ->
      small (conditional_subtract v).
```

**Comment by jadephilipoom** [comment]
Tried to fix `small_add`, but it's not possible to prove in general that you can safely add two `n`-limb numbers and get an `n`-limb number out. I have something that works if your output has a number of limbs *strictly* greater than the max of the input numbers of limbs, which seems correct to me.

**Comment by JasonGross** [comment]
Are you missing the `pred` in `pred_ nm` because the convention is terrible and different from everywhere else?  `add n n n` means "add two `n`-limb numbers, get `S n` limbs out"

**Comment by jadephilipoom** [comment]
I believe your pull request #210 fixes the `small_add` issue, so now it's just `csubtract`.

**Comment by jadephilipoom** [comment]
Also, `small_scmul` already exists.

**Comment by jadephilipoom** [comment]
`conditional_sub` is going to take a "mask" argument, and a precondition saying that `Tuple.map (Z.land mask) N = N`. This should be easy to prove whenever the point is that we narrow it to bases that are powers of two (is that in your Montgomery proofs, or not until synthesis?). It will be similar to this precondition on `freeze`:

https://github.com/mit-plv/fiat-crypto/blob/6ef07499aed3a023c19cee4ec1cb797ea861c60c/src/Arithmetic/Saturated.v#L638

**Comment by JasonGross** [comment]
I presume it will be `eval_conditional_sub` that takes the precondition?  Am I correct that `mask` will be `r-1` (`2^64-1` for 64-bit limbs)?

These are fine; the wbw montgomery proofs will fill `mask` and pass along the precondition to their callers, and MontgomeryP256 will prove the mask precondition by `eq_refl`.  I'll do this once you push csub.

**Comment by jadephilipoom** [comment]
Yes, that's correct.

**Comment by jadephilipoom** [comment]
Okay, should work. Let me know if there are any issues.

**Comment by JasonGross** [comment]
Thanks!  Only issue is #214.
