### ISSUE TITLE
conditional moves in C

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#212]
Apparently there is no way to tell a C compiler to generate a suitable conditional move. We probably want to use inline assembly... We should either use ternary conditionals and manually check assembly that it actually emitted a cmov, or do redundant comparisons in inline asm like (untested):

    inline void cmovnz_u64(uint64_t cond, uint64_t src, uint64_t dst) {
    	__asm__("testq %1,%1; cmovnzq %2,%3"); // TODO clobber flags
    }

**Comment by JasonGross** [comment]
[Currently we emit ternary conditionals](https://github.com/mit-plv/fiat-crypto/blob/93913fd7b76eea1d2b7ea1c4f7c62b9d5defc460/src/Specific/IntegrationTestMontgomeryP256Display.log#L103).  It's pretty easy for me to emit `cmovnz_u64(cond, src, &dst)` (or `cmovnz_u64(cond, src, dst)`? (can you actually do assembly like that without taking in a pointer?))

**Comment by andres-erbsen** [comment]
The ternary conditional in p256 right now emits a cmov, so let's consider it decided.
