### ISSUE TITLE
Sub-with-carry chains

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#213]
A little while back we had to special-case a certain string of instructions in addition chains so that the carries propagated nicely (#171). It looks like we need to do the same thing with subtract. The code, both the input and the desired output, is the same as in that issue, except some of the adds are subtracts. That is, when subtracting `(a2,a1,a0)` and `(b2,b1,b0)`:

```
s0, c0 = SUB a0 b0
s1'', c1'' = SUB a1 b1
s1', c1' = ADD c0 s1''
c1 = c1' + c1''
s2'', c2'' = SUB a2 b2
s2', c2' = ADD c1 s2''
c2 = c2' + c2''
...
```

The compiler optimization should convert this to:

```
s0, c0 := SUB a0 b0 
s1, c1 := SBB c0 a1 b1
s2, c2 := SBB c1 a1 b2
...
```

Jason, can you do this?

**Comment by JasonGross** [comment]
Not sure where you're getting that we need to do this from.  The missing optimization that I'm seeing is that we need to do adc-fusion even when we don't add the final carries.  I've been fighting with the adc-fusion optimizer all day to try to make this happen; it's *extremely* frustrating that Coq's pretyper is broken, and compiles some deep `match`-statements into ill-typed terms, and compiles other ones into hundreds or thousands of cases, even when there are really only two distinct cases.

Question: Should we be doing adc-fusion even when we don't add the final carries?  Or should we do something else?

**Comment by jadephilipoom** [comment]
I'm getting this by looking at the difference between our code and the reference code.

What are you calling adc-fusion?

Also, this is not saturated arithmetic, please remove it from that milestone.

**Comment by JasonGross** [comment]
I've been calling everything in P256 "Saturated Arithmetic".  Maybe we should add a separate P256 milestone?

Assuming the optimization is still missing after my recent changes involving a-normal-form and handling of code missing the final carry-addition: What code, precisely, is missing this optimization?  (Do you have a link/pointer to it?)

**Comment by jadephilipoom** [comment]
Yeah, I think we should rename it p256. It's confusing because to me saturated arithmetic is just the basesystem part.

Yeah, here's the link : https://github.com/openssl/openssl/blob/master/crypto/ec/asm/ecp_nistz256-x86_64.pl#L1209

It's not exactly the same as our code. But the point is, we're currently doing an extra step to add the carries together and then add them to the next digit, when we could be making use of the carry flag.

**Comment by JasonGross** [comment]
I meant, which line(s) in our code is wrong / suboptimal?

**Comment by JasonGross** [comment]
(Note that the way the pipeline is intended to work is that first all patterns of the form given in #171 are rewritten, and then, after that, adc is converted to sbb; this means that there should be no patterns of the form here left to rewrite.)

**Comment by jadephilipoom** [comment]
Okay, I see. I hadn't looked at the final output, just the initial state, and guessed we would need this. That's fine, then.
