### ISSUE TITLE
Generated code does not end with `return`

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#215]
Due to [Coq bug #5523](https://coq.inria.fr/bugs/show_bug.cgi?id=5523), the obvious way of getting `return` on the last line doesn't work when there's an `adc` or `sbb` right before the returned value.  Thoughts?

**Comment by andres-erbsen** [comment]
Do we have a good story why `Return` would not appear on other lines? If so, not having `return` is fine.

**Comment by JasonGross** [comment]
In valid C-code (i.e., no operations unaccounted for) that is linearized (i.e., there are no let-bound tuples), `Return` will not occur except on the final line.

**Comment by andres-erbsen** [comment]
Then I think we don't need to hurry with fixing this issue. But let's leave it open so we know it is fragile and fix it if we can think of a way.

**Comment by JasonGross** [comment]
Well, if and when we drop support for Coq 8.6 in favor of Coq 8.7, we can just uncomment the relevant notations.

**Comment by andres-erbsen** [comment]
Can we conclusively fix this now given Coq8.7? `fesub` might be a good test case.
