### ISSUE TITLE
WWMM: subtract N if output >= N

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#219]
Currently, the word-by-word montgomery reduction subtracts the modulus `N` if the output is less than the total representable range `R`. This does not integrate well with addition and subtraction (I missed that the first time around, sorry). Instead of passing in a carry bit to conditional subtract, we want to subtract `N` first, use the subtraction output if it is non-negative, but cmov in the subtraction input in case the subtraction produced a borrow bit.

`subtract_if_nonnegative` or whatever we wanna call it should go to Saturated. It should be implemented as a chain of substract-with-borrow instructions, followed by a `zselect : condition -> Z -> Z -> Z` lifted to tuples. The zselect should take the final borrow from the subtraction chain as the trigger input. I think spec of `subtract_if_nonnegative x N` is that `out = if x < N then x else x - N`.

In WWMM, we should assume `a,b < N` and prove `output < N` instead of `<R`.

**Comment by andres-erbsen** [comment]
Oh, turns out the manually-triggered conditional subtract is still of interest: the conditional subtract after field element subtraction needs to be triggered on whether the subtraction underflowed.

**Comment by JasonGross** [comment]
> the manually-triggered conditional subtract is still of interest

This will need to be factored out of the current `conditional_sub`, which always triggers on `left_hd p`.

**Comment by JasonGross** [comment]
The type signature of the new `eval_conditional_sub` lemma is given in https://github.com/mit-plv/fiat-crypto/commit/95bec50f32990673e8a2630aaa65568e1d21f7f2, with the name `eval_conditional_sub_THIS_AXIOM_IS_ACTUALLY_CURRENTLY_FALSE_AND_IS_AWAITING_A_REPLACEMENT_IMPLEMENTATION_OF_CONDITIONAL_SUB_THAT_SUBTRACTS_BASED_ON_BEING_NOT_LESS_THAN_N_RATHER_THAN_ON_BEING_NOT_LESS_THAN_R`

**Comment by andres-erbsen** [comment]
Require Import Crypto.Util.CPSNotations.
    Definition zselect2_cps cc {n} : Z^n -> Z^n -> Z^n := Tuple.map2 (Z.zselect cc).
    (* sub_unless_underflow x y = x-y if x > y else x  *)
    Definition sub_unless_underflow {a b} (x:Z^a) (y:Z^b) :~> Z^a :=
      xmy <- @Columns.unbalanced_sub_cps (uweight bound) a b a x y;
      return zselect2_cps (fst xmy) x (snd xmy).

**Comment by andres-erbsen** [comment]
We are not the first to be confused by this: https://github.com/openssl/openssl/commit/b62b2454fadfccaf5e055a1810d72174c2633b8f#diff-f10558b2dabb2196e77eab778728af61R304

**Comment by jadephilipoom** [comment]
@andres-erbsen The code there using Tuple.map2 should actually be what we want, right? Is there any reason not to just put that in?

**Comment by andres-erbsen** [comment]
As far as I can see, it should go in.
