### ISSUE TITLE
add-with-carry optimization anti-patterns

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#222]
I found a major issue with my implementation of #171.  @jadephilipoom requested optimizing
```
s0, c0 := ADD a0 b0
s1', c1' := ADD c0 a1
s1, c1'' := ADD s1' b1
c1 := c1' + c1''
```
to
```
s0, c0 := ADD a0 b0
s1, c1 := ADC c0 a1 b1
s2, c2 := ADC c1 a1 b2
...
```
I believe (though I'm only like 80% confident) that this isn't actually powerful enough; I think the assignment of `c0` doesn't always come on the line immediately preceding `ADD c0 a1`, in particular when we put the code in a-normal form (which is required for doing this rewrite in some cases, in part due to the limitations of variable equality testing and the named representation).

Therefore, the optimization I actually implemented is the strictly more powerful:
```
```
s1', c1' := ADD c0 a1
s1, c1'' := ADD s1' b1
c1 := c1' + c1''
```
to
```
s1, c1 := ADC c0 a1 b1
s2, c2 := ADC c1 a1 b2
...
```

However, this breaks Montgomery `opp`, which has code like (128-bit version):
```coq
    (fun var : Syntax.base_type -> Type =>
     λ '(H, x1)%core,
     ℤ H0, ℤ x3 = addcarryx_u128ℤ(0x0, 0x0, Op (Syntax.Opp Syntax.TZ Syntax.TZ) (Return x1));
     ℤ H1, ℤ x5 = addcarryx_u128ℤ(0x0, 0x0, H0);
     ℤ x6 = x3 +ℤ x5;
     ℤ H2, ℤ x8 = addcarryx_u128ℤ(0x0, 0x0, Op (Syntax.Opp Syntax.TZ Syntax.TZ) (Return H));
     ℤ H3, ℤ x10 = addcarryx_u128ℤ(0x0, x6, H2);
     ℤ x11 = x8 +ℤ x10;
     ℤ x12 = x11 == 0 ?ℤ 0x0 : 0xffffffffffffffffffffffffffffffffL;
     ℤ H4, ℤ x14 = addcarryx_u128ℤ(0x0, H1, x12 &ℤ 0xffffffffffffffffffffffffL);
     ℤ H5, ℤ x16 = addcarryx_u128ℤ(0x0, 0x0, H4);
     ℤ x17 = x14 +ℤ x16;
     ℤ H6, ℤ x19 = addcarryx_u128ℤ(0x0, 0x100000000000000000000000000000000L *ℤ x11, x12 &ℤ 0xffffffff000000010000000000000000L);
     ℤ H7, ℤ x21 = addcarryx_u128ℤ(0x0, H3, H6);
     ℤ x22 = x19 +ℤ x21;
     ℤ H8, ℤ x24 = addcarryx_u128ℤ(0x0, x17, H7);
     ℤ _ = x22 +ℤ x24;
     return (H8, H5))
```
or (64-bit version):
```coq
    (fun var : Syntax.base_type -> Type =>
     λ '(H1, x3, x2, x1)%core,
     ℤ H2, ℤ x5 = addcarryx_u64ℤ(0x0, 0x0, Op (Syntax.Opp Syntax.TZ Syntax.TZ) (Return x1));
     ℤ H3, ℤ x7 = addcarryx_u64ℤ(0x0, 0x0, H2);
     ℤ x8 = x5 +ℤ x7;
     ℤ H4, ℤ x10 = addcarryx_u64ℤ(0x0, 0x0, Op (Syntax.Opp Syntax.TZ Syntax.TZ) (Return x2));
     ℤ H5, ℤ x12 = addcarryx_u64ℤ(0x0, x8, H4);
     ℤ x13 = x10 +ℤ x12;
     ℤ H6, ℤ x15 = addcarryx_u64ℤ(0x0, 0x0, Op (Syntax.Opp Syntax.TZ Syntax.TZ) (Return x3));
     ℤ H7, ℤ x17 = addcarryx_u64ℤ(0x0, x13, H6);
     ℤ x18 = x15 +ℤ x17;
     ℤ H8, ℤ x20 = addcarryx_u64ℤ(0x0, 0x0, Op (Syntax.Opp Syntax.TZ Syntax.TZ) (Return H1));
     ℤ H9, ℤ x22 = addcarryx_u64ℤ(0x0, x18, H8);
     ℤ x23 = x20 +ℤ x22;
     ℤ x24 = x23 == 0 ?ℤ 0x0 : 0xffffffffffffffffL;
     ℤ H10, ℤ x26 = addcarryx_u64ℤ(0x0, H3, x24 &ℤ 0xffffffffffffffffL);
     ℤ H11, ℤ x28 = addcarryx_u64ℤ(0x0, 0x0, H10);
     ℤ x29 = x26 +ℤ x28;
     ℤ H12, ℤ x31 = addcarryx_u64ℤ(0x0, H5, x24 &ℤ 0xffffffff);
     ℤ H13, ℤ x33 = addcarryx_u64ℤ(0x0, x29, H12);
     ℤ x34 = x31 +ℤ x33;
     ℤ H14, ℤ x36 = addcarryx_u64ℤ(0x0, H7, 0x0);
     ℤ H15, ℤ x38 = addcarryx_u64ℤ(0x0, x34, H14);
     ℤ x39 = x36 +ℤ x38;
     ℤ H16, ℤ x41 = addcarryx_u64ℤ(0x0, 0x10000000000000000L *ℤ x23, x24 &ℤ 0xffffffff00000001L);
     ℤ H17, ℤ x43 = addcarryx_u64ℤ(0x0, H9, H16);
     ℤ x44 = x41 +ℤ x43;
     ℤ H18, ℤ x46 = addcarryx_u64ℤ(0x0, x39, H17);
     ℤ _ = x44 +ℤ x46;
     return (H18, H15, H13, H11))
```

This is very bad, because there are cases that fit the second pattern but not the first.

Fixing this by bounds-testing the carry-bit to determine when to apply the optimization is a non-starter; it'll make a proof that currently takes a full minute to compile take something like 64x longer, because code that currently only works on Z will have to work on every combination of Z and Word.

It looks like the all the carry bits in the add-carry chain are dead, though; why are we using add-with-carry there, and can we fix it to not do that (@jadephilipoom)?

**Comment by andres-erbsen** [comment]
This looks like a pain, and I would take it as a long-overdue sign that we are just doing sub wrong -- reusing the columnwise compaction operation we originally for adding up partial products after multiplication might let the proofs go through, but has forced us to implement a patchwork of rewriting rules. How about we re-implement a carrying addition/subtraction operation from scratch, perhaps by folding over a pair of tuples carrying a single carry bit? @jadephilipoom

**Comment by JasonGross** [comment]
Tangentially, re priorities, I'd say #219 takes priority over this, because if we have #219, I can just disable the optimization for sub and opp, and we can still get valid C code without this.

**Comment by jadephilipoom** [comment]
Yes, I agree we should make a new carrying addition/subtraction definition--reusing compact should work in theory, but in practice is awkward. I will aim to produce code like this:

```
dlet x0 := Z.add_get_carry_full 0 a0 b0 in
dlet x1 := Z.add_get_carry_full (fst x0) a1 b1 in
dlet x2 := Z.add_get_carry_full (fst x1) a2 b2 in
dlet x3 := Z.add_get_carry_full (fst x2) a3 b3 in
(fst x3, (snd x3, snd x2, snd x1, snd x0))
```

Of course, for subtraction the `Z.add_get_carry_full` would be replaced with some equivalent operation for subtract. @JasonGross Is this the correct goal?

I also will prioritize #219 first.

**Comment by JasonGross** [comment]
@jadephilipoom yes, though feel free to reuse `Z.add_get_carry_full` for subtract if that makes things easier; rewriting adc to sbb is not hard, and the code is already there and at least somewhat robust.

**Comment by JasonGross** [comment]
This will be obsoleted by #226.

**Comment by JasonGross** [comment]
We should consider disabling the adc-fusion optimization by default now that it's unused.
