### ISSUE TITLE
change notation `_ == _ ? _ : _ ` to `cmovznz(_, _, _)`

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#228]
change notation `_ == _ ? _ : _ ` to `cmovznz(_, _, _)` so we can stub it out with assembly code or something to guarantee that it produces constant-time code

**Comment by JasonGross** [comment]
I assume you want `a == 0 ? x : y` to be `cmovznz(a, x, y)` and not some other order?
