### ISSUE TITLE
Proving admits about new add/sub chains

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#232]
There are some admits in the new code I pushed that would be suitable for someone who is not me to do, so I'm dumping the info here in case anyone has some free time. If not I'll probably get to them sometime over the weekend or early next week.

The admits are all in `Arithmetic/Saturated/AddSub.v`. I have currently defined one carrying-loop operation and defined `add` and `sub` by plugging in the relevant `Z.add_get_carry` and `Z.sub_get_borrow` operations. It might work to prove the carrying loop correct with the generic operation, and that would be best in terms of proof repetition, but if it doesn't work out I'm not opposed to specializing into two proofs.

Some of the logic in `Arithmetic/Saturated/Core.v` is similar, and may be helpful. In particular, you will probably want some version of this lemma:
https://github.com/mit-plv/fiat-crypto/blob/2876f7c688590a64189f47b439f7edf26c91c5de/src/Arithmetic/Saturated/Core.v#L246

**Comment by andres-erbsen** [comment]
I think this was 5ee86c875e65f362f20a3a5443d8414edb5406c9
