### ISSUE TITLE
25519 freeze status?

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#244]
Did we ever generate runnable C code for 25519 freeze? If so, what happened to it. If not, why?

**Comment by JasonGross** [comment]
I think all that's missing is Makefile targets to convert IntegrationTestFreezeDisplay.log, in the root of Specific/, into c.  Idk why IntegrationTest{Freeze,Sub,Add} didn't get moved into the X25519 folder when the reorganization happened.

**Comment by andres-erbsen** [comment]
Okay, in that case I think we are blocked on implementing `subborrow_u51`. I don't know what is the best place to do that.

Regardless, the files should probably just get moved.

**Comment by JasonGross** [comment]
#248 moves the files (and generates them)

**Comment by andres-erbsen** [comment]
https://github.com/mit-plv/fiat-crypto/tree/divmod is my attempt at getting rid of `subborrow_u51` by unfolding it and then using the reflective rewriter to do `mod` -> `&`, `div` -> `>>`.

**Comment by andres-erbsen** [comment]
@jadephilipoom `freeze` seems to use columnwise operations (add, sub) right now. I think you implemented row-wise operations for montgomery stuff. Could you switch freeze to use row-wise operations?

**Comment by JasonGross** [comment]
Why do you want the reflective rewriter to do that?  Can't you stuff the conversion to bitwise earlier?  We already know that we're only using powers of 2.

Anyway, if you want the reflective rewriter to handle it, just add a rule to the arithmetic simplifier that says that sbb goes to shift and land or whatever, since, again, we parameterize on log2 of the modulus.

**Comment by andres-erbsen** [comment]
mostly because handling it early is a pain, and i think it would not be using the reflective rewriter. and the rewrite bit is actually easy i think, the question is what to do about bounds analysis... but bounds of modulus should work, i think

**Comment by JasonGross** [comment]
Should we close this now, or leave it open until we fix subborrow_u51?

**Comment by andres-erbsen** [comment]
It is unclear how we could fix subborrow_u51, so let's deal with that separately.
