### ISSUE TITLE
Moving to requiring Coq 8.7

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#255]
I would like to move to requiring Coq 8.7 within the next few days, so that I can merge #248 (whence I will also merge #198, and #168, assuming I can get travis to pass them).  (The feature that 8.7 adds that is relevant is `transparent_abstract`.)  I plan to make the transition when Coq 8.7 (stable) is released, which should, conveniently, happen within the next few days.  I maintain [debian packages for various versions of Coq on launchpad](https://launchpad.net/~jgross-h/+archive/ubuntu/many-coq-versions), and will package Coq 8.7 before moving to it.  (It will also be available from source, and on opam.)  If you have any objections to this, please voice them soon.

cc @jadephilipoom @achlipala @andres-erbsen (am I missing anyone here?)

**Comment by achlipala** [comment]
Sounds good to me.  I don't think we should make our research lives much harder, just to simplify installation for hypothetical users in the period of about 2 years before Coq updates propagate into stable OS distributions.

**Comment by andres-erbsen** [comment]
I guess this is happening then.

Instructions for Arch Linux:
1. install `camlp5` from AUR.
2. Run this `PKGBUILD` https://gist.github.com/andres-erbsen/2cd0a211f7a900eafbf84ba60d986033 and watch it fail
3. Manually apply https://github.com/coq/coq/pull/1152/files to `src/coq`
4. `makepkg -e`

Hopefully the Coq patch here will make it into 8.7. I also contacted the Arch packagers of `calmp5` and `coq` to figure out whether we can continue having prebuilt packages for latest coq (i.e., can `camlp5` be made into a prebuilt package).

On Debian, coq 8.7 can be built from source with all dependencies installed using apt.

**Comment by achlipala** [comment]
I actually never install Coq from OS packages in Debian/Ubuntu.  I always do what you wrote: install dependencies with `apt` and then build from source.
