### ISSUE TITLE
Fiat-crypto light target takes too long again

### ISSUE THREAD

**Issue by Zimmi48** [mit-plv/fiat-crypto#262]
3 out of 6 recent PR builds failed because fiat-crypto timed out:
https://travis-ci.org/coq/coq/builds/292572657
https://travis-ci.org/coq/coq/builds/292319973
https://travis-ci.org/coq/coq/builds/292176758
This is likely due to the commits that were pushed yesterday because this wasn't happening before.

**Comment by JasonGross** [comment]
Ugh, really?  I'll go remove the files in `src/Specific/NISTP256/AMD128` from lite and hope that fixes it, but I think Coq could also fix the issue by fixing https://github.com/coq/coq/issues/5988.  The files I added yesterday aren't really that slow.

**Comment by Zimmi48** [comment]
Sure performance improvement is a better longer-term solution ;-)
I guess fiat-crypto was already close to the limit and these files make it take a bit too long from time to time.
