### ISSUE TITLE
Output generated `Specific` code to a file

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#28]
It would be nice to have `make` create files with the generated specific code in them (and then `cat` those files at the end of the Travis build). We will eventually be generating qhasm code, currently most of `Specific/` goes down to `Z` expressions. I don't know how much the process for outputing stuff depends on what is being output, so it may make sense to punt this for a while.

**Comment by JasonGross** [comment]
The commands I know about to output things are `Print`, `About`, `Check`, `idtac`, `Extraction`, `Extraction Library`, `Recursive Extraction`.

@andres-erbsen Do you actually want a command that prints it to a file, or can you just have a `.v` file with a `Print` in it, and a makefile target that redirects the output to a file?

@cpitclaudel do you know about redirecting output to files with commands?  Is there a command to do this for anything other than `Extraction`?

**Comment by andres-erbsen** [comment]
A `Print` plus a redirect in the Makefile would be fine by me -- I just don't want to see the output every time I build.

**Comment by JasonGross** [comment]
Okay, that's what you should do then.  Make a .v file with just the import and the `Check` or `Print` or `Eval cbv` or whatever, and I can add some makefile magic to exclude it from the default target, when I fix #27.

**Comment by cpitclaudel** [comment]
What about `Redirect`? I added it a while ago.

```
6.8.4  Redirect "file" command.

This command executes the vernacular command command, redirecting its output to “file.out”.
```

**Comment by andres-erbsen** [comment]
We will be using Redirect.
