### ISSUE TITLE
carry without cps

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#283]
In the simplified arithmetic experiment, we want carry without cps, to cpsify in reflective land.

**Comment by jadephilipoom** [comment]
I implemented `carry` without CPS; note that we have been using a wrapper called `chained_carries`, which does a whole sequence, in the current pipeline. Do you need `chained_carries` also, or will the new pipeline look sufficiently different that it is not necessary?

**Comment by JasonGross** [comment]
Thanks!  I am not sure how the primes -> curve parameters part will look in the new pipeline, but I will still need to start from a single function which does all the carrying that is necessary to do on the output of `mul`.  Does that answer your question?

**Comment by jadephilipoom** [comment]
Yes, that means you need `chained_carries`. I'll take care of it.

**Comment by JasonGross** [comment]
Thanks!

**Comment by JasonGross** [comment]
@jadephilipoom We have been using `list (list nat)` for carry chains.  Does `chained_carries` do the right thing if I flatten these lists, or is there something special I have to do at boundaries?
