### ISSUE TITLE
Align/combine solinas{32,64}_2e255m19_{10,5}limbs and X25519/C{32,64}

### ISSUE THREAD

**Issue by davidben** [mit-plv/fiat-crypto#294]
@JasonGross @andres-erbsen 

I started trying to adapt the 51-bit limb schedule for BoringSSL, as that's a considerable perf win. Things I found:

* The solinas* versions are missing an fecarry implementation.
* The X25519/C{32,64} versions are missing C files and also include said C files in .gitignore, which makes them a little harder to use.
* The X25519/C{32,64} versions don't seem to emit quite the same code as the solinas* versions. The input and output are funny and there's some surrounding bits.
* I gather the C{32,64} versions are nominally the same, but have some manual instruction scheduling borrowed from an curve25519-donna, unlike the solinas* versions which are purely automated? I ran some benchmarks. It appears that C32 vs solinas32* doesn't make any difference, but C64 is about 16% faster than solinas64*.

This suggests the C32 version isn't very useful, but the C64 one is. I'm not sure how you all prefer to organize it, either fold the manual scheduling of C64 into solinas64*, or keep having two of them around? Either way, it would be nice for fecarry to be easily available and for the C code to be like the solinas* one in whichever instances are ultimately supported.

**Comment by JasonGross** [comment]
@davidben I've added fecarry for all the solinas implementations in a4789ec72a32b6d3b1d40154626e8c6674d4aa7d.  Feel free to make the `*Display.log` and `*.c` files that you need and add them. 

x25519_c64 and x25519_c32 both have manually specified replacement C code (which is parsed into Coq) in the .json files:
https://github.com/mit-plv/fiat-crypto/blob/a4789ec72a32b6d3b1d40154626e8c6674d4aa7d/src/Specific/CurveParameters/x25519_c64.json#L12-L73

I don't see a way to add that to the fully-autogenerated versions, which generate everything based on just the prime number.

Currently, the method we use to go from the display logs to the C code is different for X25519/* vs solinas*.  The former uses a different method of benchmarking, etc, and also has as test binary.   The easiest, most kludgy thing to do is to add variants of `solinas64_2e255m19_*limbs.json` which mention donna and have the hand-crafted C code.  I've done this in #295.  Perhaps it makes more sense to unify the two ways we have of benchmarking, though. @andres-erbsen what do you think?

**Comment by davidben** [comment]
Thanks!

Huh, that's hilarious. I didn't realize you all specified the input as C. So hand-written C code gets parsed into Coq with integer sizes widened to infinity, prove it correct, re-derive integer sizes, and then spit back out vaguely similar C code? :-)

**Comment by JasonGross** [comment]
> Huh, that's hilarious. I didn't realize you all specified the input as C. So hand-written C code gets parsed into Coq with integer sizes widened to infinity, prove it correct, re-derive integer sizes, and then spit back out vaguely similar C code?

Yep.  It's kind-of silly.  There's even a bit of preprocessing in Python to turn it into stuff that Coq can parse:
https://github.com/mit-plv/fiat-crypto/blob/a4789ec72a32b6d3b1d40154626e8c6674d4aa7d/src/Specific/X25519/C64/CurveParameters.v#L27-L47

**Comment by JasonGross** [comment]
@andres-erbsen this is now outdated given the new pipeline, right?
