### ISSUE TITLE
.dir-locals.el for COQPATH

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#31]
We should have a `.dir-locals.el` that sets `COQPATH`, so we don't have to set it in emacs.  Preferably, we should have a target in the makefile that makes it based on which version of coq is in `COQBIN`.  Maybe something like (untested):
```makefile
ifneq ($(filter 8.4%,$(COQ_VERSION)),) # 8.4
COQPRIME_FOLDER := coqprime-8.4
else
COQPRIME_FODLER := coqprime
endif

.dir-locals.el::
	sed 's:@COQPRIME@:$(COQPRIME_FOLDER):g' .dir-locals.el.in > $@
```
with `.dir-locals.el.in` being
```elisp
((coq-mode . ((eval . (let ((default-directory (locate-dominating-file
                                                buffer-file-name ".dir-locals.el"))
                             (cur-COQPATH (getenv "COQPATH")))
                        (setenv "COQPATH" (concat (expand-file-name "@COQPRIME@") (if (string= "" cur-COQPATH) "" (concat ":" cur-COQPATH))))))))
```

(@cpitclaudel might have useful input here)

**Comment by andres-erbsen** [comment]
How would this interact with [Emacs Safe Variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Safe-File-Variables.html)?

**Comment by cpitclaudel** [comment]
You'd accept it the first time you run it.

I suggested the following to Jason by email:
```elisp
    (let* ((project-root (locate-dominating-file buffer-file-name "_CoqProject"))
           (coqprime-folder (expand-file-name "coqprime" project-root))
           (coq-path (split-string (or (getenv "COQPATH") "") ":" t)))
      (unless (memql coqprime-folder coq-path)
        (setenv "COQPATH" (mapconcat #'identity coq-path ":"))))
```

**Comment by andres-erbsen** [comment]
I wouldn't use this, but I don't object. Generating emacs lisp files from Makefile sounds like a hack, but if it really would be overly cumbersome to detect the Coq version in elisp then I guess the Makefile will have to do. All that to save the 50 characters of `COQPATH="$(pwd)/coqprime${COQPATH:+:}$COQPATH"
`...

**Comment by JasonGross** [comment]
I don't mind typing the characters, but it's rather hard when I'm trying to launch emacs from not-the-command-line :P

**Comment by JasonGross** [comment]
I want to autobind COQPATH to different values depending on whether `coqc --version` says `Coq 8.4*` or something else, because we have `coqprime-8.4` (8.4 only) and `coqprime` (>= 8.5).

**Comment by JasonGross** [comment]
@cpitclaudel did you mean `(cons coqprime-folder coq-path)` in the last line?

**Comment by cpitclaudel** [comment]
Yes, absolutely.
