### ISSUE TITLE
fiat-crypto has been failing on Coq Jenkins for 2 months

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#344]
(from https://github.com/coq/coq/issues/7188)

There seems to be a good mix of different reasons, many of which look like resource limit issues.

Example failure:
https://ci.inria.fr/coq/job/opam-install-coq-fiat-crypto/653/consoleFull
~~~~~~~~~~~~
- "coqc"  -q   -w "-notation-overridden"  src/Specific/X25519/C64/fecarryDisplay.v | sed s'/\r\n/\n/g' > src/Specific/X25519/C64/fecarryDisplay.log.tmp && mv -f src/Specific/X25519/C64/fecarryDisplay.log.tmp src/Specific/X25519/C64/fecarryDisplay.log
- "coqc"  -q   -w "-notation-overridden"  src/Specific/X25519/C64/feaddDisplay.v | sed s'/\r\n/\n/g' > src/Specific/X25519/C64/feaddDisplay.log.tmp && mv -f src/Specific/X25519/C64/feaddDisplay.log.tmp src/Specific/X25519/C64/feaddDisplay.log
- "coqc"  -q   -w "-notation-overridden"  src/Specific/X25519/C64/fesubDisplay.v | sed s'/\r\n/\n/g' > src/Specific/X25519/C64/fesubDisplay.log.tmp && mv -f src/Specific/X25519/C64/fesubDisplay.log.tmp src/Specific/X25519/C64/fesubDisplay.log
- "coqc"  -q   -w "-notation-overridden"  src/Specific/NISTP256/AMD64/fesubDisplay.v | sed s'/\r\n/\n/g' > src/Specific/NISTP256/AMD64/fesubDisplay.log.tmp && mv -f src/Specific/NISTP256/AMD64/fesubDisplay.log.tmp src/Specific/NISTP256/AMD64/fesubDisplay.log
- File "./src/Specific/NISTP256/AMD64/fesubDisplay.v", line 1, characters 15-51:
- Error:
- Cannot find a physical path bound to logical path matching suffix
- Crypto.Specific.NISTP256.AMD64.
- 
- File "./src/Specific/X25519/C64/fesubDisplay.v", line 1, characters 15-47:
- Error:
- Cannot find a physical path bound to logical path matching suffix
- Crypto.Specific.X25519.C64.
- 
- File "./src/Specific/X25519/C64/fecarryDisplay.v", line 1, characters 15-49:
- Error:
- Cannot find a physical path bound to logical path matching suffix
- Crypto.Specific.X25519.C64.
- 
- File "./src/Specific/X25519/C64/feaddDisplay.v", line 1, characters 15-47:
- Error:
- Cannot find a physical path bound to logical path matching suffix
- Crypto.Specific.X25519.C64.
~~~~~~~~~~~~

**Comment by JasonGross** [comment]
@SkySkimmer That's a very good question.  The difference between the two calls is that the ones that do get the `-R` flags are invoked by depending on `.vo` rules from a `coq_makefile`-generated `Makefile.coq`, while the ones that don't get invoked with the rule
```
$(HIDE)$(TIMER) $(COQC) $(COQDEBUG) $(COQFLAGS) $< | sed s'/\r\n/\n/g' > $@.tmp && mv -f $@.tmp $@
```
after a `-include Makefile.coq` ...

**Comment by JasonGross** [comment]
Ah, I think I figured that bit out; it was broken by https://github.com/coq/coq/pull/7025 , and I'm not sure what a backwards compatible way of fixing this is.

**Comment by SkySkimmer** [comment]
I think if you just add $(COQLIBS) to the command it will be OK, 
repeating -R/-Q/-I doesn't seem to cause errors.

Gaëtan Gilbert

**Comment by JasonGross** [comment]
I'll push a change to fix this, and to test it on Coq's ci moving forward, but note that this won't fully fix the build on Jenkins.  e.g., there's still https://ci.inria.fr/coq/job/opam-install-coq-fiat-crypto/637/console
```
- File "./src/Curves/Weierstrass/AffineProofs.v", line 48, characters 6-59:
- Error:
- Anomaly
- "Uncaught exception Failure("The spawned process did not connect back in 2.0s")."
- Please report at http://coq.inria.fr/bugs/.
```

The first failure that I can find is https://ci.inria.fr/coq/job/opam-install-coq-fiat-crypto/533/console, which does not seem to have a useful log.

**Comment by JasonGross** [comment]
The next issue seems to be a combination of the fact that the `coqprime` target doesn't build all of the `coqprime` files, and so `install-coqprime` fails, and that we don't build all of the files that we try to install.  I can fix this by adding a `coqprime-all` target to build all of `coqprime`, and also fixing the `install` target to only install the files we build...
