### ISSUE TITLE
need help: C-code for P-521 64-bit mont mul

### ISSUE THREAD

**Issue by 0x64616E69656C** [mit-plv/fiat-crypto#346]
Hi,

I am able to create the C code for ```feopp``` and ```fesub``` in ```src/Specific/montgomery64_2e521m1_9limbs/```, which takes a few hours and about 4% of memory constantly, however I'm running out of memory (24GB) with ```femul.c```.

Does anyone by any chance have an already generated ```femul.c``` and ```femulDisplay.log``` lying around?

Thanks!

**Comment by JasonGross** [comment]
Here is `femulDisplay.log` is a slightly different format: https://github.com/JasonGross/fiat-crypto/blob/wip-no-reification/src/Specific/montgomery64_2e521m1_9limbs/femulDisplay.log
and here is `femul.c` generated from that log using a `prettyprint.py` which can handle that format: https://github.com/JasonGross/fiat-crypto/blob/wip-no-reification/src/Specific/montgomery64_2e521m1_9limbs/femul.c

Note that these were generated with a slight variant of the pipeline, which did not have complete proofs associated with it, so it's possible that a bug slipped in somewhere (though much of it was proven).  (The alternate pipeline was the forerunner to the update we're currently working on.  It was already faster and less memory hungry (but was a pain to prove things about).)

**Comment by 0x64616E69656C** [comment]
Thanks, that should help! 👍
