### ISSUE TITLE
Fiat-Crypto should support building with an external coqprime

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#363]
Currently, we necessarily depend on on the pinned version of coqprime, and we try to install it when we install things.  For the sake of modularity on opam, we should probably have a makefile flag that disables building of the local version of coqprime, and makes `COQPATH` not include `coqprime`.

**Comment by andres-erbsen** [comment]
I think having a Makefile variable to use external coqprime is reasonable, but I don't think we should try to support it beyond making sure the way we try to access external coqprime is within standard practice of coq projects.
