### ISSUE TITLE
Broken on Coq master

### ISSUE THREAD

**Issue by SkySkimmer** [mit-plv/fiat-crypto#379]
Fiat says: https://ci.inria.fr/coq/job/benchmark-part-of-the-branch/ws/448/coq-fiat-crypto.NEW.opam_install.1.stdout/*view*/
~~~
- File "./src/Coqprime/elliptic/GZnZ.v", line 152, characters 4-5:
- Error:
- Syntax error: [prim:ident] expected after 'fix' (in [tactic:simple_tactic]).
~~~
(see coq/coq#7196)

**Comment by JasonGross** [comment]
This is probably because opam builds more of coqprime than Travis, because of the requirement to install.  Anyway, this is a bug in coqprime (which should maybe be independently added to Travis?).  If the issue is fixed there, we can bump the submodule
