### ISSUE TITLE
The notation "O :( A , B ): :?: L ::: R" breaks ((1):nat) and constr:()

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#39]
This is why we should reserve all notations in `Notations.v`.  I'm going through and doing this now, and will, for now, just add spaces so that `):T` becomes `) : T`, but we should think about changing this notation.

**Comment by JasonGross** [comment]
Ugh, this also breaks the ltac `constr:(foo)`.  Please change the notation to something reasonable, which doesn't include any frowny faces (nor smiley faces).

**Comment by andres-erbsen** [comment]
Fixed in #47 (reopen if I'm incorrect).
