### ISSUE TITLE
make: execvp: /bin/sh: Argument list too long

### ISSUE THREAD

**Issue by samuelgruetter** [mit-plv/fiat-crypto#420]
If I try to build current master (29f1c8b447294b4a0a6a5127c6db23d54d43343f), which does build on travis, on my machine, I get this:

```
make -j printlite lite
COQ_MAKEFILE -f _CoqProject > Makefile.coq
make: execvp: /bin/sh: Argument list too long
make: execvp: /bin/sh: Argument list too long
make: execvp: /bin/sh: Argument list too long
COQDEP VFILES
*** Warning: in file src/Util/NumTheoryUtil.v, library Coqprime.PrimalityTest.Euler is required and has not been found in the loadpath!
*** Warning: in file src/Util/NumTheoryUtil.v, library Coqprime.PrimalityTest.Zp is required and has not been found in the loadpath!
...
```

and after a while, `make` seems to hang (no CPU usage, but it doesn't return either).

I tried increasing `ulimit -s` (which is 8192 on my machine) to 65536, but that didn't help.

**Comment by JasonGross** [comment]
This is https://github.com/coq/coq/issues/7584.  `make` should work fine, but `make install` will not.  If `make` hangs, that's a separate issue...
