### ISSUE TITLE
cbv on F.of_Z is very slow

### ISSUE THREAD

**Issue by samuelgruetter** [mit-plv/fiat-crypto#421]
If I add the following at the end of the file [src/Spec/ModularArithmetic.v](https://github.com/mit-plv/fiat-crypto/blob/master/src/Spec/ModularArithmetic.v)

```
Definition x: F (2 ^ 16) := F.of_Z (2 ^ 16) (-3).
```

and do

```
Eval cbv in (F.to_Z x).
```

it finishes immediately, and prints `65533`, as expected.

However, if I do

```
Time Eval cbv in x.
```

which seems to be "less computation", it takes 26.994 secs, and prints a term of the form

```
exist HUGE_TERM 65533 (ModularArithmeticPre.Z_mod_mod (-3) 65536)
```

I'm considering whether I should replace types such as `bbv.Word 16` by something like `F (2 ^ 16)`, which requires that computing on words and printing words is fast, so I wonder if you ran into this problem too, and if so, what you did about it.

**Comment by andres-erbsen** [comment]
If https://github.com/coq/coq/issues/7159 happened we could make this work; currently your best bet is to never compute values of type `F` (instead compute `F.to_Z` of that value).

**Comment by JasonGross** [comment]
Note that if we made `F` a custom record rather than a sigma type, this problem would go away.

**Comment by andres-erbsen** [comment]
it would still reduce the proofs, no?

**Comment by samuelgruetter** [comment]
This is awesome! I just implemented it here: https://github.com/mit-plv/riscv-coq/commit/7b7867d56ed6bd5869f39d3cdb4ca86749568a1c

And if I use this implementation in my compiler, and do `Eval cbv in fib6_bits.`, where `fib6_bits` are the bits produced by the compiler for the fibonacci program, I get something like this:

```
     = [{| word_val := 659; word_mod := eq_refl |};
       {| word_val := 8557203; word_mod := eq_refl |};
       {| word_val := 164499; word_mod := eq_refl |};
       ... ]
     : list word
```

rather than a seemingly infinite computation.
(Of course this also worked with bbv word, but it did not work with sigma type word).
