### ISSUE TITLE
make is slow in "make no-curves-proofs-non-specific"

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#444]
like a minute or so of `make` spinning at 100% cpu.

**Comment by JasonGross** [comment]
This is possibly the same issue as @maximedenes was commenting to me about on gitter the other day, where we're doing something like topological sort with `sed` and `grep` in the Makefile to calculate the list of everything which depends on any file that we're excluding, and we're doing it separately for each file we exclude.
