### ISSUE TITLE
NewPipeline Arithmetic: partition vs encode

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#468]
@jadephilipoom  Why do both `partition` and `encode` exist? Is there actually a need for both variants, or can we get rid of one of them? Oh, and there is also `recursive_partition`...

**Comment by jadephilipoom** [comment]
`encode` is redundant, and should be changed to use `partition`. It's just older and was there before `partition` existed. However, `recursive_partition` is useful -- it's equivalent to `partition` but works from the head of the list, so it's better for proofs that do induction on the list. It should only be used in proofs.
