### ISSUE TITLE
refactoring: new pipeline becomes default

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#475]
As @JasonGross just finished proofs for the `Experiments/NewPipeline` support for Solinas reduction and word-by-word Montgomery reduction, I am tempted to move this code out of the `Experiments` directory into the spotlight of this repository. I think this would also be a major cleanup. I would do this tomorrow, or the day after, or something like that.

This will likely interfere with work in all branches. I am discarding all of mine. If you have branches you care about maintaining, please say so here and we will figure something out. @JasonGross @jadephilipoom 

Currently, the plan is to

~~~
keep: Algebra, Curves, Util, Primitives, Spec, Demo.v, Arithmetic/*Theorems.v
delete: measurements, Specific, Compilers, Arithmetic, benchmarking stuff, expansion.md, regenerate-curves.sh, register-allocate.py, synthesis-parameters.txt, optimizations.md, failures.txt, extract-*.sh, third_party, liblow, Experiments/*.v, LegacyArithmetic
promote: Experiments/NewPipeline/* to toplevel
otherwise move: checked-in generated c code, measure.c to etc
~~~

later we would most likely to git-restore: benchmarking stuff (although BoringSSL benchmarks also work), third_party(?), 

TODO:

[ ] what to do with Arithmetic/BarrettReduction? is it superseded?
[ ] Arithmetic.Saturated?
[ ] how to deal with not-yet-ready stuff in the new pipeline -- FancyMachine and Barrett?

**Comment by JasonGross** [comment]
What do we want to do with the legacy pipeline for Coq's CI?  Do we want to branch?  Or migrate to coq-community?

> Arithmetic/BarrettReduction
We `Require Import Crypto.Arithmetic.BarrettReduction.Generalized.` for the Barrett stuff in the new pipeline.  Similarly with the MontgomeryReduction stuff there.

**Comment by andres-erbsen** [comment]
I'm thinking something like the current master will remain as a branch.

**Comment by JasonGross** [comment]
We should make sure to update Coq's CI before we change master.  Things to do:
- make a section like https://github.com/coq/coq/blob/0a5bbf347b5bbcb579f94eb3d0166778cd92cfdb/dev/ci/ci-basic-overlay.sh#L145-L150 for fiat-crypto-legacy
- update https://github.com/coq/coq/blob/master/dev/ci/ci-fiat-crypto-legacy.sh to use the alternative branch
- make sure that we don't break any targets of https://github.com/coq/coq/blob/master/dev/ci/ci-fiat-crypto.sh / that we update said targets

**Comment by andres-erbsen** [comment]
IIUC, we will be merging branches [fix_fancy3](https://github.com/mit-plv/fiat-crypto/tree/fix_fancy3) and [better-glue](https://github.com/JasonGross/fiat-crypto/tree/better-glue) before this refactor.

**Comment by JasonGross** [comment]
Is fix_fancy3 going to be ready by the time you want to refactor?  Also, we will be merging #474, which is also the first commit in better-glue.

**Comment by JasonGross** [comment]
(I hope to merge #474 tonight or tomorrow morning, as soon as travis passes it)

**Comment by andres-erbsen** [comment]
"fix_fancy3" is going to be "ready enough". Depending on what it looks like after the merge and refactor, we might branch it off again right after. Do you have any recommendation about which order to do the merges in?

**Comment by andres-erbsen** [comment]
`better-glue` has been merged, next step is to rebase fix_fancy. I seem to be going pretty slow on this.
