### ISSUE TITLE
Remove bbv dependency

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#481]
I think nothing in the pipeline depends on bbv stuff, so we should be able to remove wordutil and bbv now.

**Comment by andres-erbsen** [comment]
EdDSA still depends on bbv. It shouldn't. It would probably take a couple of hours to fix.

**Comment by bbarenblat** [comment]
It looks like the bbv `word` type is pretty integral to EdDSA. However, I can just delete

  - src/Primitives/EdDSARepChange.v
  - src/Spec/Ed25519.v
  - src/Spec/EdDSA.v

without breaking anything (`make all c-files` still passes). Is that code all obsolete?

**Comment by andres-erbsen** [comment]
The EdDSA code is orthogonal to the field arithmetic stuff, so yeah, I guess we can say it is obsolete. I do hope we will eventually revive it, but I don't think it is going to happen over the next couple of months.
