### ISSUE TITLE
MSVC warns on uint8_t >> 8.

### ISSUE THREAD

**Issue by davidben** [mit-plv/fiat-crypto#493]
When building fiat-generated code with MSVC, lines like the following trigger MSVC's warning C4333,
https://github.com/mit-plv/fiat-crypto/blob/master/p256_32.c#L3186
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4333?view=vs-2017

How hard would it be to add a pass to replace those lines with zero? It would probably trim the subsequent code too, if constant propagation and such is applied.

Aside: normally right-shifting an integer by all its bits is not only redundant but also UB because one cannot shift `(u)intN_t` by `N` bits, only up to `N-1`. However, integer promotion rules apply to shifts too, so this is merely redundant, not UB:

> The integer promotions are performed on each of the operands. The type of the result is
> that of the promoted left operand. If the value of the right operand is negative or is
> greater than or equal to the width of the promoted left operand, the behavior is undefined.

**Comment by davidben** [comment]
Okay, it's these lines:
https://github.com/mit-plv/fiat-crypto/blob/master/p256_32.c#L3188
https://github.com/mit-plv/fiat-crypto/blob/master/p256_32.c#L3197
https://github.com/mit-plv/fiat-crypto/blob/master/p256_32.c#L3206
https://github.com/mit-plv/fiat-crypto/blob/master/p256_32.c#L3215
https://github.com/mit-plv/fiat-crypto/blob/master/p256_32.c#L3224
https://github.com/mit-plv/fiat-crypto/blob/master/p256_32.c#L3233
https://github.com/mit-plv/fiat-crypto/blob/master/p256_32.c#L3242

Otherwise, I think what I wrote is accurate.

**Comment by davidben** [comment]
Oh, I see. It's giving `fiat_p256_uint1` just because it's having to round up `[0x0 ~> 0x0]` to an integer size. That should work. Doing constant propagation from there would be nice, but one hopes the C compiler can do that too. (`x24` would disappear, then `x26` would disappear into `x6`.)

**Comment by JasonGross** [comment]
It'll do constant propagation from there, too
