### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#504]
We have [20 branches](https://github.com/mit-plv/fiat-crypto/branches).  We probably don't need all of them, such as `fancy_cleanup-makefile-fix`.  I think we should delete the ones we definitely don't need.

We should definitely not delete
- master
- sp2019latest
- v8.6
We should probably not delete branches with open PRs:
- poly1305

Of the branches last touched by me:
- protocols - I vote we keep this one, it has potentially interesting (if very outdated-ish) work
- [sqrt_bounds](https://github.com/mit-plv/fiat-crypto/compare/sqrt_bounds) - I think we can delete this one, thought @jadephilipoom or @andres-erbsen should confirm; the first couple of commits are by @jadephilipoom , then there are a bunch by me that I think are superseded by the new pipeline

**Comment by jadephilipoom** [comment]
Yes, we can get rid of `sqrt_bounds`. I went through the list and have the following categories:

Definitely keep:
- master
- bedrock-integration1
- bedrock2-integration
- poly1305 (the PR is still open -- will we ever merge it?)
- v8.6

Uncertain:
- karatsuba (probably won't ever be merged, has one file with a reasonably nice description of karatsuba multiplication)
- lattice (similar situation, probably won't be merged but has some bits we maybe don't want to delete forever)
- sp2019latest (it was in Jason's list originally, but the comment is many months old -- is it still needed?)
- loop-notation-please-report (is it worth reporting this bug given the branch is 2 years old?)
- x25519_c32_parenthesized (I don't know what's happening in this one)
- protocols (this one looks really outdated, probably delete, but I'm not sure)
- perf-testing-data-POPL-2020-rewriting (I imagine we still need this?)
 
Definitely delete:
- fancy_proofs2
- fancy_proofs
- fancy
- fix_fancy3
- fix_fancy2
- wbw_admits
- sqrt_bounds
- generalize_barrett
- generalize
- straightline_proofs
- fancy_cleanup-makefile-fix
- mac32

If no one objects in the next couple of days, I'll consider myself free to remove the ones in the "definitely delete" list.

**Comment by JasonGross** [comment]
I think we want to keep 
- sp2019latest
- perf-testing-data-POPL-2020-rewriting

basically forever, because we have papers which either reference these branches or are based on data from these branches.  Also, Coq's CI uses sp2019latest for fiat-crypto-legacy; if we ever delete sp2019latest, it should be because we've extracted it to its own repository.

I've deleted x25519_c32_parenthesized; it was modifying the very old way of printing C code to parenthesize more things.  If we want more parenthetisation, we will want to do it a different way, now.

I'm not sure about protocols; @andres-erbsen , what do you think?  (This is the branch where we were playing with protocol-level things way back when.)

**Comment by jadephilipoom** [comment]
I removed all the "definitely delete" ones, so we're now down to 13 from 25. The 13 are:
- master
- bedrock-integration1 (active)
- bedrock2-integration (active)
- poly1305 (open PR)
- v8.6
- v8.8
- sp2019latest (referenced by paper)
- perf-testing-data-POPL-2020-rewriting (referenced by paper)
- karatsuba (not using but maybe don't want to delete)
- lattice (not using but maybe don't want to delete)
- loop-notation-please-report (???)
- protocols (???)

I think it would be good to either come up with a decent justification for the last two or delete them, and then I would consider this issue closed.

**Comment by JasonGross** [comment]
I think @andres-erbsen should decide for `loop-notation-please-report` (I'm willing to spin up my bug minimizer if that's what needs to be done for that?).  I want to hear @andres-erbsen 's thoughts on protocols before making a decision on it, though I'm inclined to keep it here or at least dump the code in a gist somewhere and put a link to it here.  (I think making a gist of the 9 files that were added in that branch (there was no modification of existing code except `_CoqProject`), either with or without version history, and linking to the gist here, would be enough for me to lean towards deleting the branch.)

**Comment by andres-erbsen** [comment]
I had forgotten about that branch. I would be happy with bug minimizer + delete, or just delete.

**Comment by jadephilipoom** [comment]
I put all files from the protocols branch into a gist, along with the `git log --stat` printout up to and including the earliest commit that's in master: https://gist.github.com/jadephilipoom/d95b83b1071f7e2ce7f69132b30d5931

I'll assume I can delete both `protocols` and `loop_notation_please_report`, and close this issue, unless someone objects in the next 2-3 days.
