### ISSUE TITLE
Abstraction level of bounded

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#51]
Currently `bounded` is defined for `limb_widths` in `Pow2Base`.  It seems like it'd be more natural in `BaseSystem`.  Is there any reason not to move it (and `upper_bound`) there?

**Comment by jadephilipoom** [comment]
Discussed with Jason offline--the summary is that I think of `bounded` and `upper_bound` as maximum numbers of bits, not maximum integer values, so the `Pow2Base` layer makes the most sense. But Jason thinks of them as maximum integer values, for which `BaseSystem` makes more sense. I have no objection to their being moved as long as the lemmas about them remain intact.

**Comment by JasonGross** [comment]
I'm going to close this, since @jadephilipoom answered the question, and it's no longer useful in the path to Montgomery reduction on the fancy machine.
