### ISSUE TITLE
Remove fancy Admitted

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#522]
https://github.com/mit-plv/fiat-crypto/blob/b06d11d9e12cae00475e8f9a5f69d42cf34ae729/src/RewriterRulesInterpGood.v#L787

I'm not sure how this `Admitted` made it back into the codebase; I'm pretty sure I fixed it...

**Comment by JasonGross** [comment]
@jadephilipoom is this done?

**Comment by JasonGross** [comment]
This has been fixed

**Comment by 812-946-3407** [comment]
You have stolen my identity and I'm going to the police so either get all your s*** out of my fucken emails at off of my phone or you're going down!
