### ISSUE TITLE
fiat-crypto-legacy opam package broken

### ISSUE THREAD

**Issue by SkySkimmer** [mit-plv/fiat-crypto#548]
ie one of the packages used by the bench system for Coq
Log: [coq-fiat-crypto-legacy.NEW.opam_install.1.stdout.txt](https://github.com/mit-plv/fiat-crypto/files/3163598/coq-fiat-crypto-legacy.NEW.opam_install.1.stdout.txt)
Maybe related to https://github.com/coq/coq/pull/9906

**Comment by JasonGross** [comment]
Should hopefully be fixed (by https://github.com/mit-plv/fiat-crypto/pull/550, in a kludgy way), now.
