### ISSUE TITLE
Split up ZUtil

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#56]
ZUtil is a bit slow to compile.  It'd be faster (on parallel machines) if we split it up into preliminaries (database creation, adding standard lemmas to them), theorems about `+` and `-`, theorems about `*`, theorems about `/`, theorems about `mod`, misc theorems/tactics, and ones that make use of the theorems in the aforementioned parts.  I might do this myself at some point soon.  The structure should probably be:

```
ZUtil/
  Core.v
  AddSub.v
  Mul.v
  Div.v
  Modulo.v
  Misc.v
ZUtil.v # exports the above
```

**Comment by andres-erbsen** [comment]
Closed due to inactivity.

**Comment by JasonGross** [comment]
I will note that this is still a thing that would be nice to do/fix.
