### ISSUE TITLE
#[inline]ing select generated fiat-rust functions

### ISSUE THREAD

**Issue by isislovecruft** [mit-plv/fiat-crypto#575]
Hi there!

I just watched a presentation by Zoe Paraskevopoulou on parts of the fiat-rust crate and its generated curve25519 Rust code, including some benchmarks comparing it against the [curve25519-dalek](https://github.com/dalek-cryptography/curve25519-dalek) code. Zoe mentioned that the generated Rust has some (~15-30%) overhead compared to our hand-written Rust. I'm not entirely sure as I've never written Coq before, but I think if there were a way to change the Coq code to output `#[inline(always)]` above select functions, the overhead could potentially be diminished. I believe the primary function you want this for is `fiat_25519_carry()`. Possibly better could be done if the output were modified to keep field element reduction as a distinct call (i.e. eliminating the similar behaviours from e.g. `fiat_25519_carry_mul()`, `fiat_25519_carry_square()`, etc.).

Thoughts? I'd be willing to help with patches if folks don't mind likely answering a bunch of noob questions about Coq.

**Comment by JasonGross** [comment]
Is there any reason to not inline all of the functions?  If you're willing to inline all of the functions, you could just have all functions emit the inline attribute (search for `pub fn` and add a bit to the string in front of that).  If you want a flag to inline all the functions, that's also not too hard to add (I can replace the `static : bool` with a record for options like it and include one for inline).  It's also possible to permit requesting that specific functions be inlined, but that's a bit harder.

You can also run the perf experiments by modifying the code by hand, before you try to change the Coq code.

I'm happy to answer Coq questions, though I expect it's not much work to make this change for either me or @zoep.  I estimate 5 minutes + compilation time for making all functions inline (maybe 30 minutes of time in front of the computer to make it, test it, submit the PR, etc).  The version where you can inline only certain functions I expect would take me about 90 +- 30 minutes to code up and test and submit as a PR.

**Comment by JasonGross** [comment]
(If there is in fact a performance gain and it's important to only inline some of the functions, I'm happy to make the change needed to allow that.)

**Comment by zoep** [comment]
Hi @isislovecruft! thank you so much for your remarks today. It's definitely an easy change to add the inline directive above some or all functions. I'll edit the code manually and run the benchmarks to get an idea of the perf gain as @JasonGross suggested, and I can submit a PR for the Rust code.

Also, I think that both Jason and I will be more than happy to help with Coq :).

**Comment by huitseeker** [comment]
I did a quick test of the curve benchmarks inlining, and that does improve things a bit.

## With Inlining 
Average:11.2484 13.8445 16.5414
( compiled with the *highly super duper inaccurate and misleading* command:
```
grep -e 'p = 0.0' results/benches/fiat-rust_u64_1.txt| sed -re 's/ *change: \[(.*?)\].*/\1/g'| awk '{ sum1+=$1; sum2+=$2; sum3+=$3} END { print "Average:" sum1/ NR " "sum2/ NR " "sum3/ NR }' 
```
from https://gist.github.com/huitseeker/3cd26ea013483d697808edcaa0bfd960 )

## Without 
 Average:12.952 15.1472 17.4665
(same method, from
https://gist.github.com/huitseeker/a9a9de7bc4f6cde630992aeb68e8170a )

Next steps, select the few interesting ops from this computation and make this more relevant.
