### ISSUE TITLE
[coq] Please update the repository for Coq 8.12

### ISSUE THREAD

**Issue by ejgallego** [mit-plv/fiat-crypto#622]
c.f. https://github.com/coq/coq/pull/11158 

I tried to do it but found some problems.

On the long term it'd be great if we could avoid manual action, for example Compcert does work with unknown Coq versions but emits a warning.

**Comment by JasonGross** [comment]
Should be fixed by 6ae1d842759cbc5e2b4b9f86dc591b01c087d9fa, and https://github.com/mit-plv/rewriter/commit/f0886d99a54f5bd360070bfad3950c34faa6971f
