### ISSUE TITLE
when i building with make,there is a fatal error

### ISSUE THREAD

**Issue by l00519243** [mit-plv/fiat-crypto#624]
hi 
when i building with make, how can i solve it?
the processing:
COQC /home/kiran/l00519243/debugFiat/fiat-crypto/bedrock2/bedrock2/src/bedrock2/Semantics.v
COQC /home/kiran/l00519243/debugFiat/fiat-crypto/bedrock2/bedrock2/src/bedrock2/WeakestPrecondition.v
COQC /home/kiran/l00519243/debugFiat/fiat-crypto/bedrock2/bedrock2/src/bedrock2/WeakestPreconditionProperties.v
Fatal error: out of memory.
Makefile.coq.noex:658: recipe for target '/home/kiran/l00519243/debugFiat/fiat-crypto/bedrock2/bedrock2/src/bedrock2/WeakestPreconditionProperties.vo' failed
make[3]: *** [/home/kiran/l00519243/debugFiat/fiat-crypto/bedrock2/bedrock2/src/bedrock2/WeakestPreconditionProperties.vo] Error 2
Makefile.coq.noex:320: recipe for target 'all' failed
make[2]: *** [all] Error 2
Makefile:34: recipe for target 'noex' failed
make[1]: *** [noex] Error 2
make: *** No rule to make target 'bedrock2', needed by 'src/BoundsPipeline.vo'.  Stop.

**Comment by JasonGross** [comment]
How much RAM do you have on your machine?  In any case, you should report this at https://github.com/mit-plv/bedrock2/issues/new if you wish to use the parts of fiat-crypto that depend on bedrock2.

However, if you do not care about the parts that depend on bedrock2, you an run `make EXTERNAL_BEDROCK2=1 c-files` (or whatever target you want to build; I'm assuming you want C files).  Or you can run `make EXTERNAL_BEDROCK2=1 -k` to get all files (and to keep going after the ones that depend on bedrock2 fail).

**Comment by JasonGross** [comment]
Btw, if you want to see how much memory various files take, you can inspect the build logs (e.g., [this recent one](https://travis-ci.org/mit-plv/fiat-crypto/builds/626947854)), and see that `WeakestPreconditionProperties` takes 3257448 ko of mem (on v8.10).

Note that the next most expensive files, memory-wise, are `src/Rewriter/Rewriter/Wf` (1059804 ko) and `src/Rewriter/Rewriter/InterpProofs` (1058464 ko); everything else is under 1 GB of RAM.

**Comment by l00519243** [comment]
> uch RA

ok thanks for your guiding
