### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by AsmaaHailane** [mit-plv/fiat-crypto#643]
Hi i get this error, when i try to build the project:
Error: Error while running external preprocessor
Command line: /usr/bin/camlp5o -I /usr/lib/ocaml -I "/usr/lib/coq//grammar" pa_extend.cmo q_MLast.cmo pa_macro.cmo grammar.cma -loc loc -impl 'src/Rewriter/Util/plugins/inductive_from_elim_plugin.ml4' > /tmp/ocamlppea751339039fdb5bb0661b4d50c010a0

CAMLDEP -pp src/Rewriter/Util/plugins/definition_by_tactic_plugin.ml4
Error while loading "grammar.cma": file not found in path.
File "src/Rewriter/Util/plugins/definition_by_tactic_plugin.ml4", line 1:
Error: Error while running external preprocessor
Command line: /usr/bin/camlp5o -I /usr/lib/ocaml -I "/usr/lib/coq//grammar" pa_extend.cmo q_MLast.cmo pa_macro.cmo grammar.cma -loc loc -impl 'src/Rewriter/Util/plugins/definition_by_tactic_plugin.ml4' > /tmp/ocamlpp7c7d1b530f8b13880f244a2b06f3a272

CAMLC -c src/Rewriter/Util/plugins/strategy_tactic.mli
File "src/Rewriter/Util/plugins/strategy_tactic.mli", line 1, characters 39-54:
Error: Unbound module Names
make[2]: *** [Makefile.coq:595: src/Rewriter/Util/plugins/strategy_tactic.cmi] Error 2
make[1]: *** [Makefile.coq:327: all] Error 2
make: *** No rule to make target 'rewriter', needed by 'src/BoundsPipeline.vo'.  Stop.

**Comment by jadephilipoom** [comment]
When you cloned, did you clone the submodules? If not, run

git submodule update --init --recursive

**Comment by AsmaaHailane** [comment]
Thank you , Yes after cloning i did that but same errors after many times
trying to build the project. I’m using ubuntu 19 and the version for coq is
8.9 all the needed packages is here.

**Comment by JasonGross** [comment]
How did you install Coq?  If you installed it via `apt`, note that you will need `libcoq-ocaml-dev` and not just `coq`.

**Comment by AsmaaHailane** [comment]
Thank you again and  sorry for asking too much but i'm new with coq.
Now i have another error related to bedrock2 

make --no-print-directory -C rewriter
make[2]: Nothing to be done for 'real-all'.
make --no-print-directory -C bedrock2/deps/coqutil
Generating Makefile.coq.all
make -f Makefile.coq.all
make[3]: Nothing to be done for 'real-all'.
make --no-print-directory -C bedrock2/bedrock2 noex
Generating Makefile.coq.noex
rm -f .coqdeps.d
make -f Makefile.coq.noex
COQDEP VFILES
COQC /root/fiat-crypto/bedrock2/bedrock2/src/bedrock2/WeakestPreconditionProperties.v
Killed
make[3]: *** [Makefile.coq.noex:663: /root/fiat-crypto/bedrock2/bedrock2/src/bedrock2/WeakestPreconditionProperties.vo] Error 137
make[2]: *** [Makefile.coq.noex:327: all] Error 2
make[1]: *** [Makefile:35: noex] Error 2
make: *** No rule to make target 'bedrock2', needed by 'src/BoundsPipeline.vo'.  Stop.

**Comment by JasonGross** [comment]
This is https://github.com/mit-plv/bedrock2/issues/130 (you have not enough RAM).  You can work around this with `(cd bedrock2 && git checkout master && git pull)`, or you can wait for me to merge https://github.com/mit-plv/fiat-crypto/pull/644 (once the CI passes).  Or you can get more RAM (you'll need about 3.3 GB free to build the currently-pinned version of bedrock2).

**Comment by AsmaaHailane** [comment]
Thanks for your guiding

**Comment by JasonGross** [comment]
#644 has now been merged, so you can just `git pull && git submodule update --recursive`

**Comment by AsmaaHailane** [comment]
Thank you a lot

**Comment by JasonGross** [comment]
I expect this is resolved, so I will close now; feel free to reopen if it is not
