### ISSUE TITLE
Publish the fiat-rust crate

### ISSUE THREAD

**Issue by huitseeker** [mit-plv/fiat-crypto#647]
The fiat-rust crate is attractive to a large number of developers (the projects of @tarcieri, @kchalkias, @Pratyush come to mind), but tremendously more usable if published to Rust's package repository.

A workflow for regularly publishing this package automatically on the basis of [Github Actions](https://help.github.com/en/actions/automating-your-workflow-with-github-actions) would be useful to do so (the management of crates.io authentication is nice in Github actions, using secrets).

**Comment by JasonGross** [comment]
Now published
