### ISSUE TITLE
32-bit p521 uses uint128

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#655]
https://github.com/mit-plv/fiat-crypto/blob/b3c26501432fd1ec5dd75e0ba136b667106fd097/p521_32.c#L129-L143

The issue is that we claim to synthesize 17-limb 32-bit p521, but 1.1 * (521 / 17) > 32.  (We can't have a bounds multiplier greater than 1.044 in this case).  What should be done?

@andres-erbsen ?

**Comment by JasonGross** [comment]
Maybe we should also have a check that the bounds are all within the bitwidth...

**Comment by andres-erbsen** [comment]
I think we don't care about p521 on 32-bit right now, so let's drop it and figure out these issues when we need it?
