### ISSUE TITLE
License compliance and legal status of generated code?

### ISSUE THREAD

**Issue by xorhash** [mit-plv/fiat-crypto#678]
This repository is licensed under the MIT license, but I have a few open questions regarding licensing of the *inserted* code (such as the `#error` on two's complement mismatch [which should never matter anyway because C99, § 7.18.1.1(1) guarantees two's complement representation for exact-width types] and the function description strings) and *generated* code that are left over:

1. Unlike e.g. Clang and GCC, there is no special license exception for inserted code or generated code. Am I correct in assuming that your understanding is that both are covered by the MIT license?
2. The MIT license has some specific wording (emphasis added): “*The above copyright notice* and this permission notice shall be included in all copies or substantial portions of the Software.” My understanding is that it is required to copy the copyright notice 1:1 (see also). However, the above copyright notice reads “Copyright (c) 2015-2019 the fiat-crypto authors (see the AUTHORS file).” This effectively forces all inserted and generated code to include a file that must specifically be called `AUTHORS`, which is both frustrating for single-file libraries (they cannot be single-file by definition).

**Comment by JasonGross** [comment]
I am not an expert on copyright, and I'd like to make the code easy to use.  @andres-erbsen do you have thoughts on this?  @xorhash Do you have suggestions for what you'd like to see the licensing be?

**Comment by xorhash** [comment]
**Disclaimer**: I am not a lawyer. This is just my best-effort interpretation of what copyright law even allows.

> Do you have suggestions for what you'd like to see the licensing be?

There's a number of fiddly parameters that go into this; the main thing here is requiring attribution in the *output* code (which as far as I can tell, you have no desire for) and the code *that generates* the output. You want the former, there's no practically relevant reason not to have attribution on the latter.

As for the *output* code, I see that it consists of effectively four parts:

1. the header (curve parameters and generation command);
2. including `<stdint.h>` and typedefs;
3. a (likely redundant) two's complement check;
4. the generated code, which itself consists of:
    1. a brief description ("The function [namehere] is [...]" and preconditions/postconditions/bounds);
    2. the function prototype (number of arguments is fixed, the types are partially autogenerated);
    3. the completely autogenerated implementation code.

I think the most important aspect to hook into in this context is the [requirement of originality in copyright](https://en.wikipedia.org/wiki/Threshold_of_originality) and related concepts in various jurisdictions; it's fairly muddy, but I believe for the purpose of our discussion here, I feel comfortable to reducing it to “a human element” that is required for copyright protection in the first place.

1. The header is likely ineligible for copyright for similar reasons. The autogeneration command is dictated by necessity (argument order is fixed), so there's no room for originality there. Similarly, the curve description, the list of requested operations and the specification of `m` and the machine word size are all user-defined, which you have no control over in the first place and thus also no copyright interference from fiat-crypto per se. Perhaps the arrangement of the order of these arguments themselves could be eligible, but that's pretty bonkers. The "In addition to the bounds specified above each function, all [...]" string, on the other hand, appears to me to be eligible to be considered a small literary work.
2. The include and its position is a technical necessity; nothing to note here. The typedef names are *maybe* eligible, but probably not?
3. The two's complement check is original code, and there may be a reasonable amount of other ways  to express it, so there's likely copyright attached on the entire segment.
4. The *arrangement* of the generated code (i.e. the order in which they're generated) seems to be fixed in the code, so there's maybe an argument to be made there that the order is original.
    1. The brief description may be eligible to copyright; the order and arrangement of the bounds and postconditions perhaps as well, though not the actual bounds themselves, which are just mathematical necessity.
    2. The function prototypes (namely, the order of inputs and outputs) were designed by you. There's a bit of an argument about API copyrightability in the U.S. that goes in this general direction (Oracle v. Google, I'm sure you've heard of this one), so that's an issue to watch out for.
    3.  The autogenerated implementation code is effectively the result of an algorithm that itself is determined mostly by mathematical necessity; I therefore reasonably believe that this part in particular is *likely ineligible to any kind of copyright protection* in the first place, so this can be ignored.

With all this in mind, I can see a user-side workaround for the copyright elephants in the room: Removing all comments, the two's complement check, renaming the functions to be safe and maybe reordering the function arguments. Of course, that assumes that my analysis above was on the mark and didn't misclassify any part of the generated code.

---

As for the code of the *code that generates the output*: I believe it's reasonable to keep the status quo in terms of licensing; however, there's still the issue of physically being unable to comply in some instances. For that purpose, I'd suggest inlining AUTHORS into LICENSE instead, so that LICENSE can be copied everywhere (and/or added to individual file headers if only parts of the code are used in another project).

---

As for the actual question... I see several approaches here that could kind of get you somewhere. Before detailing it, here's the tl;dr:

Strategy | No attribution in generated code? | No attribution the actual project code? | Note
-|-|-|-
Re"license" CC-0 | x | x | No attribution ever, maximally permissive, but maybe scary for some legal dep'ts
Relicense 0-clause BSD | x | x | No attribution ever, extremely permissive, *maybe* scary for some legal dept's
License exception | x | | Leaves project code alone, but relieves downstream of attribution requirements; probably requires a lawyer to word it properly

# CC-0 public domain declaration

If given free rein and choice, I would replace LICENSE with the CC-0 legalcode, and add [the CC0 header](https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F) to all files, attributing "written by" to all people who have ever touched the file. That way, any existing copyright would be maximally discarded in every jurisdiction, in the most sound way I can think of. The current copyright holders may likely not be happy with this; plus you will need the approval of everyone whose code is in the repository right now.

The reason why this is my personally preferred option is because:

1. the CC-0 has a sound fallback license for when dedication into the public domain fails (which it will in some jurisdictions);
2. Professor Daniel J. Bernstein has sort of set a trend of public domain reference implementations, which I believe is worthwhile to keep allowing—just now with safe, generated field arithmetic code for new curve implementations.

However, this would also be *overkill*: You'd disclaim copyright on perfectly fine, original code, just to make room for some edge cases caused by code generation. Once dedicated to the public domain, you cannot change your mind and go "actually, I'd like to have my copyright back"; it's gone in all jurisdictions in which this was possible in the first place and only future changes can be covered.

# BSD 0-clause

To keep your copyright, but remove *all* attribution requirement, there's the option of re-licensing the code [to be covered by the BSD 0-clause license](https://spdx.org/licenses/0BSD.html) (with the copyright notice changed). The effect is effectively identical to the above, but retains copyright; because of this, it's probably still overkill because the main issue is the generated code, not the large fiat-crypto codebase itself.

# License exception

A more amenable change may be to add a specific exception, similar to the [Clang exception to the Apache 2.0 license](https://github.com/llvm-mirror/clang/blob/master/LICENSE.TXT#L208-L222); however, the wording cannot be copied 1:1 since fiat-crypto generates source code rather than object code. The goal of this exception would be to:

1. leave the disclaimer intact and protect the contributors and copyright holders from legal liabilities; and
2. remove the requirements of attribution and shipping the full license text.

However, adding a clause yourself is kind of "legal homebrew" without a lawyer wording it. I can't really say I'd really recommended that strategy, and will probably scare legal departments away from it, rather than encourage liberally sprinkling code generated by fiat-crypto.

**Comment by andres-erbsen** [comment]
Hi,

I am glad to see you are interested in our project, and I all for single-file libraries. I also believe that "maybe scary for some legal dep'ts" is in fact relevant given the two institutions holding copyright on this project, and that any licensing changes at this point would be rather cumbersome and come at a significant cost of dev time better spent on improving the library. Thus, I (not a lawyer, not particularly well-read on this topic) am trying to think of alternatives. I appreciate your analysis of originality above, but I do not feel confident enough about it to rely on it if I was considering using a project with similar licensing. (For example, another possible interpretation here is that the .c files are a compiled form of the .v files in the Arithmetic directory.) So, instead, what if you took the generated files you want, and in each one of them:

- at the beginining, inserted: "LICENSE FILE:", inlined the LICENSE file, "END OF LICENSE FILE"
- after that, inserted "AUTHORS FILE:", inlined the AUTHORS file, "END OF AUTHORS FILE"

This would meet the requirement of reproducing the license verbatim and make clear who the authors are. And while AUTHORS would no longer be a separate file according to the OS file system, this does not seem different from packaging the entire repository in a tarball, which I dearly hope is fine for any MIT-licensed repository.

Cheers,
Andres

**Comment by xorhash** [comment]
I do not notice any issue with that approach. Thank you for your guidance.
