### ISSUE TITLE
Should we unset Fast Name Printing?

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#700]
Currently we have
https://github.com/mit-plv/fiat-crypto/blob/43ced13048453fe7b1922ee68684d2afbdcecc06/src/Util/GlobalSettings.v#L30

But this makes interactive proving somewhat annoying, because it prints things like `(nat -> nat -> Prop) -> True` as `forall H : forall H H0 : nat, Prop, True`.  I think we should unset it.  @andres-erbsen thoughts?

**Comment by andres-erbsen** [comment]
That sound annoying indeed. does fast name printing just totally disable notations that hide a binder? :(

**Comment by JasonGross** [comment]
It disables notations that rely on the binder being unused in the term.  It can also result in actively confusing goals.  For example, if you have `H : Type` and `H1 : forall x, H = x`, and then you do `rename H into x`, you will see `H1 : forall x, x = x` because it won't bother to avoid clashing names.

**Comment by andres-erbsen** [comment]
Ugh. Why did we ever enable this?

**Comment by JasonGross** [comment]
Because printing was slow?

**Comment by andres-erbsen** [comment]
Yeah, sure. But I don't think we can have globally on an option that prints goals wrong.
