### ISSUE TITLE
Binary invocations hang on invalid arguments

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#701]
Minimal example: `./unsaturated_solinas --xyz '25519' '5' '2^255 - 19' '64' carry_mul`

I ran into this on the `cli-bedrock2` branch.

**Comment by JasonGross** [comment]
Ah, this is because it interprets --xyz as the curve name and then thinks that you are asking it to use 25519 limbs....  Maybe I should disallow curve names starting with -?  Or treat all -- things as options?

**Comment by JasonGross** [comment]
As a historical note, I'm now suspecting that the hanging behavior was due to trying to compute the bitwidth in unary. This is fine for 64-bit machines, less fine for 2^255-19-bit machines.
