### ISSUE TITLE
Translate `Z.zselect` to bedrock2

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#750]
Currently, synthesis of `to_bytes` and `selectznz` fails on bedrock2 because we don't have a good translation for `Z.zselect` (bedrock2 doesn't have a conditional-move or select instruction). I have an idea for how to translate it:
```
Z.zselect c x y ==
    let a := sub 0 (eq c 0) in
    let b := xor a 0xFFFFFFFF in
    or (and x a) (and y b)
```
This expression would be expressible in bedrock2. To implement it, we could do one of two things. One option is that I implement this transformation in the bedrock2 backend. This is possible but clunky; because it requires setting a variable (`a`) that is used twice, it would need to be implemented as a special case at the higher `cmd` level of abstraction, as opposed to the `expr` level where instruction-level translations usually live.

The other option is to add a new rewrite rule, and possibly a new CLI flag to indicate when we should use the new rule. This is probably nicer, except for the wrinkle that I don't think we support `xor` right now in the AST. Do we? If we need to add support for a new instruction, I'd actually vote for adding `Z.lnot` instead of `Z.xor` here; I'm using `xor` to implement `not` because bedrock2 doesn't have a `not` operation, and it would be straightforward to write that `not` gets translated to `xor` with 1s. That way if bedrock2 does later support `not`, the change would be really simple and at the appropriate level of abstraction.

So, succinctly, my questions are:
@andres-erbsen does this translation seem reasonable to you?
@JasonGross do we support `Z.lxor` or `Z.lnot`? How much work would be needed to support `Z.lnot` and a new rewrite rule to transform `Z.zselect`?

**Comment by andres-erbsen** [comment]
seems reasonable. if xor is an issue, what about b=-1-a? bedrock2 likely won't have not, it already has xor and ndn.

**Comment by jadephilipoom** [comment]
Would probably express as `0xFFFFFFFF - a` to pass bounds-check, but yes, that's a good idea :)

Speaking of bounds check, another note: `0 - (eq c 0)` would need to be expressed in the AST some other way to pass bounds check. I'd actually like to express it as `Z.zselect c 0 0xFFFFFFF`, which would have the nice property that the zselects between 0 and a mask (like in `to_bytes`) actually get translated to a more efficient expression. Would I be able to write the new rewrite rule so that it doesn't then fire again on the newly introduced zselect?

**Comment by JasonGross** [comment]
@jadephilipoom We already have `Z.lnot_modulo`.  Do you need `Z.lnot` / `Z.lxor` in addition to that?  In any case, by far the most work-intensive part of adding a new identifier is writing the bounds analysis rule (and corresponding proof) for it.  If you want, I can make a PR that adds `Z.lxor` and(/or) `Z.lnot` and fixes all the places except for the bounds-analysis part, and leave a TODO axiom for you for the bounds analysis rules.

**Comment by JasonGross** [comment]
> Would I be able to write the new rewrite rule so that it doesn't then fire again on the newly introduced zselect?

I'd rather have idempotent rewrite rules, so there's freedom in the pipeline, but if you want to add it as a separate pass that is "run this past as the absolute last pass, and run it only once", then, yeah, by default the rewrite rule won't trigger on it's own output.  An alternative would be to insert a dummy identity rewrite rule right before the zselect ones that says to rewrite any zselect on two literals into itself.  (And then because rewriting doesn't trigger by default in the output of a rewrite rule, and rewrite rules are considered in order, no further rewrites from that pass will trigger in the result.)

**Comment by JasonGross** [comment]
> @JasonGross do we support `Z.lxor` or `Z.lnot`?

@jadephilipoom https://github.com/mit-plv/fiat-crypto/pull/753

**Comment by jadephilipoom** [comment]
> I'd rather have idempotent rewrite rules, so there's freedom in the pipeline, but if you want to add it as a separate pass that is "run this past as the absolute last pass, and run it only once", then, yeah, by default the rewrite rule won't trigger on it's own output. An alternative would be to insert a dummy identity rewrite rule right before the zselect ones that says to rewrite any zselect on two literals into itself. (And then because rewriting doesn't trigger by default in the output of a rewrite rule, and rewrite rules are considered in order, no further rewrites from that pass will trigger in the result.)

Hmm, this isn't exactly what I'm going for. I really want a rewrite rule that fires on all zselects *unless* they happen to be `Z.zselect _ 0 (2^bitwidth-1)`. So it would be idempotent; it would introduce a zselect that it shouldn't fire on.

An important difference between that and running the rule only once is that in `to_bytes` we actually have a zselect between 0 and a mask. And I want to translate *that* to `0 - (eq c 0)`, not the more complex pattern for non-literal zselects. I want the rule to fire 0 times on that expression.

**Comment by JasonGross** [comment]
> Hmm, this isn't exactly what I'm going for. I really want a rewrite rule that fires on all zselects _unless_ they happen to be `Z.zselect _ 0 (2^bitwidth-1)`. So it would be idempotent; it would introduce a zselect that it shouldn't fire on.

What about the alternative suggestion?  I think that meets your needs.  (Note that it's not possible to condition a rewrite rule on something not being a literal; this is possibly a feature for a future version.)  Let me spell out a bit more my alternative suggestion:
Context: By default, rewrites are processed in order, and if a rewrite rule succeeds, nothing fires on the output of that rewrite rule.
Suggestion: It seems you want a rewrite rule `r` of the form `args != literal -> p = v`.  I'm suggesting replacing that single rewrite rule with a sequence of two rewrite rules, the first of the form `p' = p'` and the second of the form `p = v`, where `p'` is `p` except with the relevant arguments replaced by literals.  In this case, whenever the first rewrite rule matches and succeeds, the second will never trigger.  In all cases where it does not match, or where the sideconditions are false, the second rewrite rule will be tried.  So, for example, if you have
```
; Z.zselect k ('0) ('(2^bitwidth-1)) = Z.zselect k ('0) ('(2^bitwidth-1))
; Z.zselect k x y = stuff
```
(and you have the casts in the right place), anything that matches `Z.zselect k ('0) ('(2^bitwidth-1))` will remain untouched (being rewritten to itself), and every other `Z.zselect` will pass to the second rewrite rule and be replaced by `stuff`.

**Comment by jadephilipoom** [comment]
Ah, okay! Thanks for the elaboration, I misunderstood it before. This seems like it would have the right behavior.

So now we need a new rewriter pass containing these rules, and a CLI flag saying whether to call them, right?

**Comment by JasonGross** [comment]
Yes, that sounds right
