### ISSUE TITLE
bedrock2: 32-bit curve25519 code on CI?

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#751]
like curve25519_64.c, but for a 32-bit machine.

**Comment by jadephilipoom** [comment]
Like `fiat-c/src/curve25519_32.c`?

**Comment by andres-erbsen** [comment]
Yes, like that, with the bedrock2 backend.

**Comment by JasonGross** [comment]
Do you want it generated identically?  That is, is the 32-bit one only allowed to use 32-bit integers, or is it also allowed to use 64-bit integers?

**Comment by andres-erbsen** [comment]
Yes. Only 32-bit integers, the 64-bit ones need to be split into 32-bit parts first.
