### ISSUE TITLE
Can't run on Mac

### ISSUE THREAD

**Issue by mimoo** [mit-plv/fiat-crypto#773]
Hello,

I am trying to implement ECDSA P-256 with fiat-crypto, but there's only arithmetic for the field part. I was thinking that I can probably use `word_by_word_montgomery` to generate arithmetic for the scalar part (which is done with a different modulus).

But I can't seem to `make` on my mac. I'm getting this error (after doing `brew install coq; brew install opam`):

```
/bin/sh: /usr/local/opt/ocaml-findlib/bin/ocamlfind: No such file or directory
/Library/Developer/CommandLineTools/usr/bin/make --no-print-directory -C rewriter
CAMLDEP src/Rewriter/Util/plugins/strategy_tactic.mli
/bin/sh: /usr/local/opt/ocaml-findlib/bin/ocamlfind: No such file or directory
CAMLDEP src/Rewriter/Util/plugins/rewriter_build.mli
/bin/sh: /usr/local/opt/ocaml-findlib/bin/ocamlfind: No such file or directory
CAMLDEP src/Rewriter/Util/plugins/inductive_from_elim.mli
/bin/sh: /usr/local/opt/ocaml-findlib/bin/ocamlfind: No such file or directory
CAMLDEP src/Rewriter/Util/plugins/definition_by_tactic.mli
/bin/sh: /usr/local/opt/ocaml-findlib/bin/ocamlfind: No such file or directory
CAMLDEP src/Rewriter/Util/plugins/strategy_tactic.ml
/bin/sh: /usr/local/opt/ocaml-findlib/bin/ocamlfind: No such file or directory
...
```

**Comment by JasonGross** [comment]
You need to `opam install ocamlfind` (perhaps `ocamlfind.1.8.1`?).  See our Mac CI setup in https://github.com/mit-plv/fiat-crypto/blob/81aefa3c03d1df1b4526f0c8eb2eb7fa45ec8f0c/.github/workflows/coq-macos.yml#L40 
It might be the case that the `brew` version of Coq is incompatible with the `opam` version of `ocaml` (I'm not sure), in which case you'd need to remove the `brew`-installed `coq` and instead install Coq via opam (see [here](https://coq.inria.fr/opam-using.html)).  I'm not sure.  Please report back either way, so we can update the README with appropriate Mac install instructions.

**Comment by mimoo** [comment]
I forgot to mention that I had also installed `ocamlfind` before getting that error, but it looks like things are not installed in the same paths

**Comment by mimoo** [comment]
going to `brew install open && opam install coq` route, it still doesn't work:

```
Error: The reference Z.div_mod_to_equations was not found in the current
```

**Comment by JasonGross** [comment]
What version of Coq did that install?  If it's older than 8.9, it won't work at all, and if it's older than 8.10, you need to pass `SKIP_BEDROCK2=1`

**Comment by mimoo** [comment]
```
❯ coqc -v
The Coq Proof Assistant, version 8.9.0 (May 2020)
compiled on May 4 2020 13:53:45 with OCaml 4.07.1
```

**Comment by JasonGross** [comment]
Indeed.  That alternative is to do something like `opam install coq.8.11.1`

**Comment by mimoo** [comment]
it worked! Although I can't find what make produced but I should probably read the README more :D

**Comment by JasonGross** [comment]
Great!

The relevant part of the README is:
> The binaries are located in `src/ExtractionOcaml/` and `src/ExtractionHaskell` respectively.

**Comment by JasonGross** [comment]
Also, @mimoo, if you have thoughts about what we should put in the README to make it easier on the next Mac user, I'm interested in suggestions.

**Comment by mimoo** [comment]
here's what I ended up doing:

```
brew install opam
opam install coq
opam install ocamlfind
SKIP_BEDROCK2=1 make
```
