### ISSUE TITLE
why don't we have to_montgomery in generated code?

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#784]
There is https://github.com/mit-plv/fiat-crypto/blob/5cab97ed8f17e294f4e7e66010147a518c45f3a6/src/Arithmetic/MontgomeryReduction/Definition.v#L170
but that doesn't seem to make it to the .c/.rs files. Is there a reason, or did we just forget?

The `R` in that definition is just `2^256` for P-256, right?

**Comment by JasonGross** [comment]
I think it's just because BoringSSL never asked for it?

**Comment by mimoo** [comment]
does it generate the R differently depending on the order passed? (I'm using fiat-crypto to generate scalar arithmetic, not field arithmetic, the modulo is different : o)

**Comment by JasonGross** [comment]
In https://github.com/mit-plv/fiat-crypto/blob/62978b9fd2b00f544ac0fd24f51d9428f09988f5/src/Arithmetic/WordByWordMontgomery.v#L1074
`R` is `(2^bitwidth)^numlimbs`

**Comment by davidben** [comment]
We don't use to_montgomery in BoringSSL as a consequence of the curve bits being a mix of some generic code and the tuned curve-specific code. (Artifacts of this code's OpenSSL ancestry.) Having to_montgomery makes sense. We may even end up using it later depending on how our EC bits evolve. I've been gradually trying to make that abstraction more sensible.

**Comment by davidben** [comment]
I guess you could always do to_montgomery by stashing a reduced copy of R^2 somewhere and multiplying. Though perhaps the synthesized code can be smarter knowing the value ahead of time.

**Comment by JasonGross** [comment]
#786 adds generation of `to_montgomery`.  I'm not sure to what extent it actually ends up being smarter about things (but the value of `R^2` is inlined into the multiplication).

**Comment by mimoo** [comment]
btw it's not clear in what format the field element must be (`[u32; 8]`). Is it in little-endian? Does it have to be smaller than p?

**Comment by JasonGross** [comment]
Indeed, we should specify endianess in a comment.  @andres-erbsen , how do you think we should do this?  As for smaller than p:
https://github.com/mit-plv/fiat-crypto/blob/51abc74eaeb0af651e9a0cb4b3b3d013d33e9a8e/fiat-c/src/p256_64.c#L7-L12

**Comment by JasonGross** [comment]
One thought is that we could print the definition of `eval` specialized to the particular weight function in a comment at the top.  This would have the benefit of being automatically generated, being guaranteed to be in sync with the code, and being precise.
