### ISSUE TITLE
Cannot build anymore on mac

### ISSUE THREAD

**Issue by mimoo** [mit-plv/fiat-crypto#790]
I cannot make on Mac anymore. I'm getting this error after doing

```
SKIP_BEDROCK2=1 make
```

```
COQC src/AbstractInterpretation/Wf.v
File "./src/AbstractInterpretation/Wf.v", line 295, characters 40-75:
Error: The reference expr.invert_App_curried_App_curried was not found
in the current environment.

make: *** [src/AbstractInterpretation/Wf.vo] Error 1
```

**Comment by JasonGross** [comment]
I suspect your submoudle is out of date.  If you run `git diff`, what do you see?  Does running `git submoudle update; SKIP_BEDROCK2=1 make clean; SKIP_BEDROCK2=1 make` fix it?

**Comment by mimoo** [comment]
trying this, `make` takes a looot of time :D

**Comment by mimoo** [comment]
indeed it works! Thanks!
