### ISSUE TITLE
get_possible_limbs thinks there are no valid limbs for 2^448 - 2^224 - 1

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#801]
https://github.com/mit-plv/fiat-crypto/blob/ccf644f710b931dad8339aa63c1ce6e95d19a623/src/UnsaturatedSolinasHeuristics.v#L96-L111

```coq
Compute @get_possible_limbs (2^448) [(2^224,1); (1,1)] 64
```
gives `[]`, and similarly for 32 bits.

**Comment by jadephilipoom** [comment]
Oh wow, this heuristic is completely wrong in the context of anything but very small `c`. I think this code might predate our understanding of multi-tap primes. It contains a division by zero if `c` has more limbs than the machine word size, so it doesn't work on *any* multi-tap primes.
