### ISSUE TITLE
Core.v cleanup

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#809]
The file holding the main logic for our arithmetic templates, `Arithmetic/Core.v`, is a bit overwhelming. It's over 1400 lines and contains mixed code and proofs (including some proofs that _really_ seem like they could be improved with another close look). I think it could be improved, and that it should be given it's a pretty important file. I'm willing to do it myself.

Some ideas:
- separate out code and proofs so it's easy to skim the templates
- separate associational and positional, and make Core.v a skeleton file that exports both
- more comments
- fix the huge slow proofs

What do you think @JasonGross @andres-erbsen ?

**Comment by JasonGross** [comment]
This seems good!  Note that Arithmetic/Core currently takes about 43s to compile on my machine.

> - separate out code and proofs so it's easy to skim the templates

It might be nice if we can figure out more automation, and put the relevant automation tactics elsewhere, but leave the proofs together with the code (I feel like having at least the statement of the semantics of each operation, next to the operation, is nice).

> - separate associational and positional, and make Core.v a skeleton file that exports both

My inclination is many small files, but sometimes @andres-erbsen disagrees.  I'm happy to have these in separate files; @andres-erbsen what do you think?

> - more comments

Generally seems good.

> - fix the huge slow proofs

This sounds pretty great.

I don't have time to take much of this on my plate, but if you have a particular proof that you want me to performance-analyze and/or micro-optimize, let me know and I can try to dig into it.  (This should be done only after the proof is in a state where you don't think it's doing any high-level-unnecessary things, and where you think the proof strategy should be relatively fast, but it's spending unreasonable amounts of time in one of the automation tactics that should be doing simple things, or doing rewriting, or where the time gets spent seems mysterious).

Also let me know if any of the few templates that I wrote (I think I did one for a fused square-and-reduce pass) are hard to understand / make sense of, and I can try to write comments for those.
