### ISSUE TITLE
Windows CI test is broken

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#815]
It's been failing due to a python problem. My vote is to get rid of the Windows test entirely, since it's been repeatedly having issues and has never once to my knowledge caught any problems that exist only on Windows. @JasonGross , what do you think?

**Comment by JasonGross** [comment]
I believe it's caught a windows-specific bug in our Makefile setup once, and also caught an only-on-windows Heisenbug-segfault in Coq itself (in micromega).  I'm inclined to keep it

**Comment by JasonGross** [comment]
Fixed by 71ece0a53e535095cd11ed14ec8de61f14598a40
