### ISSUE TITLE
Mixed declarations and code

### ISSUE THREAD

**Issue by bbbrumley** [mit-plv/fiat-crypto#824]
Howdy Fiat Folks,

```ISO C90 forbids mixed declarations and code```

This is a warning generated because of stuff like

```C
    uint64_t x8;
    fiat_secp384r1_mulx_u64(&x7, &x8, x6, (arg2[5]));
    uint64_t x9;
```

You probably think this is a dumb compiler warning and I should just turn it off. And I even agree with you. But it's in the coding guidelines for many projects. For example, [OpenSSL](https://www.openssl.org/policies/codingstyle.html) which is currently one of many things holding up [this PR](https://github.com/openssl/openssl/pull/12201).

Is there any way to prevent that with Fiat? I'd rather not resort to shamelessly hacking up your output C with some BS post-processing script.

In other news, our project [ECCKiila](https://gitlab.com/nisec/ecckiila) is now public, powered by Fiat! Thanks for all your impactful work.

**Comment by JasonGross** [comment]
I can add in a post-processing pass internally that does this, hopefully within the next few days.  In particular, our syntax tree type is defined at 
https://github.com/mit-plv/fiat-crypto/blob/184b333d7e16b453de92cd6f87afc47bec0d279c/src/Stringification/IR.v#L100-L106
and we just need to define a pass that lifts the declarations to the top in `expr_of_PHOAS'` (presumably parameterized on a flag that we thread through, or just set on a per-language basis)
https://github.com/mit-plv/fiat-crypto/blob/184b333d7e16b453de92cd6f87afc47bec0d279c/src/Stringification/IR.v#L1472-L1500

**Comment by JasonGross** [comment]
> In other news, our project [ECCKiila](https://gitlab.com/nisec/ecckiila) is now public, powered by Fiat!

Congrats!
