### ISSUE TITLE
MacOS build is broken

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#842]
...again. Seems to be a ruby dependency issue in the setup.

Failures from the MacOS and Windows builds make it hard to see which commits actually break something, and fills my inbox with superfluous "build failed" notifications. If we can't remove them, can we at least make them optional, so the commit still gets a check mark if they fail?

**Comment by JasonGross** [comment]
This is pending https://github.com/coq/coq/pull/12672.  Maybe let's delete the mac job for now and put it back when https://github.com/coq/coq/pull/12672 gets merged and we have a way of building on mac again?

**Comment by JasonGross** [comment]
And what's the latest windows failure?
