### ISSUE TITLE
Help with adding rupicola dependency

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/fiat-crypto#863]
@JasonGross 

I'm trying to add rupicola as a submodule (see branch `add-rupicola`) and it's giving me quite a lot of trouble. Since rupicola also depends on bedrock2 and coqutil, I had to thread our dependencies on them through rupicola's (so we now depend on rupicola directly as a submodule, and get bedrock2 and coqutil through recursive submodules). I've gotten the recursive dependencies (bedrock2 and coqutil) to work, but I have two remaining issues with the direct dependency on rupicola:

1. I can't import rupicola files. I get `Error: Cannot find a physical path bound to logical path matching suffix
Rupicola.Lib.` This is possibly related to the warnings I'm getting when I build the rupicola dependency, which is a line for every file and directory that says `Warning: /home/jadep/plv/fiat-crypto/rupicola/src/Lib was previously bound to
Lib; it is remapped to Rupicola.Lib [overriding-logical-loadpath,loadpath]`. A bit stumped as to what's causing this, why it wasn't a problem for the bedrock2 and coqutil dependencies, and how to fix the issue.
2. When I run the CI, the `deps` target fails because the `.timing` files added to rupicola cause a `-dirty` to be added to the submodule commit and therefore the diff isn't clean. In the branch, I modified `coq.yml` so that it runs normal `make` instead of `github_actions_make.sh`, just so I can see other things that are failing (MacOS and Windows builds still show the `.timing` issue). Is there a reason we shouldn't run regular `make` on dependencies, given we don't really care about their timing? If we really need to use `github_actions_make`, then how can I get it to ignore the extra files?

**Comment by JasonGross** [comment]
1. I'm order for Rubicola to be compatible with COQPATH, you need to, e.g., rename src/Lib to sec/Rubicola/Lib and then point COQPATH at src.  See, e.g., the way we do this for bedrock and coqutil and the rewriter.
2. Add *.timing to Rubicola's .gitignore

**Comment by jadephilipoom** [comment]
Resolved, thanks!
