### ISSUE TITLE
Issues with the bedrock2 backend on functions taking a list as input and returning a tuple

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#886]
> @jadephilipoom Both `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => x1` and `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => x2` synthesize correctly, but `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => (x1, x2)` and `fun (x1 : Z) (x2 x3 x4 x5 : list Z) => (x2, x3)` both fail. On the other hand `fun (x1 x2 : Z) (x3 .. : listZ) => (x1, x2)` also does not synthesize correctly, which doesn't really agree with the fact that addcarryx and mulx synthesizes properly?

_Originally posted by @bshvass in https://github.com/mit-plv/fiat-crypto/pull/670#issuecomment-709117953_

------

My guess is that the commonality is that all of these functions take a list as input and return a tuple.  AFAIK, we don't currently have any other functions which both take at least one list as input and also return a tuple of things.

**Comment by JasonGross** [comment]
Self-contained example of issues:
```coq
Require Import Coq.ZArith.ZArith.
Require Import Coq.Strings.String.
Require Import Coq.Lists.List.
Require Import Crypto.Util.ZRange.
Require Import Crypto.BoundsPipeline.
Require Import Crypto.Bedrock.Standalone.Stringification.

Require Import Crypto.Util.Notations.
Local Open Scope string_scope.
Local Open Scope list_scope.
Import ListNotations. Local Open Scope Z_scope.

Import
  AbstractInterpretation.Compilers
  Language.Compilers
  Language.API.Compilers.

Import Language.API.Compilers.API.

Local Coercion Z.of_nat : nat >-> Z.
Local Coercion Z.pos : positive >-> Z.

Local Existing Instance default_low_level_rewriter_method.
Local Instance : unfold_value_barrier_opt := true.

Module debugging_bedrock2.
  Section __.
    Local Existing Instance OutputBedrock2API.
    Local Existing Instances Pipeline.show_ErrorMessage.
    Local Instance static : static_opt := true.
    Local Instance : internal_static_opt := true.
    Local Instance : emit_primitives_opt := false.
    Local Instance : use_mul_for_cmovznz_opt := false.
    Local Instance : widen_carry_opt := true.
    Local Instance : widen_bytes_opt := true.
    Local Instance : only_signed_opt := false.
    Local Instance : no_select_opt := true.
    Local Instance : should_split_mul_opt := true.
    Local Instance : should_split_multiret_opt := true.
    Local Instance : machine_wordsize_opt := 64.
    Let machine_wordsize := 64.
    (** ================================================= *)
    Let possible_values := prefix_with_carry [machine_wordsize].
    Local Instance : no_select_size_opt := no_select_size_of_no_select machine_wordsize.
    Local Instance : split_mul_to_opt := split_mul_to_of_should_split_mul machine_wordsize possible_values.
    Local Instance : split_multiret_to_opt := split_multiret_to_of_should_split_multiret machine_wordsize possible_values.
    Let bound := r[0 ~> (2^machine_wordsize - 1)]%zrange.
    Import IR.Compilers.ToString.

    Compute
      Show.show (* [show] for pretty-printing of the AST without needing lots of imports *)
      false
      (Pipeline.BoundsPipelineToString
         "fiat" "mul"
            false (* subst01 *)
            None (* fancy *)
            possible_values
            64
            ltac:(let r := Reify ((fun (x1 x2 : Z) => x1)) in
                  exact r)
                   (fun _ _ => []) (* comment *)
                   (Some bound, (Some bound, tt))
                   None
      ). (* success *)

    Compute
      Show.show (* [show] for pretty-printing of the AST without needing lots of imports *)
      false
      (Pipeline.BoundsPipelineToString
         "fiat" "mul"
            false (* subst01 *)
            None (* fancy *)
            possible_values
            64
            ltac:(let r := Reify ((fun (x1 x2 : Z) => (x1, x2))) in
                  exact r)
                   (fun _ _ => []) (* comment *)
                   (Some bound, (Some bound, tt))
                   (None, None)
      ). (* failure *)
```

I think actually the thing is that `addcarryx` and `mulx` are unused in the bedrock2 backend, so we're not testing their synthesis

**Comment by JasonGross** [comment]
The error comes from the fact that
https://github.com/mit-plv/fiat-crypto/blob/b3638100aa03e9a1d0358c4047b8e1a2c780f0fe/src/Bedrock/Field/Translation/Cmd.v#L73-L85
delegates to `assign` of `translate_expr` at 
https://github.com/mit-plv/fiat-crypto/blob/b3638100aa03e9a1d0358c4047b8e1a2c780f0fe/src/Bedrock/Field/Translation/Expr.v#L254-L268
and `translate_expr` sees that `pair` is not cast-exempt nor do pairs come prefixed with casts, and so considers that all pairs are errors.  @jadephilipoom what should be done?

**Comment by JasonGross** [comment]
(Btw, my debugging script was:
```coq
Require Import Coq.ZArith.ZArith.
Require Import Coq.QArith.QArith.
Require Import Coq.QArith.Qround.
Require Import Coq.Strings.String.
Require Import Coq.derive.Derive.
Require Import Coq.Lists.List.
Require Import Crypto.Util.ZRange.
Require Import Crypto.Arithmetic.Core.
Require Import Crypto.Arithmetic.ModOps.
Require Import Crypto.Arithmetic.Partition.
Require Import Crypto.PushButtonSynthesis.UnsaturatedSolinas.
Require Import Crypto.UnsaturatedSolinasHeuristics.
Require Crypto.PushButtonSynthesis.SaturatedSolinas.
Require Crypto.PushButtonSynthesis.WordByWordMontgomery.
Require Crypto.Stringification.C.
Require Crypto.Stringification.Go.
Require Crypto.Stringification.Java.
Require Import Crypto.BoundsPipeline.
Require Import Crypto.Util.ZUtil.ModInv.

Require Import Crypto.Util.Notations.
Local Open Scope string_scope.
Local Open Scope list_scope.
Import ListNotations. Local Open Scope Z_scope.

Import
  AbstractInterpretation.Compilers
  Language.Compilers
  Language.API.Compilers.

Import Language.API.Compilers.API.

Import Associational Positional.

Local Coercion Z.of_nat : nat >-> Z.
Local Coercion QArith_base.inject_Z : Z >-> Q.
Local Coercion Z.pos : positive >-> Z.

Local Existing Instance default_low_level_rewriter_method.
Local Instance : unfold_value_barrier_opt := true.
Local Instance : tight_upperbound_fraction_opt := default_tight_upperbound_fraction.

Module debugging_bedrock2.
  Require Import Crypto.Bedrock.Standalone.Stringification.
  Section __.
    Local Existing Instance OutputBedrock2API.
    Local Existing Instances Pipeline.show_ErrorMessage.
    Local Instance static : static_opt := true.
    Local Instance : internal_static_opt := true.
    Local Instance : emit_primitives_opt := false.
    Local Instance : use_mul_for_cmovznz_opt := false.
    Local Instance : widen_carry_opt := true.
    Local Instance : widen_bytes_opt := true.
    Local Instance : only_signed_opt := false.

    Local Instance : no_select_opt := true.
    Local Instance : should_split_mul_opt := true.
    Local Instance : should_split_multiret_opt := true.
    Local Instance : machine_wordsize_opt := 64.
    Let machine_wordsize := 64.
    (** ================================================= *)
    Let possible_values := prefix_with_carry [machine_wordsize].
    Local Instance : no_select_size_opt := no_select_size_of_no_select machine_wordsize.
    Local Instance : split_mul_to_opt := split_mul_to_of_should_split_mul machine_wordsize possible_values.
    Local Instance : split_multiret_to_opt := split_multiret_to_of_should_split_multiret machine_wordsize possible_values.
    Let bound := r[0 ~> (2^machine_wordsize - 1)]%zrange.
    Import IR.Compilers.ToString.

    Goal True.
      pose
              (Pipeline.BoundsPipelineToString
         "fiat" "mul"
            false (* subst01 *)
            None (* fancy *)
            possible_values
            64
            ltac:(let r := Reify ((fun (x1 x2 : Z) => x1)) in
                  exact r)
                   (fun _ _ => []) (* comment *)
                   (Some bound, (Some bound, tt))
                   None
              ) as v1.
      pose       (Pipeline.BoundsPipelineToString
         "fiat" "mul"
            false (* subst01 *)
            None (* fancy *)
            possible_values
            64
            ltac:(let r := Reify ((fun (x1 x2 : Z) => (x1, x2))) in
                  exact r)
                   (fun _ _ => []) (* comment *)
                   (Some bound, (Some bound, tt))
                   (None, None)
                 ) as v2.
      vm_compute in v1.
      clear v1.
      cbv [Pipeline.BoundsPipelineToString] in v2.
      cbv [Pipeline.BoundsPipelineToStrings] in v2.
      set (k := Pipeline.BoundsPipeline _ _ _ _ _ _) in (value of v2).
      vm_compute in k.
      subst k.
      cbv beta iota zeta in v2.
      cbv [ToString.ToFunctionLines] in v2.
      cbv [OutputBedrock2API] in v2.
      cbv [Bedrock2_ToFunctionLines] in v2.
      cbv [SelectParameters.select_parameters MakeListLengths.list_lengths_from_argbounds] in v2.
      set (k := find _ _) in (value of v2).
      hnf in k.
      cbv [Defaults64.default_parameters] in k.
      subst k.
      cbv beta iota in v2.
      cbn [fst snd] in v2.
      cbv [Crypto.Util.Option.bind] in v2.
      cbv [MakeListLengths.list_lengths_from_bounds] in v2.
      cbv [MakeAccessSizes.make_access_sizes_args] in v2.
      cbv [MakeAccessSizes.make_base_access_sizes] in v2.
      cbn [fst snd] in v2.
      cbv [type.final_codomain] in v2.
      set (k := MakeNames.make_innames _) in (value of v2).
      vm_compute in k.
      subst k.
      vm_compute MakeNames.make_outnames in v2.
      set (k := Func.translate_func _ _ _ _ _ _) in (value of v2).
      clear -k.
      Import IdentifiersBasicGENERATED.Compilers.
      (* Func.translate_func
         (fun var : type -> Type =>
          (λ x x0 : var (type.base (base.type.type_base Z)),
           (#ident_Z_cast @ ###r[0 ~> 18446744073709551615]%zrange @ $x,
           #ident_Z_cast @ ###r[0 ~> 18446744073709551615]%zrange @ $x0))%expr)
         ("in0", ("in1", tt)) (tt, (tt, tt)) (tt, (tt, tt))
         ("out0", "out1") (tt, tt)*)
      cbv beta delta [Func.translate_func] in k.
      set (k' := LoadStoreList.load_arguments _ _ _ _) in (value of k).
      vm_compute in k'.
      subst k'.
      lazymatch (eval cbv delta [k] in k) with
      | let x := ?v in ?f => change (match v with x => f end) in (value of k)
      end.
      cbn beta iota delta [fst snd] in k.
      do 3 lazymatch (eval cbv delta [k] in k) with
      | let x := ?v in ?f => change (match v with x => f end) in (value of k)
      end.
         set (k' := Func.translate_func' _ _ _) in (value of k).
         cbn [fst snd Func.translate_func'] in k'.
         Locate Cmd.translate_cmd.
         cbn [Cmd.translate_cmd]in k'.
         Locate Expr.translate_expr.
         cbn [Expr.translate_expr] in k'.
         vm_compute Expr.cast_exempt in k'.
         cbv beta iota zeta in k'.
         vm_compute Expr.is_cast in k'.
         cbv beta iota zeta in k'.
```
)

**Comment by jadephilipoom** [comment]
The translation expects casts before pairs because, in some previous version, the reified code *did* contain casts before every pair. If this is no longer the case, then pair should be added as a case to cast_exempt.

Thanks for looking into this! Sorry I've been a little slow to respond.

**Comment by JasonGross** [comment]
> in some previous version, the reified code did contain casts before every pair

That may have been true for Z*Z pairs, but it cannot have been true for, e.g., Z*Z*Z pairs nor Z*list Z pairs, because there is no way to annotate such nodes with casts.

I'll try updating the cast exempt list tomorrow.

**Comment by jadephilipoom** [comment]
I see. `Z*Z` pairs were the only ones in the code before, so I must have overgeneralized from that.

It looks like you'll also have to modify `translate_cast_exempt` to support pairs -- or modify the `then` case in `translate_expr` to look for pairs and call `translate_expr` recursively on the pair elements.

**Comment by JasonGross** [comment]
I've decided to instead modify the condition on `translate_expr` to also check if the expression we're translating is a pair, and to treat pairs as if we don't require a cast.  That makes pairs synthesize correctly, now I'm trying to figure out why `(fun (x1 : Z) (x2 : list Z) => (x1, x2))` fails.

Interestingly, even the function header is wrong on this one; we get `uintptr_t f(uintptr_t out1, uintptr_t in0, uintptr_t in1)` rather than `uintptr_t f(uintptr_t in0, uintptr_t in1, uintptr_t out1)`.  Thoughts @andres-erbsen @jadephilipoom .  (I seem to recall raising this concern previously and us not addressing it because we didn't currently use this case...)

**Comment by JasonGross** [comment]
I think in fact the approach I was following was the wrong approach, because it's `translate_cmd` that handles lists.  I think `translate_cmd` should be extended to handle pairs.

**Comment by jadephilipoom** [comment]
I think `translate_cmd` is the wrong place for this change. It handles lists because lists are only ever in the input and output -- every legal expression on lists is very predictable. That's not at all the case with pairs. What if there's a large expression with a pair in the middle? Unless that pair has a cast in front of it, modifying `translate_cmd` will not fix the issue for that case. What's wrong with modifying `translate_cast_exempt`? It seems to me that that's the right conceptual and architectural place for a fix.

> Interestingly, even the function header is wrong on this one; we get `uintptr_t f(uintptr_t out1, uintptr_t in0, uintptr_t in1)` rather than `uintptr_t f(uintptr_t in0, uintptr_t in1, uintptr_t out1)`. Thoughts @andres-erbsen @jadephilipoom . (I seem to recall raising this concern previously and us not addressing it because we didn't currently use this case...)

Hmm, not sure if this is connected, and I'm surprised by it. I mean, obviously we hadn't tested this before so I'm not *that* surprised, but it's something the current design should have handled. What discussion are you referring to? If you can link this to some aspect of the current design it would be helpful in fixing it.

If a fix can wait until the weekend, I will take a stab at this one. I do feel strongly that the change shouldn't go in `translate_cmd` if that can at all be avoided; it violates abstraction barriers.

**Comment by JasonGross** [comment]
>  What if there's a large expression with a pair in the middle?

This will never happen unless you have an uncurried function call.  We're dealing with errors that arise from output pairs here.

> What's wrong with modifying translate_cast_exempt? 

The components of the tuple are still required to have casts, it's only the pair itself that is not required to have a cast.  As far as I can tell, cast-exempt things are recursively cast-exempt, which is not the case for pairs.  Furthermore, the code for handling lists is in translate_cmd.  We need to handle pairs of lists in the output, so either the code for handling lists needs to be moved or duplicated, or the code for handling pairs needs to go in translate_cmd.

> If a fix can wait until the weekend, I will take a stab at this one. 

Indeed, it's not urgent.  And I still need to figure out why divstep fails to synthesize even with this change.
Note that https://github.com/mit-plv/fiat-crypto/pull/887 modifies translate_cmd, but it's first commit, which is later reverted, instead modifies translate_expr.  Feel free to build off these if you'd like.

**Comment by jadephilipoom** [comment]
> This will never happen unless you have an uncurried function call. We're dealing with errors that arise from output pairs here.

Is that documented/guaranteed anywhere? This entire issue, I think, stems from not really being clear on which patterns are "we haven't synthesized a function with that pattern yet" and which are "we will never generate that pattern". Anyway, if we're strictly only supporting output pairs, then I agree with putting it in `translate_cmd`.

> As far as I can tell, cast-exempt things are recursively cast-exempt, which is not the case for pairs.

Not necessarily; `translate_expr` uses `require_cast_for_arg` to determine whether a function's argument should have a cast:
https://github.com/mit-plv/fiat-crypto/blob/10baf7ed642871a537518e34087b8768dc24ec21/src/Bedrock/Field/Translation/Expr.v#L270-L272
So if you added pairs to that lists, the arguments of pairs would always need casts.

**Comment by JasonGross** [comment]
> Is that documented/guaranteed anywhere?

No to both.  (However, none of the non-fancy operations currently in the AST take pairs.)
But we don't guarantee this about list literals either.  Should we move list support to `translate_expr`?

> Anyway, if we're strictly only supporting output pairs, then I agree with putting it in `translate_cmd`.

That is what we're supporting here.

> Not necessarily; `translate_expr` uses `require_cast_for_arg`

`translate_expr` does, but `translate_cast_exempt` does not:
https://github.com/mit-plv/fiat-crypto/blob/10baf7ed642871a537518e34087b8768dc24ec21/src/Bedrock/Field/Translation/Expr.v#L257-L258
and
https://github.com/mit-plv/fiat-crypto/blob/10baf7ed642871a537518e34087b8768dc24ec21/src/Bedrock/Field/Translation/Expr.v#L237-L252


----

Should I move the list support to the final `else` case of `translate_expr`, and add support for pairs there?

**Comment by jadephilipoom** [comment]
> Should we move list support to `translate_expr`?

Definitely not! Because lists are in-memory arrays in bedrock2, it massively simplifies the proofs for the `cmd` and `expr` levels if we can assume we're not doing anything at all with lists except for indexing into them and assembling them as final output (actually, come to think of it, that "assembling as final output" expects a series of cons followed by a nil -- returning a list that was given as an argument breaks its expectations and is likely part of the problem here).

Adding it to `translate_cmd` is fine, given it's only output pairs.
