### ISSUE TITLE
Coq 8.4 build diverges on Proper_iter_op

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#89]
https://github.com/mit-plv/fiat-crypto/commit/b34da8a551b3c8aa2086155ff523030126b19f2e#commitcomment-19623748

**Comment by andres-erbsen** [comment]
This specific issue was fixed in https://github.com/mit-plv/fiat-crypto/commit/7f20cf022c139dac1379dd249dd9b42998d6aced#diff-5275a52b0e0bb4404b76508ff4a209a3R246
