### ISSUE TITLE
Unverified bedrock2 wrapper functions are incorrect on divstep

### ISSUE THREAD

**Issue by JasonGross** [mit-plv/fiat-crypto#891]
https://github.com/mit-plv/fiat-crypto/blob/4be7fee8f4d551d67e2f0f5de71e07593834a64f/src/Bedrock/Standalone/Stringification.v#L108-L137
divstep contains mixed integers and lists in the output.  Can @jadephilipoom or @andres-erbsen help me write a better version of this?  Roughly, I need to somehow perform the same algorithm as `make_innames` + `make_outnames` + `translate_func` + `c_func` to print the function prototype, except instead of starting with a function `nat -> string` and getting out `ltype`s, I already have `string`s where each `ltype` should be (and they are not parameterized by `nat`, but instead are already in `type.for_each_lhs_of_arrow` / type-indexed structures.  How can I get this to work?

**Comment by andres-erbsen** [comment]
I think https://github.com/mit-plv/bedrock2/blob/master/bedrock2/src/bedrock2/ToCString.v#L118-L129 is the relevant code in bedrock2 (and it could be changed if it would make things significantly easyer)

**Comment by JasonGross** [comment]
I think this one is more of a concern:
https://github.com/mit-plv/fiat-crypto/blob/0592f006976898954bae9873d07a718eb0c3293c/src/Bedrock/Field/Translation/Func.v#L43-L87
