### ISSUE TITLE
from_bytes generates different result compare with linux kernel

### ISSUE THREAD

**Issue by supernatural** [mit-plv/fiat-crypto#912]
Compared two version of from_bytes:
```c
//kernel 5.8.0, lib/crypto/curve25519-fiat32.c
static inline void fe_frombytes_impl(uint32_t h[10], const uint8_t *s);

//mit-plv/fiat-crypto/fiat-c/src/curve25519_32.c
static void fiat_25519_from_bytes(uint32_t out1[10], const uint8_t arg1[32]);
```

and a test program:
```c
int main(int argc, char **argv)
{
    uint32_t out32[10] = {0};
    uint8_t point[32];

    for (int i=0; i<32; i++) {
        point[i] = (uint8_t)(i*i);
    }

    fiat_25519_from_bytes(out32, point);
    // fe_frombytes_impl(out32, point);
    // dump(out32);
    return 0;
}
```
Result of kernel version:
[17039616, 17187842, 36177444, 8637218, 59183782, 21242112, 39634996, 2622012, 17668679, 17174820]
mit-plv version:
[17039616, 17187842, 36177444, 8637218, 59183782, 21242112, 39634996, 2622012, 17668679, 50729252]

the last number is different.  Is this right?

**Comment by JasonGross** [comment]
If I recall correctly, most production versions of `from_bytes` will mask off high bits, while fiat-crypto's version has a precondition (mentioned in the comment of the function) that the high bits are zero.  I believe BoringSSL and other users of the library wrap the function in one that masks off higher bits.  Perhaps you're getting different results on numbers that exceed 2^255-1?

If this is the case, perhaps we should add assert statements for the bounds?

**Comment by davidben** [comment]
That's probably what's going on. The high byte here is `(uint8_t)(31*31)` which is 196. Additionally, the last words here are 17174820 = 0x1061124 and 50729252 = 0x3061124.

**Comment by supernatural** [comment]
yes, you'r right, I missed it. thanks!
