### ISSUE TITLE
fiat-rust: attemp to multiply with overflow

### ISSUE THREAD

**Issue by supernatural** [mit-plv/fiat-crypto#913]
I am using curve25519_32.rs，and get a panic:
---- tests::curve25519_generic stdout ----
thread 'tests::curve25519_generic' panicked at 'attempt to multiply with overflow', src/curve25519_32.rs:164:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```rust
pub fn fiat_25519_carry_mul(out1: &mut [u32; 10], arg1: &[u32; 10], arg2: &[u32; 10]) -> () {
  let x1: u64 = (((arg1[9]) as u64) * (((arg2[9]) * 0x26) as u64)); // this line
  let x2: u64 = (((arg1[9]) as u64) * (((arg2[8]) * 0x13) as u64));
```

here `(arg2[9]) * 0x26)` trigger this panic. should add a wrapping for such case, as `(arg2[9].wrapping_mul(0x26))`.

**Comment by JasonGross** [comment]
Thanks!  Do you think it would be okay to turn all multiplication into wrapping multiplication?  That is the intended semantics, and currently we don't track which multiplications could wrap, though we could track this if necessary.

**Comment by davidben** [comment]
Is that true for the additions too? Maybe the Rust code should just use the wrapping versions of all operations.

**Comment by supernatural** [comment]
yes, I think "wrapping_mul/wrapping_add" is safe, c/c++ do the same thing by default.

**Comment by supernatural** [comment]
Just noticed that the precondition of `fiat_25519_carry_mul`，Inbounds:
```c
/// Input Bounds:
///   arg1: [[0x0 ~> 0xc000000], [0x0 ~> 0x6000000], [0x0 ~> 0xc000000], [0x0 ~> 0x6000000], [0x0 ~> 0xc000000], [0x0 ~> 0x6000000], [0x0 ~> 0xc000000], [0x0 ~> 0x6000000], [0x0 ~> 0xc000000], [0x0 ~> 0x6000000]]
///   arg2: [[0x0 ~> 0xc000000], [0x0 ~> 0x6000000], [0x0 ~> 0xc000000], [0x0 ~> 0x6000000], [0x0 ~> 0xc000000], [0x0 ~> 0x6000000], [0x0 ~> 0xc000000], [0x0 ~> 0x6000000], [0x0 ~> 0xc000000], [0x0 ~> 0x6000000]]
```

0xc000000 * 0x13 = 0x6000000 * 0x26 = 0xe4000000, this wouldn't overflow.
My test case was run with random data, which violate this precondition, so it's not a real issue.

Sorry for the trouble, I would close this issue.
