### ISSUE TITLE
performance comparison status

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/fiat-crypto#94]
@achlipala I have measured our code against ed25519-donna and curve25519-donna, and we are doing just as well as we would have expected -- "known slowdowns only", so I guess that's a good sign. The progress towards building and comparing ecc-star can be seen at https://github.com/mitls/hacl-star/issues/1

**Comment by achlipala-biz** [comment]
Super.  I won't be surprised if we can get past some of those known slowdowns, too, which should be easier with a small extracted-Haskell example that we can all look at.

**Comment by achlipala** [comment]
Super. I won't be surprised if we can get past some of those known slowdowns, too, which should be easier with a small extracted-Haskell example that we can all look at.  (Comment reposted with proper account.)
